//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.ReportingServices.Rendering.HtmlRenderer.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RenderRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RenderRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.ReportingServices.Rendering.HtmlRenderer.RenderRes", typeof(RenderRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report chart.
        /// </summary>
        internal static string AccessibleChartLabel {
            get {
                return ResourceManager.GetString("AccessibleChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report chart - {0}.
        /// </summary>
        internal static string AccessibleChartNavigationGroupLabel {
            get {
                return ResourceManager.GetString("AccessibleChartNavigationGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report image.
        /// </summary>
        internal static string AccessibleImageLabel {
            get {
                return ResourceManager.GetString("AccessibleImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report image - {0}.
        /// </summary>
        internal static string AccessibleImageNavigationGroupLabel {
            get {
                return ResourceManager.GetString("AccessibleImageNavigationGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report table.
        /// </summary>
        internal static string AccessibleTableBoxLabel {
            get {
                return ResourceManager.GetString("AccessibleTableBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report text.
        /// </summary>
        internal static string AccessibleTextBoxLabel {
            get {
                return ResourceManager.GetString("AccessibleTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string DefaultDocMapLabel {
            get {
                return ResourceManager.GetString("DefaultDocMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Map.
        /// </summary>
        internal static string DocumentMap {
            get {
                return ResourceManager.GetString("DocumentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Document Map.
        /// </summary>
        internal static string HideDocMapTooltip {
            get {
                return ResourceManager.GetString("HideDocMapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML 4.0.
        /// </summary>
        internal static string HTML40LocalizedName {
            get {
                return ResourceManager.GetString("HTML40LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML5.
        /// </summary>
        internal static string HTML5LocalizedName {
            get {
                return ResourceManager.GetString("HTML5LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHTML (web archive).
        /// </summary>
        internal static string MHTMLLocalizedName {
            get {
                return ResourceManager.GetString("MHTMLLocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DeviceInfo.
        /// </summary>
        internal static string rrInvalidDeviceInfo {
            get {
                return ResourceManager.GetString("rrInvalidDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Section device info parameter was out of the range of valid values..
        /// </summary>
        internal static string rrInvalidSectionError {
            get {
                return ResourceManager.GetString("rrInvalidSectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Ascending.
        /// </summary>
        internal static string SortAscAltText {
            get {
                return ResourceManager.GetString("SortAscAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted Descending.
        /// </summary>
        internal static string SortDescAltText {
            get {
                return ResourceManager.GetString("SortDescAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ToggleStateCollapse {
            get {
                return ResourceManager.GetString("ToggleStateCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ToggleStateExpand {
            get {
                return ResourceManager.GetString("ToggleStateExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted.
        /// </summary>
        internal static string UnsortedAltText {
            get {
                return ResourceManager.GetString("UnsortedAltText", resourceCulture);
            }
        }
    }
}
