//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.ReportingServices.Rendering.WordRenderer.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordRenderRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordRenderRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.ReportingServices.Rendering.WordRenderer.WordRenderRes", typeof(WordRenderRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Body is too complex to export to Word.  Please group the ReportItems together into rectangles to simplify..
        /// </summary>
        internal static string ColumnsErrorBody {
            get {
                return ResourceManager.GetString("ColumnsErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Header or Footer is too complex to export to Word.  Please group the ReportItems together into rectangles to simplify..
        /// </summary>
        internal static string ColumnsErrorHeaderFooter {
            get {
                return ResourceManager.GetString("ColumnsErrorHeaderFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rectangle &apos;{0}&apos; is too complex to export to Word.  Please group the ReportItems together into rectangles to simplify..
        /// </summary>
        internal static string ColumnsErrorRectangle {
            get {
                return ResourceManager.GetString("ColumnsErrorRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PNG file.
        /// </summary>
        internal static string InvalidPNGError {
            get {
                return ResourceManager.GetString("InvalidPNGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word 2003.
        /// </summary>
        internal static string WordLocalizedName {
            get {
                return ResourceManager.GetString("WordLocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WordOpenXmlLocalizedName {
            get {
                return ResourceManager.GetString("WordOpenXmlLocalizedName", resourceCulture);
            }
        }
    }
}
