<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="DescriptionAttributeMapImage_Image" xml:space="preserve">
    <value>The image to be displayed.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_AutomaticallyAdded" xml:space="preserve">
    <value>Determines if the swatch color has been added automatically by a shape, path, or group rule.</value>
  </data>
  <data name="DescriptionAttributeViewport_ContentAutoFitMargin" xml:space="preserve">
    <value>Gets or sets the content margin (in pixels) to be used when the ContentSize property is set to AutoFit</value>
  </data>
  <data name="DescriptionAttributeMapImage_Angle" xml:space="preserve">
    <value>Determines the angle (in degrees) by which this image is rotated.</value>
  </data>
  <data name="DescriptionAttributeMapControl_GridUnderContent" xml:space="preserve">
    <value>Determines if the grid lines are to be shown above or below the content of the map.</value>
  </data>
  <data name="DescriptionAttributeShape_Name" xml:space="preserve">
    <value>Gets or sets the name of the shape.</value>
  </data>
  <data name="DescriptionAttributeShape_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributeShape_Font" xml:space="preserve">
    <value>Specifies the font of the shape's text.</value>
  </data>
  <data name="DescriptionAttributeShape_Text" xml:space="preserve">
    <value>The text to be displayed for the shape.</value>
  </data>
  <data name="DescriptionAttributeSymbol_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the symbol image.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_GroupField" xml:space="preserve">
    <value>The group field based on which to apply this rule.</value>
  </data>
  <data name="locate_cprovider_failed" xml:space="preserve">
    <value>Cannot locate calculated value with name "{0}"</value>
  </data>
  <data name="DescriptionAttributeMapControl_Legends" xml:space="preserve">
    <value>A collection containing legends of the map control.</value>
  </data>
  <data name="DescriptionAttributeMapControl_EnableViewState" xml:space="preserve">
    <value>Gets or sets a value indicating whether the control persists its view state.</value>
  </data>
  <data name="DescriptionAttributeSymbol_TextAlignment" xml:space="preserve">
    <value>Determines how the text is aligned relative to the symbol itself.</value>
  </data>
  <data name="LabelFormatPrecisionMsg" xml:space="preserve">
    <value>Precision can be empty or in range from 0 to 99.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_BorderColor" xml:space="preserve">
    <value>The color of the scale bar's border.</value>
  </data>
  <data name="DescriptionAttributePanelMargins_Left" xml:space="preserve">
    <value>The distance of the panel's visual bounds from its left edge in pixels.</value>
  </data>
  <data name="DescriptionAttributePanel_ZOrder" xml:space="preserve">
    <value>Determines the Z-order of the panel in the map control.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Angle" xml:space="preserve">
    <value>Determines the angle (in degrees) by which the text is rotated. If set to Auto, the angle will be determined automatically by the docking, or it will be 0 degrees if not docked.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_BorderStyle" xml:space="preserve">
    <value>The line style of the scale bar's border.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_BorderWidth" xml:space="preserve">
    <value>The line width of the scale bar's border, measured in pixels.</value>
  </data>
  <data name="AccessibilityNavigationPanelName" xml:space="preserve">
    <value>Navigation panel</value>
  </data>
  <data name="DescriptionAttributeMapControl_TileServerAppId" xml:space="preserve">
    <value>Gets or sets the the Bing Maps Key to be passed to the Bing Maps tile server.</value>
  </data>
  <data name="margin_error" xml:space="preserve">
    <value>The start margin must be less than the end margin.</value>
  </data>
  <data name="CategoryAttribute_GroupFields" xml:space="preserve">
    <value>Group Fields</value>
  </data>
  <data name="out_of_range" xml:space="preserve">
    <value>The argument is out of range ({0},{1}).</value>
  </data>
  <data name="DescriptionAttributeMargins_Right" xml:space="preserve">
    <value>Right margin.</value>
  </data>
  <data name="DescriptionAttributePanel_Selected" xml:space="preserve">
    <value>Determines if the panel visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Selected" xml:space="preserve">
    <value>Determines if the symbol visually appears selected.</value>
  </data>
  <data name="DescriptionAttributePanel_Location" xml:space="preserve">
    <value>The location of the panel inside the map control. Measured in percent units or in pixels.</value>
  </data>
  <data name="DescriptionAttributeShape_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="ExceptionCollorCannotBeTransparent" xml:space="preserve">
    <value>Collor cannot be transparent.</value>
  </data>
  <data name="DescriptionAttributeViewport_Zoom" xml:space="preserve">
    <value>Gets or sets the zoom value.</value>
  </data>
  <data name="DescriptionAttributeMapControl_SymbolFields" xml:space="preserve">
    <value>A collection containing all the names and types of the symbol fields</value>
  </data>
  <data name="DescriptionAttributeShape_CentralPointOffset" xml:space="preserve">
    <value>Gets or sets the offset of the shape's central point.</value>
  </data>
  <data name="DescriptionAttributeMapControl_MapLimits" xml:space="preserve">
    <value>Contains the minimum and maximum coordinates of the map in degrees.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_FontAngle" xml:space="preserve">
    <value>An additional fixed amount in degrees by which labels will be rotated.</value>
  </data>
  <data name="AccessibilityColorSwatchPanelNameRS" xml:space="preserve">
    <value>Color scale</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_NonSerializableContent" xml:space="preserve">
    <value>Comma separated list of non-serializable (Save/Load/Reset) properties.</value>
  </data>
  <data name="DescriptionAttributeMapSize_Height" xml:space="preserve">
    <value>The Height value of the size.</value>
  </data>
  <data name="DescriptionAttributeSymbol_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of the symbol.</value>
  </data>
  <data name="UnsupportedDbfNumberOfRecords" xml:space="preserve">
    <value>Unsupported DBF file format. Number of records too big.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ThumbColor" xml:space="preserve">
    <value>Determines the fill color for the slider thumb.</value>
  </data>
  <data name="DescriptionAttributeMapImage_ToolTip" xml:space="preserve">
    <value>The tooltip txt to be displayed when the cursor is over the map image.</value>
  </data>
  <data name="DescriptionAttributePathRule_CustomColors" xml:space="preserve">
    <value>A collection of user defiend colors.</value>
  </data>
  <data name="DescriptionAttributeSymbol_TextColor" xml:space="preserve">
    <value>The text color of the symbol.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_LabelType" xml:space="preserve">
    <value>Determines the positioning of the color swatch labels.</value>
  </data>
  <data name="FileToLarge" xml:space="preserve">
    <value>File is too large - larger than 4 GB.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_SnappingInterval" xml:space="preserve">
    <value>The interval to use when snapping is enabled. If 0 it will snap to the smallest tick mark interval.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_MiddleColor" xml:space="preserve">
    <value>Gets or sets the middle color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributeLayer_VisibleFromZoom" xml:space="preserve">
    <value>Specifies the minimum zoom for the map, in which the layer is visible. This property only applies when Visibility is set to 'ZoomBased'.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_Color" xml:space="preserve">
    <value>Determines the color for this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeViewport_ViewCenter" xml:space="preserve">
    <value>Gets or sets the center of the view. Measured in percents of the map content.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_IgnoreUnknownXmlAttributes" xml:space="preserve">
    <value>Indicates that unknown XML attributes and elements will be ignored without throwing an exception.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ZoomPanel" xml:space="preserve">
    <value>Contains all of the attributes for the zoom panel.</value>
  </data>
  <data name="DescriptionAttributePanel_BackSecondaryColor" xml:space="preserve">
    <value>The end color of the fill gradient. Used for gradients and hatching.</value>
  </data>
  <data name="DescriptionAttributeLegend_Items" xml:space="preserve">
    <value>Legend custom items collection.</value>
  </data>
  <data name="DescriptionAttributeMapControl_PathRules" xml:space="preserve">
    <value>A collection containing containing all the path rules.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleColor" xml:space="preserve">
    <value>Legend title text color.</value>
  </data>
  <data name="DescriptionAttributeLegend_Title" xml:space="preserve">
    <value>Legend title text.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_Name" xml:space="preserve">
    <value>Gets or sets the name of the symbol rule.</value>
  </data>
  <data name="ExceptionRightMarginCannotBeNegative" xml:space="preserve">
    <value>Right margin cannot be negative.</value>
  </data>
  <data name="CategoryAttribute_GeneralVisibility" xml:space="preserve">
    <value>General Visibility</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_Reversed" xml:space="preserve">
    <value>Determines if the zoom panel is reversed.</value>
  </data>
  <data name="DescriptionAttributeMapControl_SelectionMarkerColor" xml:space="preserve">
    <value>Determines the fill color for the markers of a selection rectangle.</value>
  </data>
  <data name="DescriptionAttributePathRule_Name" xml:space="preserve">
    <value>Gets or sets the name of the path rule.</value>
  </data>
  <data name="DescriptionAttributePathRule_Text" xml:space="preserve">
    <value>Gets or sets the text to be displayed for all paths to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeLegend_TextWrapThreshold" xml:space="preserve">
    <value>Defines the preferred number of characters in the legend text after which it will wrap. Set this property to zero to disable text wrapping.</value>
  </data>
  <data name="EmptyFile" xml:space="preserve">
    <value>The file is empty.</value>
  </data>
  <data name="DescriptionAttributeMapControl_KeyboardNavigation" xml:space="preserve">
    <value>Specifies whether the keyboard can be used for panning and zooming the map.</value>
  </data>
  <data name="symboldatabind_bad_loc_arg" xml:space="preserve">
    <value>To databind symbols coordinate fields have to be specified.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_FillSecondaryColor" xml:space="preserve">
    <value>The end color of the scale bar fill gradient.</value>
  </data>
  <data name="DescriptionAttributeLayer_TileSystem" xml:space="preserve">
    <value>Specifies the visiblity of the layer.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_Interval" xml:space="preserve">
    <value>Gets or sets the spacing between the grid lines in degrees.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ProjectionCenter" xml:space="preserve">
    <value>Contains the center of the map projection in degrees.</value>
  </data>
  <data name="DescriptionAttributeViewport_LoadTilesAsynchronously" xml:space="preserve">
    <value>Determines if the map control waits for all the tiles to download before it finishes painting.</value>
  </data>
  <data name="DescriptionAttributePanel_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributeMapControl_TileCulture" xml:space="preserve">
    <value>Gets or sets the culture to use for the Virtual Earth tiles.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LabelFormatString" xml:space="preserve">
    <value>Determines the text to be used when a color range is added to the legend.</value>
  </data>
  <data name="DescriptionAttributeSymbol_ImageResizeMode" xml:space="preserve">
    <value>Determines whether or not the image will be stretched to fit the size as specified by the 'Width' and 'Height' properties.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_HeaderFont" xml:space="preserve">
    <value>Legend column header text font.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_HeaderText" xml:space="preserve">
    <value>Legend column header text.</value>
  </data>
  <data name="DescriptionAttributeShape_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of the shape.</value>
  </data>
  <data name="ExceptionTextThresholdValueTooSmall" xml:space="preserve">
    <value>Text threshold value cannot be a negative number.</value>
  </data>
  <data name="AccessibilityMapImageName" xml:space="preserve">
    <value>Map image {0}</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ColorCount" xml:space="preserve">
    <value>Gets or sets the number of colors that will be automatically generated by this shape rule.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_SymbolSize" xml:space="preserve">
    <value>Legend cell image or marker symbol size (as a percentage of legend font size). Set CellType to Symbol to use this property.</value>
  </data>
  <data name="DescriptionAttributeDockablePanel_Dock" xml:space="preserve">
    <value>Gets or sets the docking style of the panel.</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_SymbolBorderColor" xml:space="preserve">
    <value>Determines the border color of the symbols on the navigation buttons.</value>
  </data>
  <data name="CategoryAttribute_MouseAndKeyboard" xml:space="preserve">
    <value>Mouse and Keyboard</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_ToValue" xml:space="preserve">
    <value>Determines the end value for this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_MaximumPin" xml:space="preserve">
    <value>Attributes for the maximum pin of the scale.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Shape" xml:space="preserve">
    <value>Shape of the custom map area. Effects the coordinates that must be set so that the shape is drawn correctly.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_Dock" xml:space="preserve">
    <value>Gets or sets the docking style of the panel.</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_SymbolColor" xml:space="preserve">
    <value>Determines the color of the symbols on the navigation buttons.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_WidthCount" xml:space="preserve">
    <value>Gets or sets the number of widths that will be automatically generated by this path rule.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Coordinates" xml:space="preserve">
    <value>Coordinates of the map area. The Shape property determines how many coordinates are required to correctly draw the shape.</value>
  </data>
  <data name="property_negative" xml:space="preserve">
    <value>The {0} property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_MajorTickMark" xml:space="preserve">
    <value>The major tick marks attributes of this scale.</value>
  </data>
  <data name="CategoryAttribute_ShapeFields" xml:space="preserve">
    <value>Shape Fields</value>
  </data>
  <data name="ExceptionArrayOfPointsCannotBeNull" xml:space="preserve">
    <value>The array of points cannot be null.</value>
  </data>
  <data name="CategoryAttribute_CellColumns" xml:space="preserve">
    <value>CellColumns</value>
  </data>
  <data name="DescriptionAttributeMapControl_TileServerMaxConnections" xml:space="preserve">
    <value>Gets or sets the maximum number of simultaneous connections that can be established to the Virtual Earth tile server.</value>
  </data>
  <data name="DescriptionAttributeGroup_Layer" xml:space="preserve">
    <value>Determines the layer that this group belongs to.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_ShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the shadow will be drawn. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapCore_DimIntensity" xml:space="preserve">
    <value>Intensity of dimming for the map control when the control doesn't have the focus.The value of this property must be in the range of 0 (min) - 100 (max)</value>
  </data>
  <data name="DescriptionAttributeGroup_Color" xml:space="preserve">
    <value>Gets or sets the fill color for the group.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ImageMapEnabled" xml:space="preserve">
    <value>Determines if client-side image maps are enabled.</value>
  </data>
  <data name="AccessibilityMapLabelName" xml:space="preserve">
    <value>Map label {0}</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ToolTip" xml:space="preserve">
    <value>Gets or sets the tooltip to be displayed for all shapes to which this rule applies.</value>
  </data>
  <data name="CategoryAttribute_Position" xml:space="preserve">
    <value>Position</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Text" xml:space="preserve">
    <value>Specifies the legend item's text.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Href" xml:space="preserve">
    <value>URL target of the map area.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Name" xml:space="preserve">
    <value>Specifies the name of this legend item.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleAlignment" xml:space="preserve">
    <value>Legend title horizontal text alignment.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LabelColor" xml:space="preserve">
    <value>Gets or sets the text color for the grid labels.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for the automatically generated colors. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ToColor" xml:space="preserve">
    <value>Gets or sets the end color for the automatically generated colors.</value>
  </data>
  <data name="ExceptionMarkerBorderMustBeGreaterThanZero" xml:space="preserve">
    <value>Marker border must be greater than 0.</value>
  </data>
  <data name="DescriptionAttributeSymbol_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of the symbol.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleBackColor" xml:space="preserve">
    <value>Legend title background color.</value>
  </data>
  <data name="hot_region_error_initialize" xml:space="preserve">
    <value>The element "{0}" is not initialized.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_ToolTip" xml:space="preserve">
    <value>Legend column tooltip. This is only applicable to items that are automatically generated.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Visible" xml:space="preserve">
    <value>Determines whether or not to show the tick marks.</value>
  </data>
  <data name="DescriptionAttributeFrame_FrameStyle" xml:space="preserve">
    <value>Frame style.</value>
  </data>
  <data name="DescriptionAttributeField_Name" xml:space="preserve">
    <value>Gets or sets the name of the field.</value>
  </data>
  <data name="DescriptionAttributeField_Type" xml:space="preserve">
    <value>Gets or sets the type of this field.</value>
  </data>
  <data name="DescriptionAttributeGroup_TextAlignment" xml:space="preserve">
    <value>Specifies how the text is aligned within the group.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for this color. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeViewport_MinimumZoom" xml:space="preserve">
    <value>Gets or sets the minimum zoom value.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ImageAlign" xml:space="preserve">
    <value>Legend item's background image alignment.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_TextAlignment" xml:space="preserve">
    <value>Specifies how the text is aligned within the map label.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ImageTranspColor" xml:space="preserve">
    <value>Legend item background image transparent color.</value>
  </data>
  <data name="ExceptionBottomMarginCannotBeNegative" xml:space="preserve">
    <value>Bottom margin cannot be negative.</value>
  </data>
  <data name="ExceptionInvalidCoordinate" xml:space="preserve">
    <value>The value "{0}" is not a valid coordinate.</value>
  </data>
  <data name="DescriptionAttributeLegendCellCollection_Item" xml:space="preserve">
    <value>Legend item cell collection indexer. The legend cell name or integer index can be provided as a parameter.</value>
  </data>
  <data name="DescriptionAttributeProjectionCenter_X" xml:space="preserve">
    <value>Gets or sets the X coordinate of the projection center in degrees.</value>
  </data>
  <data name="DescriptionAttributeProjectionCenter_Y" xml:space="preserve">
    <value>Gets or sets the Y coordinate of the projection center in degrees.</value>
  </data>
  <data name="invalid_button_type" xml:space="preserve">
    <value>Invalid button type.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_SnapToTickMarks" xml:space="preserve">
    <value>Specifies whether the position of the slider thumb should be forced to align with the positions of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_DataGrouping" xml:space="preserve">
    <value>Determines the data grouping method to use when generating the data intervals.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Minimum" xml:space="preserve">
    <value>The start value of the scale.</value>
  </data>
  <data name="DescriptionAttributeViewport_ContentSize" xml:space="preserve">
    <value>Gets or sets the total horizontal size of the content (in pixels) at 100 percent zoom. If set to AutoFit or 0, the content size will be automatically calculated so that it fits the available space at 100 percent zoom.</value>
  </data>
  <data name="ExceptionMaximumZoomtooLarge" xml:space="preserve">
    <value>The maximum zoom cannot be larger than {0}.</value>
  </data>
  <data name="DescriptionAttributeSymbolDataBindingRule_ParentShapeField" xml:space="preserve">
    <value>The field in the data source that will provide identification of the shape this symbol belongs to.</value>
  </data>
  <data name="CategoryAttribute_Interval" xml:space="preserve">
    <value>Interval</value>
  </data>
  <data name="DescriptionAttributeShape_Layer" xml:space="preserve">
    <value>Determines the layer to which this shape belongs.</value>
  </data>
  <data name="UnsupportedDbfEncryption" xml:space="preserve">
    <value>DBF encryption is not supported.</value>
  </data>
  <data name="DescriptionAttributePathDataBindingRule_BindingField" xml:space="preserve">
    <value>The name of a data source field which uniquely identifies a path.</value>
  </data>
  <data name="DescriptionAttributeShape_Color" xml:space="preserve">
    <value>Gets or sets the fill color of the shape.</value>
  </data>
  <data name="DescriptionAttributeLegend_AutoFitText" xml:space="preserve">
    <value>Legend text automatic fitting flag.</value>
  </data>
  <data name="DescriptionAttributeTileServerUrl_Url" xml:space="preserve">
    <value>Gets or sets the url to be used for the specified tile system under the specified culture. This property must be set to a valid Virtual Earth tiles server url.</value>
  </data>
  <data name="DescriptionAttributeLayer_Visibility" xml:space="preserve">
    <value>Specifies the visiblity of the layer.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_BorderColor" xml:space="preserve">
    <value>Gets or sets the border color to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeLegend_CellColumns" xml:space="preserve">
    <value>Legend columns collection.</value>
  </data>
  <data name="CategoryAttribute_MapControl" xml:space="preserve">
    <value>Map Control</value>
  </data>
  <data name="CategoryAttribute_MapContent" xml:space="preserve">
    <value>Map Content</value>
  </data>
  <data name="DescriptionAttributeSymbol_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the symbol used for gradients and hatches.</value>
  </data>
  <data name="AccessibilityLegendTitleName" xml:space="preserve">
    <value>Legend {0} title</value>
  </data>
  <data name="DescriptionAttributeShape_ShapeData" xml:space="preserve">
    <value>Contains all the graphical primitives of the shape.</value>
  </data>
  <data name="ExceptionInvalidKeywordFormat" xml:space="preserve">
    <value>Invalid keyword format: "{0}".</value>
  </data>
  <data name="DescriptionAttributeLegendItem_SeriesName" xml:space="preserve">
    <value>Legend item series name.</value>
  </data>
  <data name="CategoryAttribute_CustomColors" xml:space="preserve">
    <value>Custom Colors</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_BorderColorInLegend" xml:space="preserve">
    <value>Gets or sets the path border color that will appear in the legend for this rule.</value>
  </data>
  <data name="no_destination_type" xml:space="preserve">
    <value>Destination type has not been provided.</value>
  </data>
  <data name="DescriptionAttributeGroupDataBindingRule_BindingField" xml:space="preserve">
    <value>The name of a data source field which uniquely identifies a group.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_HatchStyle" xml:space="preserve">
    <value>Legend item background hatch style.</value>
  </data>
  <data name="CategoryAttribute_Title" xml:space="preserve">
    <value>Title</value>
  </data>
  <data name="CategoryAttribute_Paths" xml:space="preserve">
    <value>Paths</value>
  </data>
  <data name="CategoryAttribute_Shape" xml:space="preserve">
    <value>Shape</value>
  </data>
  <data name="max_min_error" xml:space="preserve">
    <value>The maximum zoom level must be greater than the minimum.</value>
  </data>
  <data name="DescriptionAttributeShapeDataBindingRule_BindingField" xml:space="preserve">
    <value>The name of a data source field which uniquely identifies a shape.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_Visible" xml:space="preserve">
    <value>Gets or sets the visibility of the grid lines.</value>
  </data>
  <data name="must_in_range" xml:space="preserve">
    <value>The argument must be in range ({0},{1}).</value>
  </data>
  <data name="CategoryAttribute_Image" xml:space="preserve">
    <value>Image</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_ShowLabels" xml:space="preserve">
    <value>Determines whether the grid labels will be shown or not.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_LabelInterval" xml:space="preserve">
    <value>Determines the frequency of the labels appearing along the color bar. A value of 0 means no labels will be displayed.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the shadow would appear. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGroup_Offset" xml:space="preserve">
    <value>Gets or sets the group offset in percent units.</value>
  </data>
  <data name="bad_data_src_fields" xml:space="preserve">
    <value>The datasource does not support the IEnumerable interface OR some of the provided field names are empty.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ColoringMode" xml:space="preserve">
    <value>Determines whether to use a color range or distinct colors.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_Font" xml:space="preserve">
    <value>Specifies the font of the labels.</value>
  </data>
  <data name="DescriptionAttributeGroup_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_PredefinedSymbols" xml:space="preserve">
    <value>A collection of pre-defined symbols.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_LegendText" xml:space="preserve">
    <value>Determines the text to be used for a legend item that is added to an existing legend.</value>
  </data>
  <data name="DescriptionAttributePath_Category" xml:space="preserve">
    <value>Gets or sets the category of this path.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type to be used for all groups to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeMapLocation_Y" xml:space="preserve">
    <value>The Y value of the location.</value>
  </data>
  <data name="DescriptionAttributeMapLocation_X" xml:space="preserve">
    <value>The X value of the location. </value>
  </data>
  <data name="out_of_range_min_close" xml:space="preserve">
    <value>The argument cannot be less than {0}.</value>
  </data>
  <data name="DescriptionAttributePathRule_DataGrouping" xml:space="preserve">
    <value>Determines the data grouping method to use when generating the data intervals.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BackColor" xml:space="preserve">
    <value>The background color of the map label.</value>
  </data>
  <data name="digits_decimals_error" xml:space="preserve">
    <value>The digits must be greater than the decimals.</value>
  </data>
  <data name="DescriptionAttributePathRule_LineStyleInLegend" xml:space="preserve">
    <value>Gets or sets the path line style that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Length" xml:space="preserve">
    <value>The length of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_LegendText" xml:space="preserve">
    <value>Gets or sets the text to be shown in the legend.</value>
  </data>
  <data name="DescriptionAttributeLayer_Transparency" xml:space="preserve">
    <value>Determines the transparency of all map elements that belong to this layer. Measured in percents.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_NoData" xml:space="preserve">
    <value>Determines whether the data attribute value for this color is defined.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LineStyle" xml:space="preserve">
    <value>Gets or sets the line style of the grid lines.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Maximum" xml:space="preserve">
    <value>The end value of the scale.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_MiddleColor" xml:space="preserve">
    <value>Gets or sets the middle color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LineWidth" xml:space="preserve">
    <value>Gets or sets the line width for the grid lines.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Meridians" xml:space="preserve">
    <value>Contains all of the meridian settings for the map control.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LineColor" xml:space="preserve">
    <value>Gets or sets the color of the grid lines.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_ColorInLegend" xml:space="preserve">
    <value>Gets or sets the color that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributePath_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the path used for gradients and hatches.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleSeparator" xml:space="preserve">
    <value>Legend title visual separator type.</value>
  </data>
  <data name="duplicate_object_failed" xml:space="preserve">
    <value>Invalid attempt to insert an object that already exists in collection {0}</value>
  </data>
  <data name="AccessibilityMapLabelNameRS" xml:space="preserve">
    <value>Map title {0}</value>
  </data>
  <data name="DescriptionAttributeTileServerUrl_SupportedTileSystem" xml:space="preserve">
    <value>Gets or sets the supported tile system for the specified culture.</value>
  </data>
  <data name="databind_state_error" xml:space="preserve">
    <value>Cannot perform data binding when input value state is in playback, databinding, or suspended mode.</value>
  </data>
  <data name="ExceptionCannotRenameField" xml:space="preserve">
    <value>Cannot rename this field since it contains data.</value>
  </data>
  <data name="CategoryAttribute_Appearance" xml:space="preserve">
    <value>Appearance</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_FillGradientType" xml:space="preserve">
    <value>The primary fill gradient type of the pointer.</value>
  </data>
  <data name="DescriptionAttributeDataBindingRuleBase_DataMember" xml:space="preserve">
    <value>Gets or sets the specific data member in a multi-member data source to bind to the map.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_DistanceFromScale" xml:space="preserve">
    <value>Determines how far away the labels will be from the scale. Measured as a percentage of the width or height of the associated scale's parent object</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_TitleColor" xml:space="preserve">
    <value>Determines the text color for the color swatch title.</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_Font" xml:space="preserve">
    <value>Determines the font of the position.</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_Text" xml:space="preserve">
    <value>The text to be displayed.</value>
  </data>
  <data name="ExceptionValueCannotBeLessThanOne" xml:space="preserve">
    <value>The value of this property cannot be less than 1.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_TitleAlignment" xml:space="preserve">
    <value>Determines the alignment for the title text.</value>
  </data>
  <data name="DescriptionAttributePathRule_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type to be used for all paths to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeSymbol_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the symbol.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Viewport" xml:space="preserve">
    <value>Contains all of the viewport attributes for the map control.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_PathWidth" xml:space="preserve">
    <value>Legend item path width.</value>
  </data>
  <data name="ExceptionAutoFitMinFontSizeMinValue" xml:space="preserve">
    <value>AutoFitMinFontSize property value can not be less than 5.</value>
  </data>
  <data name="element_not_found" xml:space="preserve">
    <value>{0} with the name "{1}" cannot be found in the {2} collection.</value>
  </data>
  <data name="DescriptionAttributeNamedElement_Collection" xml:space="preserve">
    <value>The named element's parent collection.</value>
  </data>
  <data name="ExceptionXamlGeometryNotSupported" xml:space="preserve">
    <value>The stream geometry command {0} is not supported.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of the predefined symbol.</value>
  </data>
  <data name="CategoryAttribute_TypeSpecific" xml:space="preserve">
    <value>Type Specific</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Cursor" xml:space="preserve">
    <value>The cursor to be displayed when the mouse is over this pointer.</value>
  </data>
  <data name="CategoryAttribute_Coordinates" xml:space="preserve">
    <value>Coordinates</value>
  </data>
  <data name="CategoryAttribute_Symbols" xml:space="preserve">
    <value>Symbols</value>
  </data>
  <data name="DescriptionAttributePathRule_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style to be used for all paths to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_BorderWidth" xml:space="preserve">
    <value>The border width of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_Format" xml:space="preserve">
    <value>Format used to serialize the map data.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Category" xml:space="preserve">
    <value>Gets or sets the category of this symbol.</value>
  </data>
  <data name="DescriptionAttributeMargins_Top" xml:space="preserve">
    <value>Top margin.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerSecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the marker used for gradients and hatches.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BackGradientType" xml:space="preserve">
    <value>The gradient type of the map label's background.</value>
  </data>
  <data name="DescriptionAttributePathRule_Category" xml:space="preserve">
    <value>Gets or sets the category of paths to which this path rule will be applied.</value>
  </data>
  <data name="DescriptionAttributeImageOrigin_NotSet" xml:space="preserve">
    <value>Determines if the image origin is not set.</value>
  </data>
  <data name="DescriptionAttributeMapControl_GroupRules" xml:space="preserve">
    <value>A collection containing containing all the group rules.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_BorderColor" xml:space="preserve">
    <value>The border color of the tick marks.</value>
  </data>
  <data name="ExceptionFieldNameDoesNotExist" xml:space="preserve">
    <value>A field with name {0} does not exist.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_BorderColor" xml:space="preserve">
    <value>Gets or sets the color of the predefined symbol's border.</value>
  </data>
  <data name="hot_region_error_support" xml:space="preserve">
    <value>The element "{0}" does not support its own coordinate system.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_BorderWidth" xml:space="preserve">
    <value>The line width of the predefined symbol's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ColorCount" xml:space="preserve">
    <value>Gets or sets the number of colors that will be automatically generated by this group rule.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_BorderStyle" xml:space="preserve">
    <value>The line style of the predefined symbol's border.</value>
  </data>
  <data name="ExceptionArrayOfPointsMustContainOnePoint" xml:space="preserve">
    <value>The array of points must contain at least one point.</value>
  </data>
  <data name="ExceptionLegendTableColumnSpacingTooSmall" xml:space="preserve">
    <value>Legend table column spacing must be equal to or greater than 0.</value>
  </data>
  <data name="DescriptionAttributeMapLimits_MaximumX" xml:space="preserve">
    <value>Gets or sets the maximum X coordinate of the map in degrees.</value>
  </data>
  <data name="DescriptionAttributeMapLimits_MaximumY" xml:space="preserve">
    <value>Gets or sets the maximum Y coordinate of the map in degrees.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_HeaderColor" xml:space="preserve">
    <value>Legend column header text color.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Height" xml:space="preserve">
    <value>Gets or sets the predefined symbol height in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the map label.</value>
  </data>
  <data name="duration_negative" xml:space="preserve">
    <value>The duration value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Font" xml:space="preserve">
    <value>Specifies the font of the symbol's label.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Name" xml:space="preserve">
    <value>Gets or sets the name of the symbol.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Text" xml:space="preserve">
    <value>The text to be displayed for the symbol.</value>
  </data>
  <data name="CategoryAttribute_CustomWidths" xml:space="preserve">
    <value>Custom Widths</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of this color swatch element used for gradients and hatches.</value>
  </data>
  <data name="AccessibilityShapeName" xml:space="preserve">
    <value>Shape {0}</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_MinimumWidth" xml:space="preserve">
    <value>Legend column minimum width (as a percentage of legend font size). Set this property to -1 for automatic calculation.</value>
  </data>
  <data name="symbol_databinding_not_enough_params" xml:space="preserve">
    <value>Some of the parameters for data binding map symbols (category field, x or y coordinates fields) are not specified.</value>
  </data>
  <data name="DescriptionAttributeLegend_InterlacedRows" xml:space="preserve">
    <value>Indicate that legend rows should be drawn with interlaced background color.</value>
  </data>
  <data name="ExceptionInvalidIndexerArgument" xml:space="preserve">
    <value>Invalid indexer argument.</value>
  </data>
  <data name="DescriptionAttributeLayer_UseSecureConnectionForTiles" xml:space="preserve">
    <value>Specifies if all the communication with the tile server (including the downloading of the tile) should be done using a secure connection (SSL).</value>
  </data>
  <data name="ProvideBingMapsAppID" xml:space="preserve">
    <value>In order to use a Bing Maps layer, please obtain an AppID from Bing and place it in the LocalReport.MapTileServerConfiguration.AppID property of the ReportViewer control.</value>
  </data>
  <data name="DescriptionAttributePathRule_WidthInLegend" xml:space="preserve">
    <value>Gets or sets the path width that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributeLinearMinorTickMark_Length" xml:space="preserve">
    <value>The length of the tick marks.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the predefined symbol image.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_FillColor" xml:space="preserve">
    <value>The fill color of the tick mark.</value>
  </data>
  <data name="CategoryAttribute_ParallelsAndMeridians" xml:space="preserve">
    <value>Parallels and Meridians</value>
  </data>
  <data name="DescriptionAttributeMapControl_RenderingImageUrl" xml:space="preserve">
    <value>The URL of a custom rendering image, which will be displayed while the map control is rendering its content.</value>
  </data>
  <data name="DescriptionAttributeMapControl_GroupFields" xml:space="preserve">
    <value>A collection containing all the names and types of the group fields.</value>
  </data>
  <data name="DescriptionAttributeShape_TextAlignment" xml:space="preserve">
    <value>Specifies how the text is aligned within the shape.</value>
  </data>
  <data name="DescriptionAttributePanel_Size" xml:space="preserve">
    <value>The size of the panel measured in percents or in pixels.</value>
  </data>
  <data name="DescriptionAttributePanel_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Fields" xml:space="preserve">
    <value>Gets or sets the {0} field. At run-time use the "symbol["{0}"]" syntax.</value>
  </data>
  <data name="DescriptionAttributeLinearMajorTickMark_Width" xml:space="preserve">
    <value>The width of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_Text" xml:space="preserve">
    <value>Gets or sets the text to be used for the given range of values.</value>
  </data>
  <data name="min_log_error" xml:space="preserve">
    <value>The Minimum property cannot be less OR equal than 0 on logarithmic scales.</value>
  </data>
  <data name="DescriptionAttributeLinearMajorTickMark_Shape" xml:space="preserve">
    <value>Determines the shape of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeMapCore_BorderLineColor" xml:space="preserve">
    <value>Gets or sets the color of the control's border.</value>
  </data>
  <data name="decimals_negative" xml:space="preserve">
    <value>The decimals property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeMapCore_BorderLineWidth" xml:space="preserve">
    <value>The line width of the control's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapCore_BorderLineStyle" xml:space="preserve">
    <value>The line style of the control's border.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_Font" xml:space="preserve">
    <value>Specifies the font for the parallel and meridian grid labels.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_TextAlignment" xml:space="preserve">
    <value>Determines how the text is aligned relative to the predefined symbol itself.</value>
  </data>
  <data name="DescriptionAttributePanel_Visible" xml:space="preserve">
    <value>Determines the visibility of the panel.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeGroup_Visible" xml:space="preserve">
    <value>Determines the visibility of the group.</value>
  </data>
  <data name="DescriptionAttributeGroup_Fields" xml:space="preserve">
    <value>Gets or sets the {0} field. At run-time use the "group["{0}"]" syntax.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_FillHatchStyle" xml:space="preserve">
    <value>The primary fill hatch style of the pointer.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_ImageResizeMode" xml:space="preserve">
    <value>Determines whether or not the image will be stretched to fit the specified size as determined by the Width and Height properties.</value>
  </data>
  <data name="AccessibilityPathName" xml:space="preserve">
    <value>Path {0}</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_ButtonColor" xml:space="preserve">
    <value>Determines the background color for the navigation buttons.</value>
  </data>
  <data name="DescriptionAttributeMapControl_AutoLimitsIgnoreSymbols" xml:space="preserve">
    <value>Gets or sets a flag indicating whether symbols should be ignored when automatically determining the map limits when GeographyMode is set to true.</value>
  </data>
  <data name="DescriptionAttributePath_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of the path.</value>
  </data>
  <data name="CategoryAttribute_Zooming" xml:space="preserve">
    <value>Zooming</value>
  </data>
  <data name="empty_name_failed" xml:space="preserve">
    <value>The name of this {0} element cannot be empty.</value>
  </data>
  <data name="DescriptionAttributeMapControl_TagAttributes" xml:space="preserve">
    <value>Additional attributes that are to be placed inside the rendered tag.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerBorderStyle" xml:space="preserve">
    <value>The line style of the marker border.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerBorderWidth" xml:space="preserve">
    <value>Legend item marker border width.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerBorderColor" xml:space="preserve">
    <value>Legend item marker border color.</value>
  </data>
  <data name="DescriptionAttributeTileServerUrl_Culture" xml:space="preserve">
    <value>Gets or sets the culture to which the specified tile system and server url apply.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ShadowIntensity" xml:space="preserve">
    <value>The intensity of all shadows, measured as a percentage.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleSeparatorColor" xml:space="preserve">
    <value>Legend title visual separator color.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumnCollection_Item" xml:space="preserve">
    <value>Legend column collection indexer. The legend column name or integer index can be provided as a parameter.</value>
  </data>
  <data name="ExceptionPathWidthMustBeGreaterThanZero" xml:space="preserve">
    <value>Path width must be greater than 0.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_Interval" xml:space="preserve">
    <value>Determines how often the labels will show.</value>
  </data>
  <data name="DescriptionAttributeMapControl_MapAreas" xml:space="preserve">
    <value>Map area collection, which stores custom map area objects.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Visible" xml:space="preserve">
    <value>Legend item is not visible if set to false.</value>
  </data>
  <data name="DescriptionAttributeGroup_Text" xml:space="preserve">
    <value>The text to be displayed for the group.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_ToWidth" xml:space="preserve">
    <value>Gets or sets the end width for the automatically generated widths.</value>
  </data>
  <data name="DescriptionAttributeGroup_Name" xml:space="preserve">
    <value>Gets or sets the name of the group.</value>
  </data>
  <data name="DescriptionAttributeGroup_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributeGroup_Font" xml:space="preserve">
    <value>Specifies the font for the group's text.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for the automatically generated widths. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Shapes" xml:space="preserve">
    <value>A collection containing the all the shapes of the map.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Printing" xml:space="preserve">
    <value>Printing object.</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_Placement" xml:space="preserve">
    <value>Determines the placement of the position's label, relative to the scale.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ShowInColorSwatch" xml:space="preserve">
    <value>Determines if the colors generated by this rule are to be added to the color swatch.</value>
  </data>
  <data name="DescriptionAttributeShape_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of the shape.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ContentCachingTimeout" xml:space="preserve">
    <value>Gets or sets the content caching timeout in minutes.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_Name" xml:space="preserve">
    <value>Gets or sets the name of the shape rule.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_Text" xml:space="preserve">
    <value>Gets or sets the text to be displayed for all shapes to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributePath_LineStyle" xml:space="preserve">
    <value>Gets or sets the line style of the path.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_BorderColor" xml:space="preserve">
    <value>Gets or sets the border color to be used for the given range of values.</value>
  </data>
  <data name="ExceptionCannotLoadImageFromLocation" xml:space="preserve">
    <value>Cannot load image from this location: {0}</value>
  </data>
  <data name="DescriptionAttributeMapLabel_TextColor" xml:space="preserve">
    <value>The text color of the map label.</value>
  </data>
  <data name="UnsupportedDbfTransactions" xml:space="preserve">
    <value>DBF transactions are not supported.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_FillGradientType" xml:space="preserve">
    <value>The fill gradient type of the scale's bar.</value>
  </data>
  <data name="CategoryAttribute_Values" xml:space="preserve">
    <value>Values</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_TickMarkLength" xml:space="preserve">
    <value>Determines the length of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_IntervalOffset" xml:space="preserve">
    <value>Determines the amount by which the scale's tick marks and labels will be offset. </value>
  </data>
  <data name="DescriptionAttributeLegendItem_Separator" xml:space="preserve">
    <value>Legend item visual separator type.</value>
  </data>
  <data name="DescriptionAttributeMargins_Left" xml:space="preserve">
    <value>Left margin.</value>
  </data>
  <data name="DescriptionAttributePanel_BackShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the back shadow will be.</value>
  </data>
  <data name="DescriptionAttributeSymbolDataBindingRule_YCoordinateField" xml:space="preserve">
    <value>Specifies the field in the data source that will provide data for the symbols' Y property.</value>
  </data>
  <data name="DescriptionAttributeFrame_BorderStyle" xml:space="preserve">
    <value>Frame border line style.</value>
  </data>
  <data name="DescriptionAttributeFrame_BorderWidth" xml:space="preserve">
    <value>Frame border line width.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Width" xml:space="preserve">
    <value>The width of the scale bar, measured as a percent.</value>
  </data>
  <data name="DescriptionAttributeSymbol_X" xml:space="preserve">
    <value>Gets or sets the X coordinate of the symbol in geographical units.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Y" xml:space="preserve">
    <value>Gets or sets the Y coordinate of the symbol in geographical units.</value>
  </data>
  <data name="AccessibilityDistanceScalePanelNameRS" xml:space="preserve">
    <value>Distance scale</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_Orientation" xml:space="preserve">
    <value>Determines if the zoom panel is oriented horizontally or vertically.</value>
  </data>
  <data name="DescriptionAttributeLegend_TextColor" xml:space="preserve">
    <value>Determines legend text color.</value>
  </data>
  <data name="period_negative" xml:space="preserve">
    <value>The period value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_CellSpan" xml:space="preserve">
    <value>Indicates the number of horizontal cells used to draw the content.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_CellType" xml:space="preserve">
    <value>Legend cell type.</value>
  </data>
  <data name="DescriptionAttributeFrame_BorderColor" xml:space="preserve">
    <value>Frame border color.</value>
  </data>
  <data name="DescriptionAttributeSymbol_ParentShape" xml:space="preserve">
    <value>Determines the shape to which this symbol belongs.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerWidth" xml:space="preserve">
    <value>Gets or sets the marker width in pixels.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerStyle" xml:space="preserve">
    <value>Legend item marker style.</value>
  </data>
  <data name="DescriptionAttributeShape_ScaleFactor" xml:space="preserve">
    <value>Gets or sets the scale factor. The scale factor determines if a shape will be inflated or deflated.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Interactive" xml:space="preserve">
    <value>Determines whether the user can move the pointer with the mouse by clicking and dragging.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BackHatchStyle" xml:space="preserve">
    <value>The hatch style of the control's background.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Symbols" xml:space="preserve">
    <value>A collection containing all of the symbols for the map.</value>
  </data>
  <data name="DescriptionAttributeLegend_InterlacedRowsColor" xml:space="preserve">
    <value>Legend interlaced rows background color.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerColor" xml:space="preserve">
    <value>Legend item marker color.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerImage" xml:space="preserve">
    <value>Legend item marker image.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="UnableToReadWholeFileToSqlBinary" xml:space="preserve">
    <value>Unable to read whole file to SqlBinary.</value>
  </data>
  <data name="invalid_parent" xml:space="preserve">
    <value>Cannot locate "{0}".</value>
  </data>
  <data name="UnsupportedDbfLongRecords" xml:space="preserve">
    <value>Unsupported DBF file format. Record length is too big.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Height" xml:space="preserve">
    <value>Height of the map container, measured in UnitType.Pixel.</value>
  </data>
  <data name="DescriptionAttributeShape_Visible" xml:space="preserve">
    <value>Determines the visibility of the shape.</value>
  </data>
  <data name="DescriptionAttributeMapControl_TileServerTimeout" xml:space="preserve">
    <value>Gets or sets the request timeout in milliseconds for the Virtual Earth tile server.</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_Width" xml:space="preserve">
    <value>Gets or sets the width to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeMapCore_DimWhenNotFocused" xml:space="preserve">
    <value>Specifies whether the control content should be dimmed when the control loses the focus.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Images" xml:space="preserve">
    <value>A collection containing map images of the control.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the pointer.</value>
  </data>
  <data name="duplicate_name_failed" xml:space="preserve">
    <value>This element cannot duplicate its name with another element in the same collection.</value>
  </data>
  <data name="ExceptionUnknownBorderType" xml:space="preserve">
    <value>Unknown border type "{0}".</value>
  </data>
  <data name="DescriptionAttributeSymbolDataBindingRule_Category" xml:space="preserve">
    <value>Specifies the category of the symbols affected by this property.</value>
  </data>
  <data name="DescriptionAttributeMapCore_ControlType" xml:space="preserve">
    <value>Control build type.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Cells" xml:space="preserve">
    <value>Collection of legend item cells.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Color" xml:space="preserve">
    <value>Legend item color.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_Image" xml:space="preserve">
    <value>Legend item image.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_LegendText" xml:space="preserve">
    <value>Determines the text to be used when a color range is added to a legend.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for this color. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ImageUrl" xml:space="preserve">
    <value>The URL where the map image is saved, when an image or input tag is used for rendering.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Href" xml:space="preserve">
    <value>The Href of the object.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Type" xml:space="preserve">
    <value>Determines if the pointer type is marker or bar.</value>
  </data>
  <data name="AccessibilitySymbolName" xml:space="preserve">
    <value>Symbol {0}</value>
  </data>
  <data name="DescriptionAttributeSymbolDataBindingRule_XCoordinateField" xml:space="preserve">
    <value>Specifies the field in the data source that will provide data for the symbols' X property.</value>
  </data>
  <data name="DescriptionAttributeMapControl_GeographyMode" xml:space="preserve">
    <value>Gets or sets a value indicating the map control is in geography mode. When in geography mode the bounding rectangle will be limited from -180 to +180 on the x-axis and from -90 to +90 on the y-axis.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ContentCachingEnabled" xml:space="preserve">
    <value>Determines if content caching is enabled. When content caching is enabled the server generated images are cached on the server and are not being regenerated for every single user and every single request.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BackShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the back shadow will be.</value>
  </data>
  <data name="DescriptionAttributePanelMargins_Right" xml:space="preserve">
    <value>The distance of the panel's visual bounds from its right edge in pixels.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_SymbolBorderColor" xml:space="preserve">
    <value>Determines the border color for the button symbols.</value>
  </data>
  <data name="DescriptionAttributeMapArea_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="invalid_object_type" xml:space="preserve">
    <value>The collection {0} cannot accept this object. {1} object type required.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the predefined symbol.</value>
  </data>
  <data name="CategoryAttribute_Widths" xml:space="preserve">
    <value>Widths</value>
  </data>
  <data name="DescriptionAttributeMapControl_SymbolRules" xml:space="preserve">
    <value>A collection containing containing all the symbol rules.</value>
  </data>
  <data name="DescriptionAttributeMapControl_DataBindingRules" xml:space="preserve">
    <value>A collection that contains all of the data binding objects in the map control.</value>
  </data>
  <data name="CategoryAttribute_SymbolText" xml:space="preserve">
    <value>Symbol Text</value>
  </data>
  <data name="DescriptionAttributeMapControl_Layers" xml:space="preserve">
    <value>A collection containing the layers of the map.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Labels" xml:space="preserve">
    <value>A collection containing map labels of the control.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_CustomColors" xml:space="preserve">
    <value>A collection of user defined colors.</value>
  </data>
  <data name="circular_reference" xml:space="preserve">
    <value>Circular reference detected.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Offset" xml:space="preserve">
    <value>Gets or sets the symbol offset.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_MarkerStyle" xml:space="preserve">
    <value>Determines the marker style for this symbol.</value>
  </data>
  <data name="CategoryAttribute_Interactivity" xml:space="preserve">
    <value>Interactivity</value>
  </data>
  <data name="DescriptionAttributeNamedElement_ParentElement" xml:space="preserve">
    <value>Reference to parent element of the parent collection.</value>
  </data>
  <data name="DescriptionAttributeLegend_EquallySpacedItems" xml:space="preserve">
    <value>Indicates that all legend items are equally spaced.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the scale.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_LabelAlignment" xml:space="preserve">
    <value>Determines how the color swatch labels are positioned along the color bar.</value>
  </data>
  <data name="DescriptionAttributeGroup_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type for the group.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_BorderColor" xml:space="preserve">
    <value>Gets or sets the border color to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_CustomWidths" xml:space="preserve">
    <value>A collection of user defiend widths.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Category" xml:space="preserve">
    <value>Gets or sets the category of this symbol.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_Category" xml:space="preserve">
    <value>Gets or sets the category of symbols to which this symbol rule will be applied.</value>
  </data>
  <data name="CategoryAttribute_Panels" xml:space="preserve">
    <value>Panels</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BackSecondaryColor" xml:space="preserve">
    <value>The end color of the fill gradient. Used for gradients and hatching.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackHatchStyle" xml:space="preserve">
    <value>Frame background hatch style.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_StartMargin" xml:space="preserve">
    <value>Determines the distance between the start of the linear gauge and the start of the scale in percent.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Height" xml:space="preserve">
    <value>Gets or sets the symbol height in pixels.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ToColor" xml:space="preserve">
    <value>Gets or sets the end color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_Placement" xml:space="preserve">
    <value>Determines the position of the labels relative to the scale.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_NumericLabelFormat" xml:space="preserve">
    <value>Determines the format string used to display numeric labels.</value>
  </data>
  <data name="DescriptionAttributeMapImage_Href" xml:space="preserve">
    <value>The Href of the map image.</value>
  </data>
  <data name="DescriptionAttributeMapImage_Name" xml:space="preserve">
    <value>The name of the map image.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for the automatically generated colors. Leave empty to determine this value automatically.</value>
  </data>
  <data name="CategoryAttribute_Shapes" xml:space="preserve">
    <value>Shapes</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ToolTip" xml:space="preserve">
    <value>Gets or sets the tooltip text to be displayed for all groups to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_TextValue" xml:space="preserve">
    <value>Determines the text value of this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeMapControl_MouseWheelZooming" xml:space="preserve">
    <value>Specifies whether the mouse wheel (if present) can be used to zoom in and out.</value>
  </data>
  <data name="DescriptionAttributeLegend_AutoFitMinFontSize" xml:space="preserve">
    <value>Gets or sets the minimum font size that can be used by the legend text auto-fitting algorithm.</value>
  </data>
  <data name="DescriptionAttributeShape_ChildSymbolMargin" xml:space="preserve">
    <value>Gets or sets the distance between two child symbols belonging to this shape. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Placement" xml:space="preserve">
    <value>Determines if the pointer should touch the scale bar on the inside or the outside.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Paths" xml:space="preserve">
    <value>A collection containing the all the paths of the map.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_SymbolField" xml:space="preserve">
    <value>The symbol field to be used for data grouping.</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_LegendText" xml:space="preserve">
    <value>Gets or sets the text to be shown in the legend.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Width" xml:space="preserve">
    <value>Width of the map container, measured in UnitType.Pixel.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_LogarithmicBase" xml:space="preserve">
    <value>Determines the base for logarithmic scales.</value>
  </data>
  <data name="DescriptionAttributePathRule_UseCustomColors" xml:space="preserve">
    <value>Determines if the CustomColors collection is to be used instead of automatically generating the colors.</value>
  </data>
  <data name="ExceptionBorderWidthMustBeGreaterThanZero" xml:space="preserve">
    <value>Border width must be greater than 0.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Frame" xml:space="preserve">
    <value>Map border skin style.</value>
  </data>
  <data name="DescriptionAttributeLegend_HeaderSeparatorColor" xml:space="preserve">
    <value>Legend header visual separator color.</value>
  </data>
  <data name="gdi_noninitialized" xml:space="preserve">
    <value>Internal error. GDI engine is not initialized.</value>
  </data>
  <data name="DescriptionAttributePath_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributePath_Name" xml:space="preserve">
    <value>Gets or sets the name of the path.</value>
  </data>
  <data name="DescriptionAttributePath_Font" xml:space="preserve">
    <value>Specifies the font of the path's text.</value>
  </data>
  <data name="DescriptionAttributePath_Text" xml:space="preserve">
    <value>The text to be displayed for the path.</value>
  </data>
  <data name="CategoryAttribute_MapArea" xml:space="preserve">
    <value>MapArea</value>
  </data>
  <data name="UnsupportedDbfField" xml:space="preserve">
    <value>Bad field ({0}) id.</value>
  </data>
  <data name="DescriptionAttributeShape_BorderColor" xml:space="preserve">
    <value>Gets or sets the color of the shape's border.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Visible" xml:space="preserve">
    <value>Determines the visibility of the symbol.</value>
  </data>
  <data name="DescriptionAttributeMapImage_ShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the shadow will appear. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Parallels" xml:space="preserve">
    <value>Contains all of the parallel settings for the map control.</value>
  </data>
  <data name="DescriptionAttributeAutoSizePanel_AutoSize" xml:space="preserve">
    <value>Determines whether the panel will be automatically sized based on its content.</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeGroup_CentralPoint" xml:space="preserve">
    <value>The central point of the group in map coordinates.</value>
  </data>
  <data name="DescriptionAttributeShape_BorderStyle" xml:space="preserve">
    <value>The line style of the shape's border.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for the automatically generated data intervals. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeMapControl_TextAntiAliasingQuality" xml:space="preserve">
    <value>The quality of all text anti-aliasing.</value>
  </data>
  <data name="DescriptionAttributeShape_BorderWidth" xml:space="preserve">
    <value>The line width of the shape's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeShape_TextColor" xml:space="preserve">
    <value>The text color of the shape.</value>
  </data>
  <data name="UnsupportedDbfRecordFlag" xml:space="preserve">
    <value>Bad record flag.</value>
  </data>
  <data name="DescriptionAttributePanel_BorderStyle" xml:space="preserve">
    <value>The line style of the panel's border.</value>
  </data>
  <data name="DescriptionAttributePath_ParentGroup" xml:space="preserve">
    <value>Determines the group to which this path belongs.</value>
  </data>
  <data name="DescriptionAttributePanel_BorderWidth" xml:space="preserve">
    <value>The line width of the panel's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeShape_CentralPoint" xml:space="preserve">
    <value>The central point of the shape in map coordinates.</value>
  </data>
  <data name="DescriptionAttributeMapControl_PathFields" xml:space="preserve">
    <value>A collection containing all the names and types of the path fields.</value>
  </data>
  <data name="DescriptionAttributeShape_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the shape used for gradients and hatches.</value>
  </data>
  <data name="DescriptionAttributePanel_BorderColor" xml:space="preserve">
    <value>Gets or sets the color of the panel's border.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_TextColor" xml:space="preserve">
    <value>The text color of the predefined symbol.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_SliderBarBorderColor" xml:space="preserve">
    <value>Determines the border color for the slider bar.</value>
  </data>
  <data name="column_not_found" xml:space="preserve">
    <value>A column with the name "{0}" was not found.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the color to be used for all shapes to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Href" xml:space="preserve">
    <value>The Href of the scale.</value>
  </data>
  <data name="invalid_param" xml:space="preserve">
    <value>The {0} is not valid parameter for this method.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_MaximumWidth" xml:space="preserve">
    <value>Legend column maximum width (as a percentage of legend font size). Set this property to -1 for automatic calculation.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ShapeRules" xml:space="preserve">
    <value>A collection containing containing all the shape rules.</value>
  </data>
  <data name="CategoryAttribute_LabelVisibility" xml:space="preserve">
    <value>Label Visibility</value>
  </data>
  <data name="DescriptionAttributeGroupRule_UseCustomColors" xml:space="preserve">
    <value>Determines if the 'CustomColors' collection is to be used instead of automatically generating the colors.</value>
  </data>
  <data name="DescriptionAttributeSymbol_ShadowOffset" xml:space="preserve">
    <value>Gets or sets how far to the right and how far down the shadow will be. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Margins" xml:space="preserve">
    <value>Legend cell margins (as a percentage of legend font size).</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BackHatchStyle" xml:space="preserve">
    <value>The hatch style of the map label's background.</value>
  </data>
  <data name="DescriptionAttributeLegend_LegendStyle" xml:space="preserve">
    <value>Legend style.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ColorPalette" xml:space="preserve">
    <value>Determines the color palette to be used when applying distinct colors.</value>
  </data>
  <data name="DescriptionAttributeDistanceScalePanel_ScaleForeColor" xml:space="preserve">
    <value>Determines the fill color for the distance scale bar.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_SecondaryColor" xml:space="preserve">
    <value>Legend item background secondary color.</value>
  </data>
  <data name="CategoryAttribute_SymbolFields" xml:space="preserve">
    <value>Symbol Fields</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ImageOrigin" xml:space="preserve">
    <value>The point on the image that represents the pointer origin (in pixels).</value>
  </data>
  <data name="interval_offset_negative" xml:space="preserve">
    <value>The interval offset value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_ImageSize" xml:space="preserve">
    <value>Legend cell image size as a percentage of legend font size. If property is set to Size.Empty, the original image size (in pixels) is used.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_UseCustomWidths" xml:space="preserve">
    <value>Determines if the CustomWidths collection is to be used instead of automatically generating the widths.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_BorderStyle" xml:space="preserve">
    <value>Legend item border line style.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_RangeGapColor" xml:space="preserve">
    <value>Determines the color used to fill color divisions that correspond to range values which are not defined. This property only applies when the LabelType is set to 'ShowBorderValue'.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_BorderWidth" xml:space="preserve">
    <value>Legend item border width.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Text" xml:space="preserve">
    <value>The text to be displayed for the map label.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Href" xml:space="preserve">
    <value>The Href of the map label.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Name" xml:space="preserve">
    <value>The name of the map label.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Font" xml:space="preserve">
    <value>Specifies the font of the map label.</value>
  </data>
  <data name="DescriptionAttributeLegend_ItemColumnSeparator" xml:space="preserve">
    <value>Legend table columns visual separator type.</value>
  </data>
  <data name="DescriptionAttributeLegend_ItemColumnSpacing" xml:space="preserve">
    <value>Legend table column spacing (as a percentage of the legend font).</value>
  </data>
  <data name="DescriptionAttributeFrame_BackSecondaryColor" xml:space="preserve">
    <value>Frame secondary back color which is used for gradient coloring and hatching.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_BorderColor" xml:space="preserve">
    <value>Legend item border color.</value>
  </data>
  <data name="DescriptionAttributePath_PathData" xml:space="preserve">
    <value>Contains all the graphical primitives of the path.</value>
  </data>
  <data name="ExceptionValueFormatIncorrect" xml:space="preserve">
    <value>The value "{0}"" is not a correct format.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_LegendText" xml:space="preserve">
    <value>Gets or sets the text to be shown in the legend.</value>
  </data>
  <data name="DescriptionAttributeDistanceScalePanel_LabelColor" xml:space="preserve">
    <value>Determines the text color for the distance scale labels.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Groups" xml:space="preserve">
    <value>A collection containing the groups of the map.</value>
  </data>
  <data name="DescriptionAttributePathRule_BorderWidthInLegend" xml:space="preserve">
    <value>Gets or sets the path border width that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributeAutoSizePanel_MaxAutoSize" xml:space="preserve">
    <value>Maximum size of the panel when auto sizing is enabled. The size must be specified in percent of the viewport if the panel is docked inside the viewport or in persent of the map control if the panel is docked outside the viewport.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ShadowOffset" xml:space="preserve">
    <value>Legend item shadow offset.</value>
  </data>
  <data name="ExceptionLeftMarginCannotBeNegative" xml:space="preserve">
    <value>Left margin cannot be negative.</value>
  </data>
  <data name="wrong_padding_format" xml:space="preserve">
    <value>The text entered is in wrong format.</value>
  </data>
  <data name="CategoryAttribute_ViewState" xml:space="preserve">
    <value>ViewState</value>
  </data>
  <data name="AccessibilityShapeNameRS" xml:space="preserve">
    <value>Polygon {0}</value>
  </data>
  <data name="field_NAME_add" xml:space="preserve">
    <value>Field with name 'NAME' cannot be added to the {0} collection </value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_CellColumnAttributes" xml:space="preserve">
    <value>Other attributes of the legend items.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BackSecondaryColor" xml:space="preserve">
    <value>The end color of the fill gradient. Used for gradients and hatching.</value>
  </data>
  <data name="AccessibilityParallelsName" xml:space="preserve">
    <value>Parallels</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ShowInLegend" xml:space="preserve">
    <value>Specifies the legend to which the colors generated by this rule are to be added.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_DistanceFromScale" xml:space="preserve">
    <value>Determines the offset of the tick mark from its normal position.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ButtonColor" xml:space="preserve">
    <value>Determines the background color for the zoom panel buttons.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_ShowEndLabels" xml:space="preserve">
    <value>Determines if the end labels of the scale are visible.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ItemStyle" xml:space="preserve">
    <value>Legend item graphical indicator style.</value>
  </data>
  <data name="DescriptionAttributeMapControl_TileCacheLevel" xml:space="preserve">
    <value>Gets or sets the tile cache level to use when doaloding tiles from the the Virtual Earth server.</value>
  </data>
  <data name="DescriptionAttributePanel_Margins" xml:space="preserve">
    <value>Determines a rectangular area that surrounds the panel. Margins are included in the panel's size.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style to be used for all shapes to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_FormatString" xml:space="preserve">
    <value>The format string that is to be used for all labels.</value>
  </data>
  <data name="DescriptionAttributeShape_Category" xml:space="preserve">
    <value>Gets or sets the category of this shape.</value>
  </data>
  <data name="AccessibilityZoomPanelName" xml:space="preserve">
    <value>Zoom panel</value>
  </data>
  <data name="DescriptionAttributeNamedImage_Image" xml:space="preserve">
    <value>Image object to be used as a named image.</value>
  </data>
  <data name="DescriptionAttributePanel_BackHatchStyle" xml:space="preserve">
    <value>The hatch style of the panel's background.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the tick mark image.</value>
  </data>
  <data name="ExceptionInvalidCoordonateString" xml:space="preserve">
    <value>The string "{0}" is not a valid coordinate string.</value>
  </data>
  <data name="DescriptionAttributePathRule_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the color to be used for all paths to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_Colors" xml:space="preserve">
    <value>Values displayed in the color swatch panel.</value>
  </data>
  <data name="DescriptionAttributeMapCore_BuildNumber" xml:space="preserve">
    <value>Control build number.</value>
  </data>
  <data name="DescriptionAttributeMapControl_NamedImages" xml:space="preserve">
    <value>Named images collection. Named images are saved as resources.</value>
  </data>
  <data name="DescriptionAttributeTickMark_IntervalOffset" xml:space="preserve">
    <value>A value by which the tick marks and labels will be offset. </value>
  </data>
  <data name="DescriptionAttributePanel_SizeUnit" xml:space="preserve">
    <value>Gets or sets the units for the Size property.</value>
  </data>
  <data name="CategoryAttribute_Groups" xml:space="preserve">
    <value>Groups</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Position" xml:space="preserve">
    <value>Determines the position of the scale.</value>
  </data>
  <data name="DescriptionAttributeLegend_HeaderSeparator" xml:space="preserve">
    <value>Legend header visual separator type.</value>
  </data>
  <data name="DescriptionAttributeMapImage_ResizeMode" xml:space="preserve">
    <value>Determines whether or not the image will be stretched to fit the specified size.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Font" xml:space="preserve">
    <value>Specifies the font of the predefined symbol's label.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Name" xml:space="preserve">
    <value>Gets or sets the name of the predefined symbol.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Text" xml:space="preserve">
    <value>The text to be displayed for the predefined symbol.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="UnableToAllocateMemoryForSqlBinary" xml:space="preserve">
    <value>Unable to allocate memory for SqlBinary.</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_ButtonBorderColor" xml:space="preserve">
    <value>Determines the border color of the navigation buttons.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_Category" xml:space="preserve">
    <value>Gets or sets the category of shapes to which this shape rule will be applied.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_ShowInLegend" xml:space="preserve">
    <value>Specifies the legend to which legend items will be automatically added by this rule.</value>
  </data>
  <data name="ExceptionXamlBrushNotSupported" xml:space="preserve">
    <value>The brush {0} is not supported.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_BorderStyle" xml:space="preserve">
    <value>The line style of the map label border.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_OutlineColor" xml:space="preserve">
    <value>Determines the outline color for color bar divisions.</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_ScrollStep" xml:space="preserve">
    <value>Specifies the scrolling step in percents of the viewport.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ImageType" xml:space="preserve">
    <value>Determines the type of image to be rendered. Can be Png, Jpg, Bmp, etc.</value>
  </data>
  <data name="field_duplication" xml:space="preserve">
    <value>Field with name {0}, but different type already exists in the {1}'s field collection. Field type is {2}, but data type is {3}.  NOTE that data type has been converted to the most appropriate type supported by map object fields.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_SnappingEnabled" xml:space="preserve">
    <value>Determines if snapping of the pointer's value to a given interval is enabled.</value>
  </data>
  <data name="DescriptionAttributeNamedElement_Name" xml:space="preserve">
    <value>Gets or sets the name of the NamedElement.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_AutomaticallyAdded" xml:space="preserve">
    <value>Determines if the item has been added automatically by a shape, path, symbol, or group rule.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Value" xml:space="preserve">
    <value>The value to which this pointer currently points.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Image" xml:space="preserve">
    <value>The image to be used as a pointer.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_EnableGradient" xml:space="preserve">
    <value>Determines whether or not a gradient effect is used for the tick mark.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Image" xml:space="preserve">
    <value>Legend cell image name. Set CellType to Image to use this property.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Width" xml:space="preserve">
    <value>The width of the pointer.</value>
  </data>
  <data name="DescriptionAttributeMapLimits_MinimumX" xml:space="preserve">
    <value>Gets or sets the minimum X coordinate of the map in degrees.</value>
  </data>
  <data name="DescriptionAttributeMapLimits_MinimumY" xml:space="preserve">
    <value>Gets or sets the minimum Y coordinate of the map in degrees.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of the predefined symbol.</value>
  </data>
  <data name="DescriptionAttributeGroup_BorderStyle" xml:space="preserve">
    <value>The line style for the group's border.</value>
  </data>
  <data name="DescriptionAttributeGroup_BorderWidth" xml:space="preserve">
    <value>The line width for the group's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeViewport_MaximumZoom" xml:space="preserve">
    <value>Gets or sets the maximum zoom value.</value>
  </data>
  <data name="DescriptionAttributeShape_TextVisibility" xml:space="preserve">
    <value>Determines whether the text of the shape is to be shown or hidden.</value>
  </data>
  <data name="ExceptionCannotContainSpaces" xml:space="preserve">
    <value>The name cannot contain spaces.</value>
  </data>
  <data name="DescriptionAttributeGroup_BorderColor" xml:space="preserve">
    <value>Gets or sets the border color for the group.</value>
  </data>
  <data name="DescriptionAttributeLayer_LabelVisibleFromZoom" xml:space="preserve">
    <value>Specifies the minimum zoom, at which the labels of the elements assigned to this layer will be visible.</value>
  </data>
  <data name="DescriptionAttributeShape_Offset" xml:space="preserve">
    <value>Gets or sets the shape offset, which can be used to offset a shape from its original location.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_BorderColor" xml:space="preserve">
    <value>The color of the border.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_ColorPalette" xml:space="preserve">
    <value>Determines the color palette to be used when applying distinct colors.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_BorderStyle" xml:space="preserve">
    <value>The line style of the border.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_SerializableContent" xml:space="preserve">
    <value>Comma separated list of serializable (Save/Load/Reset) properties.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_BorderWidth" xml:space="preserve">
    <value>The line width of the border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ShowInLegend" xml:space="preserve">
    <value>Specifies the legend to which the colors generated by this rule are to be added.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ZoomButtonsVisible" xml:space="preserve">
    <value>Determines the visibility of the zoom-in and zoom-out buttons.</value>
  </data>
  <data name="interval_negative" xml:space="preserve">
    <value>The interval value cannot be less than zero.</value>
  </data>
  <data name="CategoryAttribute_Colors" xml:space="preserve">
    <value>Colors</value>
  </data>
  <data name="DescriptionAttributePath_Selected" xml:space="preserve">
    <value>Determines if the path visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ColoringMode" xml:space="preserve">
    <value>Determines whether to use a color range or distinct colors.</value>
  </data>
  <data name="DescriptionAttributeLegend_TitleFont" xml:space="preserve">
    <value>Legend title font.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Name" xml:space="preserve">
    <value>Map area name.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Href" xml:space="preserve">
    <value>URL target of the map area.</value>
  </data>
  <data name="DescriptionAttributeMapImage_Visible" xml:space="preserve">
    <value>Determines the visibility of the map image.</value>
  </data>
  <data name="DescriptionAttributePanel_LocationUnit" xml:space="preserve">
    <value>Gets or sets the units for the Location property.</value>
  </data>
  <data name="Map_BackgroundNotAvailable" xml:space="preserve">
    <value>The map background from Bing is not available for this locale.</value>
  </data>
  <data name="DescriptionAttributePathRule_ColorPalette" xml:space="preserve">
    <value>Determines the color palette to be used when applying distinct colors.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_GradientType" xml:space="preserve">
    <value>Gets or sets the gradient type to be used for all shapes to which this rule applies</value>
  </data>
  <data name="LabelFormatPrecisionMsgCaption" xml:space="preserve">
    <value>Error</value>
  </data>
  <data name="parent_not_renderable" xml:space="preserve">
    <value>The "{0}" does not support its own coordinate system.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_TickMarksOnTop" xml:space="preserve">
    <value>Determines if the tick marks should drawn over pointers.</value>
  </data>
  <data name="CategoryAttribute_Marker" xml:space="preserve">
    <value>Marker</value>
  </data>
  <data name="DescriptionAttributeMapImage_Transparency" xml:space="preserve">
    <value>Determines the transparency of the image. Measured as a percentage.</value>
  </data>
  <data name="DescriptionAttributePath_ShadowOffset" xml:space="preserve">
    <value>Gets or sets how far to the right and how far down the shadow will be. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_ShowEndLabels" xml:space="preserve">
    <value>Determines whether the panel will show the first and last labels along the color bar. This property applies only when the LabelType is set to 'ShowBorderValue'</value>
  </data>
  <data name="locate_iprovider_failed" xml:space="preserve">
    <value>Cannot locate input value with name "{0}"</value>
  </data>
  <data name="DescriptionAttributeMapImage_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the image's map area.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_Font" xml:space="preserve">
    <value>Specifies the font for the color swatch labels.</value>
  </data>
  <data name="CategoryAttribute_VirtualEarth" xml:space="preserve">
    <value>Virtual Earth</value>
  </data>
  <data name="CategoryAttribute_Layers" xml:space="preserve">
    <value>Layers</value>
  </data>
  <data name="CategoryAttribute_Layout" xml:space="preserve">
    <value>Layout</value>
  </data>
  <data name="ExceptionIntervalGraterThanZero" xml:space="preserve">
    <value>The interval must be greater than 0.</value>
  </data>
  <data name="CategoryAttribute_Legend" xml:space="preserve">
    <value>Legend</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_FontUnit" xml:space="preserve">
    <value>Determines if the font size is measured as a percentage of the parent or in units specified in the Font.Unit property.</value>
  </data>
  <data name="DescriptionAttributeLinearMajorTickMark_Length" xml:space="preserve">
    <value>The length of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeDistanceScalePanel_Font" xml:space="preserve">
    <value>Specifies the font for the distance scale labels.</value>
  </data>
  <data name="DescriptionAttributeSymbolDataBindingRule_BindingField" xml:space="preserve">
    <value>The name of a data source field which uniquely identifies a symbol.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerHeight" xml:space="preserve">
    <value>Gets or sets the marker height in pixels.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_FontUnit" xml:space="preserve">
    <value>Determines if the font size is measured as a percentage of the parent or in units specified in the Font.Unit property.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_LegendText" xml:space="preserve">
    <value>Determines the text to be used when a color range is added to the legend.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ColorSwatchPanel" xml:space="preserve">
    <value>Contains all of the attributes for the color swatch.</value>
  </data>
  <data name="CategoryAttribute_LabelsAndTickMarks" xml:space="preserve">
    <value>Labels and Tick Marks</value>
  </data>
  <data name="DescriptionAttributeTickMark_Interval" xml:space="preserve">
    <value>Determines how often the tick marks will be drawn.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_GradientTypeInLegend" xml:space="preserve">
    <value>Gets or sets the gradient type that will appear in the legend for this rule.</value>
  </data>
  <data name="ExceptionMaximumLegendAutoSize" xml:space="preserve">
    <value>Maximum legend auto size must not be less than 0.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ToolTip" xml:space="preserve">
    <value>Tooltip of the legend item.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ShapeFields" xml:space="preserve">
    <value>A collection containing all the names and types of the shape fields.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Visible" xml:space="preserve">
    <value>Determines the visibility of the pointer.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_ResetWhenLoading" xml:space="preserve">
    <value>Determines if object properties are reset to their default values prior to loading.</value>
  </data>
  <data name="DescriptionAttributeShape_Fields" xml:space="preserve">
    <value>Gets or sets the {0} field. At run-time use the "shape["{0}"]" syntax.</value>
  </data>
  <data name="DescriptionAttributePath_LabelPosition" xml:space="preserve">
    <value>Determines if the path label will be centered inside the path or if it will appear above or below the path.</value>
  </data>
  <data name="AccessibilityPathNameRS" xml:space="preserve">
    <value>Line {0}</value>
  </data>
  <data name="AccessibilitySymbolNameRS" xml:space="preserve">
    <value>Point {0}</value>
  </data>
  <data name="DescriptionAttributeGroupRule_FromColor" xml:space="preserve">
    <value>Gets or sets the start color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributeSymbol_SymbolData" xml:space="preserve">
    <value>Contains all the points of the symbol.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for the automatically generated colors.  Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for the automatically generated colors. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributePathRule_MiddleColor" xml:space="preserve">
    <value>Gets or sets the middle color for the automatically generated colors.</value>
  </data>
  <data name="CategoryAttribute_Header" xml:space="preserve">
    <value>Header</value>
  </data>
  <data name="DescriptionAttributeShapeRule_FromColor" xml:space="preserve">
    <value>Gets or sets the start color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributePanel_BackGradientType" xml:space="preserve">
    <value>The gradient type of the panel's background.</value>
  </data>
  <data name="ExceptionValueCannotBeNegative" xml:space="preserve">
    <value>The value cannot be negative.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Color" xml:space="preserve">
    <value>Gets or sets the color of the predefined symbol.</value>
  </data>
  <data name="out_of_range_min_open" xml:space="preserve">
    <value>The argument must be greater than {0}.</value>
  </data>
  <data name="generate_name_failed" xml:space="preserve">
    <value>Internal exception : Generating unique name failed.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_TitleFont" xml:space="preserve">
    <value>Specifies the font for the color swatch's title.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_Category" xml:space="preserve">
    <value>Gets or sets the category of groups to which this group rule will be applied.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Image" xml:space="preserve">
    <value>The image to be used for this symbol.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_ShadowOffset" xml:space="preserve">
    <value>Gets or sets how far to the right and how far down the shadow will be. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Width" xml:space="preserve">
    <value>Gets or sets the predefined symbol width in pixels.</value>
  </data>
  <data name="DescriptionAttributePathRule_ColoringMode" xml:space="preserve">
    <value>Determines whether to use a color range or distinct colors.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_FillColor" xml:space="preserve">
    <value>The fill color of the pointer.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_Href" xml:space="preserve">
    <value>URL target of the legend items.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_Name" xml:space="preserve">
    <value>Specifies the name of this legend cell column.</value>
  </data>
  <data name="UnsupportedDbfFieldLength" xml:space="preserve">
    <value>Length of the field of type {0} is {1}.</value>
  </data>
  <data name="ExceptionFieldMustBeOfType" xml:space="preserve">
    <value>The field {0} must be of type {1}.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_BackColor" xml:space="preserve">
    <value>Legend cell back color.</value>
  </data>
  <data name="DescriptionAttributePath_Layer" xml:space="preserve">
    <value>Determines the layer that the path belongs to.</value>
  </data>
  <data name="ExceptionTraceManagerUnsupportedType" xml:space="preserve">
    <value>Trace Manager does not provide service of type: {0}</value>
  </data>
  <data name="DescriptionAttributePath_Visible" xml:space="preserve">
    <value>Determines the visibility of the path.</value>
  </data>
  <data name="DescriptionAttributePath_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributePath_Color" xml:space="preserve">
    <value>Gets or sets the fill color of the path.</value>
  </data>
  <data name="decimals_digits_error" xml:space="preserve">
    <value>The decimals must be less than the digits.</value>
  </data>
  <data name="DescriptionAttributeViewport_EnablePanning" xml:space="preserve">
    <value>Determines if panning is enabled.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_ToolTip" xml:space="preserve">
    <value>Legend cell tooltip.</value>
  </data>
  <data name="DescriptionAttributePath_Width" xml:space="preserve">
    <value>The line width of the path, measured in pixels.</value>
  </data>
  <data name="ExceptionXamlInvalidCanvasSize" xml:space="preserve">
    <value>The root canvas must have its Width and Height defined.</value>
  </data>
  <data name="DescriptionAttributeImageOrigin_Y" xml:space="preserve">
    <value>The Y value of the location.</value>
  </data>
  <data name="DescriptionAttributeImageOrigin_X" xml:space="preserve">
    <value>The X value of the image origin.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_ImageTranspColor" xml:space="preserve">
    <value>Legend cell image transparent color. Set CellType to Image to use this property.</value>
  </data>
  <data name="CategoryAttribute_View" xml:space="preserve">
    <value>View</value>
  </data>
  <data name="CategoryAttribute_Size" xml:space="preserve">
    <value>Size</value>
  </data>
  <data name="CategoryAttribute_Data" xml:space="preserve">
    <value>Data</value>
  </data>
  <data name="DescriptionAttributeLegend_TableStyle" xml:space="preserve">
    <value>Legend table style.</value>
  </data>
  <data name="CategoryAttribute_Misc" xml:space="preserve">
    <value>Misc</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_NoDataText" xml:space="preserve">
    <value>Specifies the label text to use for colors with no data values.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_PanelStyle" xml:space="preserve">
    <value>Determines the style of the zoom panel.</value>
  </data>
  <data name="DescriptionAttributeGroup_Category" xml:space="preserve">
    <value>Gets or sets the category of this group.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ButtonBorderColor" xml:space="preserve">
    <value>Determines the border color for the zoom panel buttons.</value>
  </data>
  <data name="DownloadingTile" xml:space="preserve">
    <value>Please wait...</value>
  </data>
  <data name="DescriptionAttributePanel_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the panel.</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_HeaderBackColor" xml:space="preserve">
    <value>Legend column header back color.</value>
  </data>
  <data name="DescriptionAttributePathRule_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for the automatically generated colors. Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_ToolTip" xml:space="preserve">
    <value>Gets or sets the tooltip text to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Shape" xml:space="preserve">
    <value>Determines the shape of the tick mark.</value>
  </data>
  <data name="CategoryAttribute_Background" xml:space="preserve">
    <value>Background</value>
  </data>
  <data name="DescriptionAttributeCustomColor_Color" xml:space="preserve">
    <value>Gets or sets the color to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributePrintingManager_PrintDocument" xml:space="preserve">
    <value>A reusable object that sends output to a printer. Can be used for custom print routines.</value>
  </data>
  <data name="DescriptionAttributeSymbol_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Width" xml:space="preserve">
    <value>The width of the tick marks.</value>
  </data>
  <data name="playback_count_error" xml:space="preserve">
    <value>The length of the history is less than {0} records.</value>
  </data>
  <data name="DescriptionAttributePath_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of the path.</value>
  </data>
  <data name="digits_negative" xml:space="preserve">
    <value>The digits property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_MinimumPin" xml:space="preserve">
    <value>Attributes for the minimum pin of the scale.</value>
  </data>
  <data name="DescriptionAttributeSymbol_BorderColor" xml:space="preserve">
    <value>Gets or sets the color of the symbol's border.</value>
  </data>
  <data name="TileServerRequestTimeout" xml:space="preserve">
    <value>Tile server timeout: The tile server took longer than {0} milliseconds to respond.</value>
  </data>
  <data name="DescriptionAttributePathRule_FromColor" xml:space="preserve">
    <value>Gets or sets the start color for the automatically generated colors.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for this color. Leave empty to determine the value automatically.</value>
  </data>
  <data name="CategoryAttribute_PathFields" xml:space="preserve">
    <value>Path Fields</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_MarkerLength" xml:space="preserve">
    <value>Determines the length of the marker if this pointer is of type marker.</value>
  </data>
  <data name="not_supported_DataSource" xml:space="preserve">
    <value>DataSources of type {0} are not supported.</value>
  </data>
  <data name="DescriptionAttributeSymbol_BorderStyle" xml:space="preserve">
    <value>The line style of the symbol's border.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Image" xml:space="preserve">
    <value>The image to be used as a custom tick mark.</value>
  </data>
  <data name="DescriptionAttributeSymbol_BorderWidth" xml:space="preserve">
    <value>The line width of the symbol's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGroup_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style for the group.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Compression" xml:space="preserve">
    <value>Jpeg image compression value (0-100 percent).</value>
  </data>
  <data name="UnsupportedDbfHeader" xml:space="preserve">
    <value>Bad DBF header.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_ShowInColorSwatch" xml:space="preserve">
    <value>Determines if the colors generated by this rule are to be added to the color swatch panel.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style to be used for all groups to which this rule applies.</value>
  </data>
  <data name="invalid_marker_type" xml:space="preserve">
    <value>Internal error. Invalid marker type specified.</value>
  </data>
  <data name="AccessibilityColorSwatchPanelName" xml:space="preserve">
    <value>Color swatch panel</value>
  </data>
  <data name="DescriptionAttributeSwatchColor_FromValue" xml:space="preserve">
    <value>Determines the start value for this color swatch division.</value>
  </data>
  <data name="DescriptionAttributeViewport_QueryVirtualEarthAsynchronously" xml:space="preserve">
    <value>Determines if the map control will query the Virtual Earth web service asynchronously and continue rendering without the tiles.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_Title" xml:space="preserve">
    <value>Specifies the text for the color swatch's title.</value>
  </data>
  <data name="DescriptionAttributeSpecialPosition_Enable" xml:space="preserve">
    <value>Determines whether the position is enabled.</value>
  </data>
  <data name="DescriptionAttributePathRule_ShowInColorSwatch" xml:space="preserve">
    <value>Determines if the colors generated by this rule are to be added to the color swatch panel.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Interval" xml:space="preserve">
    <value>Determines how often the scale's tick marks and labels will be displayed.</value>
  </data>
  <data name="DescriptionAttributeMapControl_DataSource" xml:space="preserve">
    <value>Gets or sets the data source for data binding purposes.</value>
  </data>
  <data name="UnsupportedDbfFormat" xml:space="preserve">
    <value>Unsupported DBF file format.</value>
  </data>
  <data name="DescriptionAttributeGridAttributes_LabelPosition" xml:space="preserve">
    <value>Determines where the grid labels will be placed.</value>
  </data>
  <data name="DescriptionAttributeDistanceScalePanel_ScaleBorderColor" xml:space="preserve">
    <value>Determines the border color for distance scale bar.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_SliderBarColor" xml:space="preserve">
    <value>Determines the fill color for the slider bar.</value>
  </data>
  <data name="DescriptionAttributePath_Offset" xml:space="preserve">
    <value>Gets or sets the path offset.</value>
  </data>
  <data name="DescriptionAttributeCustomColor_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for this color. Leave empty to determine the value automatically.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_MarkerStyle" xml:space="preserve">
    <value>Determines the marker style if this pointer is of type marker.</value>
  </data>
  <data name="DescriptionAttributeMapControl_DimIntensity" xml:space="preserve">
    <value>Specifies the level of dimming for the map control when it doesn't have the focus.The value of this property must be in the range of 0(min) - 100(max)</value>
  </data>
  <data name="DescriptionAttributePanelMargins_Top" xml:space="preserve">
    <value>The distance of the panel's visual bounds from its top edge in pixels.</value>
  </data>
  <data name="DescriptionAttributePanelMargins_All" xml:space="preserve">
    <value>The distance of the panel's visual bounds from its all edges in pixels.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Reversed" xml:space="preserve">
    <value>Determines if the direction of the scale is reversed.</value>
  </data>
  <data name="AccessibilityColorSwatchTitleName" xml:space="preserve">
    <value>Color swatch panel title</value>
  </data>
  <data name="DescriptionAttributeMapControl_RenderType" xml:space="preserve">
    <value>Determines if the map should be rendered as an interactive image, an image tag, an input tag, a binary data stream or an image map.</value>
  </data>
  <data name="AccessibilityViewportName" xml:space="preserve">
    <value>Viewport</value>
  </data>
  <data name="DescriptionAttributeOffset_Y" xml:space="preserve">
    <value>Gets or sets the Y value of the shape offset, measured in geographical units (degrees).</value>
  </data>
  <data name="DescriptionAttributeOffset_X" xml:space="preserve">
    <value>Gets or sets the X value of the shape offset, measured in geographical units (degrees).</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ShapeField" xml:space="preserve">
    <value>The shape field based on which to apply this rule.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackImageTranspColor" xml:space="preserve">
    <value>Frame background image transparent color.</value>
  </data>
  <data name="DescriptionAttributeLinearMinorTickMark_Shape" xml:space="preserve">
    <value>Determines the shape of the tick mark.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_SecondaryColorInLegend" xml:space="preserve">
    <value>Gets or sets the secondary color that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributeLinearMinorTickMark_Width" xml:space="preserve">
    <value>The width of the tick marks.</value>
  </data>
  <data name="DescriptionAttributePath_BorderColor" xml:space="preserve">
    <value>Gets or sets the color of the path's border.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Visible" xml:space="preserve">
    <value>Determines the visibility of the scale.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_FillHatchStyle" xml:space="preserve">
    <value>The fill hatch style of the scale's bar.</value>
  </data>
  <data name="DescriptionAttributePath_BorderWidth" xml:space="preserve">
    <value>The line width of the path's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackImageMode" xml:space="preserve">
    <value>Frame background image drawing mode.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_MinorTickMark" xml:space="preserve">
    <value>The minor tick marks attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeMapControl_DistanceScalePanel" xml:space="preserve">
    <value>Contains all of the attributes for the distance scale.</value>
  </data>
  <data name="DescriptionAttributeGroup_ToolTip" xml:space="preserve">
    <value>The tooltip to be displayed when the cursor is over the group.</value>
  </data>
  <data name="ExceptionIndexOutOfRange" xml:space="preserve">
    <value>List index is out of range.</value>
  </data>
  <data name="DescriptionAttributeMapImage_BorderStyle" xml:space="preserve">
    <value>The line style of the image's border.</value>
  </data>
  <data name="DescriptionAttributeMapPoint_X" xml:space="preserve">
    <value>The X coordinate of the map point.</value>
  </data>
  <data name="DescriptionAttributeMapPoint_Y" xml:space="preserve">
    <value>The Y coordinate of the map point.</value>
  </data>
  <data name="DescriptionAttributePathRule_PathField" xml:space="preserve">
    <value>The path field based on which to apply this rule.</value>
  </data>
  <data name="CategoryAttribute_Behavior" xml:space="preserve">
    <value>Behavior</value>
  </data>
  <data name="DescriptionAttributeLegendCellColumn_HeaderTextAlignment" xml:space="preserve">
    <value>Legend column header text horizontal alignment.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_TemplateMode" xml:space="preserve">
    <value>Determines if the serializer works in template creation mode.</value>
  </data>
  <data name="DescriptionAttributeSpecialPosition_Location" xml:space="preserve">
    <value>Determines the location of the position (in degrees or percent), relative to the zero.</value>
  </data>
  <data name="invalid_indexer" xml:space="preserve">
    <value>Invalid indexer argument type. Valid types are int OR string</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_TextColor" xml:space="preserve">
    <value>The text color of the position.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_TickBorderColor" xml:space="preserve">
    <value>Determines the border color for the tick marks.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_UseCustomColors" xml:space="preserve">
    <value>Determines if the CustomColors collection is to be used instead of automatically generating the colors.</value>
  </data>
  <data name="DescriptionAttributeMapControl_Projection" xml:space="preserve">
    <value>Determines the projection for the map.</value>
  </data>
  <data name="DescriptionAttributeGroup_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributePath_Fields" xml:space="preserve">
    <value>Gets or sets the {0} field. At run-time use the "path["{0}"]" syntax.</value>
  </data>
  <data name="DescriptionAttributeMapArea_ToolTip" xml:space="preserve">
    <value>Tooltip of the map area.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_SeriesPointIndex" xml:space="preserve">
    <value>Legend item series data point index.</value>
  </data>
  <data name="AccessibilityMeridiansName" xml:space="preserve">
    <value>Meridians</value>
  </data>
  <data name="DescriptionAttributeCustomColor_HatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ImageWrapMode" xml:space="preserve">
    <value>Legend item's background image wrapping mode.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackImageAlign" xml:space="preserve">
    <value>Frame background image alignment used by the 'Unscaled' drawing mode.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_SymbolColor" xml:space="preserve">
    <value>Determines the fill color for the button symbols.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Multiplier" xml:space="preserve">
    <value>Amount by which the scale's values are multiplied before being displayed.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BorderLineStyle" xml:space="preserve">
    <value>The line style of the control's border.</value>
  </data>
  <data name="DescriptionAttributeSymbol_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the map area (can also be javascript).</value>
  </data>
  <data name="DescriptionAttributeLinearScale_EndMargin" xml:space="preserve">
    <value>Determines the distance between the end of the linear gauge and the end of the scale in percent.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BorderLineWidth" xml:space="preserve">
    <value>The line width of the control's border, measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the color to be used for all groups to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeMapControl_AntiAliasing" xml:space="preserve">
    <value>The smoothing (anti-aliasing) mode, applied to all map control elements.</value>
  </data>
  <data name="DescriptionAttributeMapControl_NavigationPanel" xml:space="preserve">
    <value>Contains all of the attributes for the navigation panel.</value>
  </data>
  <data name="DescriptionAttributeViewport_OptimizeForPanning" xml:space="preserve">
    <value>Determines if the control is optimized for panning.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BorderLineColor" xml:space="preserve">
    <value>Gets or sets the color of the control's border.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ZoomType" xml:space="preserve">
    <value>Determines how the panel changes the map zoom level when the thumb is moved or buttons are pressed.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Logarithmic" xml:space="preserve">
    <value>Determines if the scale is logarithmic.</value>
  </data>
  <data name="ExceptionShapeFieldNotFound" xml:space="preserve">
    <value>Error: "{0}" was not found in the MapControl.ShapeFields collection.</value>
  </data>
  <data name="DescriptionAttributeNamedElement_Tag" xml:space="preserve">
    <value>Gets or sets an object that contains data to associate with the item.</value>
  </data>
  <data name="DescriptionAttributeShape_ShadowOffset" xml:space="preserve">
    <value>Gets or sets how far to the right and how far down the shadow will be. Measured in pixels.</value>
  </data>
  <data name="UnsupportedDbfNumberOfFileds128" xml:space="preserve">
    <value>Unsupported DBF file, maximum number of fields is 128.</value>
  </data>
  <data name="bad_data_src" xml:space="preserve">
    <value>The datasource does not support the IEnumerable interface.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_GradientDensity" xml:space="preserve">
    <value>Determines the density of the gradient effect. The value is between 0 and 100 percent.</value>
  </data>
  <data name="min_max_error" xml:space="preserve">
    <value>The minimum zoom level must be less than the maximum.</value>
  </data>
  <data name="DescriptionAttributeLayer_VisibleToZoom" xml:space="preserve">
    <value>Specifies the maximum zoom for the map, in which the layer is visible. This property only applies when Visibility is set to 'ZoomBased'.</value>
  </data>
  <data name="ticknumber_out_of_range" xml:space="preserve">
    <value>Zoom panel slider needs to have at least two tick marks.</value>
  </data>
  <data name="DescriptionAttributeMapControl_SelectionBorderColor" xml:space="preserve">
    <value>Determines the border color for a selection rectangle.</value>
  </data>
  <data name="DescriptionAttributeMapImage_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the map image.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_ThumbBorderColor" xml:space="preserve">
    <value>Determines the border color for the slider thumb.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_CustomColors" xml:space="preserve">
    <value>A collection of user-defined colors.</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for this width. Leave empty to determine the value automatically.</value>
  </data>
  <data name="AccessibilityMapControlNameRS" xml:space="preserve">
    <value>Map</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_ToolTip" xml:space="preserve">
    <value>Gets or sets the tooltip text to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeMapSerializer_Content" xml:space="preserve">
    <value>Defines the serializable content for the Load, Save and Reset methods.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for the automatically generated widths. Leave empty to determine this value automatically.</value>
  </data>
  <data name="ExceptionPropertyValueCannotbeLessThanOne" xml:space="preserve">
    <value>The value of this property cannot be less than 1.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_FromWidth" xml:space="preserve">
    <value>Gets or sets the start width for the automatically generated widths.</value>
  </data>
  <data name="designer_find" xml:space="preserve">
    <value>MapControl designer has finished searching.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_DataGrouping" xml:space="preserve">
    <value>Determines the data grouping method to use when generating the data intervals.</value>
  </data>
  <data name="DescriptionAttributeDockablePanel_DockedInsideViewport" xml:space="preserve">
    <value>Gets or sets a flag indicating whether the panel is docked inside or outside of the viewport.</value>
  </data>
  <data name="DescriptionAttributeShape_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_TickCount" xml:space="preserve">
    <value>Determines the number of tick marks to display along the slider bar.</value>
  </data>
  <data name="DescriptionAttributeZoomPanel_TickColor" xml:space="preserve">
    <value>Determines the fill color for the tick marks.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the pointer image.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerImageTranspColor" xml:space="preserve">
    <value>Legend item marker image transparent color.</value>
  </data>
  <data name="DescriptionAttributeViewport_AutoSize" xml:space="preserve">
    <value>Determines whether the viewport will automatically resize to fill up the area which is not occupied by docked panels.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the predefined symbol used for gradients and hatches.</value>
  </data>
  <data name="bad_layer_name" xml:space="preserve">
    <value>'(none)' and '(all)' has special meaning and cannot be used as layer name.</value>
  </data>
  <data name="invalid_placement_type" xml:space="preserve">
    <value>Internal error. Invalid placement type specified.</value>
  </data>
  <data name="DescriptionAttributePathRule_ToolTip" xml:space="preserve">
    <value>Gets or sets the tooltip to be displayed for all paths to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeLegend_ItemColumnSeparatorColor" xml:space="preserve">
    <value>Legend table columns visual separator color.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_Visible" xml:space="preserve">
    <value>Determines the visibility of the labels.</value>
  </data>
  <data name="DescriptionAttributePathRule_ToValue" xml:space="preserve">
    <value>Gets or sets the end value for the automatically generated colors. Leave empty to determine this value automatically.</value>
  </data>
  <data name="AccessibilityLegendName" xml:space="preserve">
    <value>Legend {0}</value>
  </data>
  <data name="DescriptionAttributeLinearScale_FillColor" xml:space="preserve">
    <value>The fill color of the scale's bar.</value>
  </data>
  <data name="DescriptionAttributePathRule_ToColor" xml:space="preserve">
    <value>Gets or sets the end color for the automatically generated colors.</value>
  </data>
  <data name="symbol_coord_type" xml:space="preserve">
    <value>Cannot use  value of type {0} as symbol coordinate.</value>
  </data>
  <data name="DescriptionAttributeMapSize_Width" xml:space="preserve">
    <value>The Width value of the size.</value>
  </data>
  <data name="DescriptionAttributeNavigationPanel_PanelStyle" xml:space="preserve">
    <value>Determines the appearance style of the navigation panel.</value>
  </data>
  <data name="DescriptionAttributeLegend_Font" xml:space="preserve">
    <value>Legend item's text font.</value>
  </data>
  <data name="DescriptionAttributeLegend_Name" xml:space="preserve">
    <value>Gets or sets the name of the legend.</value>
  </data>
  <data name="ExceptionTopMarginCannotBeNegative" xml:space="preserve">
    <value>Top margin cannot be negative.</value>
  </data>
  <data name="DescriptionAttributeShape_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the shape.</value>
  </data>
  <data name="DescriptionAttributeViewport_ErrorMessage" xml:space="preserve">
    <value>Gets or sets the error message to be displayed inside the viewport.</value>
  </data>
  <data name="DescriptionAttributeSymbol_MarkerStyle" xml:space="preserve">
    <value>Determines the marker style of the symbol.</value>
  </data>
  <data name="DescriptionAttributePinMajorTickMark_Width" xml:space="preserve">
    <value>The width of the tick marks.</value>
  </data>
  <data name="DescriptionAttributePinMajorTickMark_Shape" xml:space="preserve">
    <value>Determines the shape of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeGroup_Selected" xml:space="preserve">
    <value>Determines if the group appears selected.</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_Text" xml:space="preserve">
    <value>Gets or sets the text to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributeMargins_Bottom" xml:space="preserve">
    <value>Bottom margin.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_ShadowColor" xml:space="preserve">
    <value>Legend item shadow color.</value>
  </data>
  <data name="DescriptionAttributePathRule_LegendText" xml:space="preserve">
    <value>Determines the text to be used when a legend item is automatically added to the legend.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_DistanceFromScale" xml:space="preserve">
    <value>The distance from the tip of the pointer to the scale. Measured as a percent.</value>
  </data>
  <data name="CategoryAttribute_ImageResources" xml:space="preserve">
    <value>Image Resources</value>
  </data>
  <data name="DescriptionAttributeGroup_SecondaryColor" xml:space="preserve">
    <value>Gets or sets the secondary color of the group used for gradients and hatches.</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_FontAngle" xml:space="preserve">
    <value>An additional fixed amount in degrees by which the position label will be rotated.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_GradientType" xml:space="preserve">
    <value>Legend item background gradient type.</value>
  </data>
  <data name="DescriptionAttributePathWidthRule_HatchStyleInLegend" xml:space="preserve">
    <value>Gets or sets the hatch style that will appear in the legend for this rule.</value>
  </data>
  <data name="DescriptionAttributePredefinedSymbol_Visible" xml:space="preserve">
    <value>Determines the visibility of the predefined symbol.</value>
  </data>
  <data name="DescriptionAttributePanelMargins_Bottom" xml:space="preserve">
    <value>The distance of the panel's visual bounds from its bottom edge in pixels.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_CellAttributes" xml:space="preserve">
    <value>Other attributes of the legend cell.</value>
  </data>
  <data name="DescriptionAttributePathRule_BorderColor" xml:space="preserve">
    <value>Gets or sets the border color to be used for the given range of values.</value>
  </data>
  <data name="DescriptionAttributePathRule_ShowInLegend" xml:space="preserve">
    <value>Specifies the legend for automatically adding legend items based on the path rule.</value>
  </data>
  <data name="DescriptionAttributePathRule_ColorCount" xml:space="preserve">
    <value>Gets or sets the number of colors that will be automatically generated by this path rule.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ViewStateContent" xml:space="preserve">
    <value>The view state to be persisted on the server.</value>
  </data>
  <data name="DescriptionAttributeViewCenter_X" xml:space="preserve">
    <value>The X value of the view center.</value>
  </data>
  <data name="DescriptionAttributeViewCenter_Y" xml:space="preserve">
    <value>The Y value of the view center.</value>
  </data>
  <data name="DescriptionAttributeCustomTickMark_Placement" xml:space="preserve">
    <value>Determines the position of the tick marks relative to the scale.</value>
  </data>
  <data name="DescriptionAttributePanel_BackColor" xml:space="preserve">
    <value>Gets or sets the color of the panel's background.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for the automatically generated data intervals.  Leave empty to determine this value automatically.</value>
  </data>
  <data name="DescriptionAttributeShape_ParentGroup" xml:space="preserve">
    <value>Determines the group to which this shape belongs.</value>
  </data>
  <data name="DescriptionAttributeGroup_ShadowOffset" xml:space="preserve">
    <value>Gets or sets how far to the right and how far down the shadow will be. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapControl_ControlPersistence" xml:space="preserve">
    <value>Determines if the control is persisted between callbacks in the session or application state.</value>
  </data>
  <data name="ExceptionXamlShapeNotSupported" xml:space="preserve">
    <value>The shape {0} is not supported.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_TextColor" xml:space="preserve">
    <value>The text color of the scale labels.</value>
  </data>
  <data name="DescriptionAttributeShapeRule_ShowInColorSwatch" xml:space="preserve">
    <value>Determines if the colors generated by this rule are to be added to the color swatch panel.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_TextColor" xml:space="preserve">
    <value>Legend cell text color. Set CellType to Text to use this property.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Color" xml:space="preserve">
    <value>Gets or sets the color of the symbol.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Layer" xml:space="preserve">
    <value>Determines the layer to which this symbol belongs.</value>
  </data>
  <data name="DescriptionAttributeDockablePanel_DockAlignment" xml:space="preserve">
    <value>Gets or sets the alignment of the docked panel.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Image" xml:space="preserve">
    <value>The image to be used for this symbol.</value>
  </data>
  <data name="UnsupportedDbfDeleted" xml:space="preserve">
    <value>Deleted records are not supported.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerGradientType" xml:space="preserve">
    <value>Gets or sets the gradient type of the marker.</value>
  </data>
  <data name="invalid_cast" xml:space="preserve">
    <value>There is no cast from {0} to {1}.</value>
  </data>
  <data name="DescriptionAttributeSymbol_Width" xml:space="preserve">
    <value>Gets or sets the symbol width in pixels.</value>
  </data>
  <data name="DescriptionAttributeMapLabel_Visible" xml:space="preserve">
    <value>Determines the visibility of the map label.</value>
  </data>
  <data name="UnsupportedDbfNumberOfFields0" xml:space="preserve">
    <value>Unsupported DBF file, number of fields must be greater then zero!</value>
  </data>
  <data name="DescriptionAttributeGroupRule_Text" xml:space="preserve">
    <value>Gets or sets the text to be displayed for all groups to which this rule applies.</value>
  </data>
  <data name="DescriptionAttributeGroupRule_Name" xml:space="preserve">
    <value>Gets or sets the name of the group rule.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_PathLineStyle" xml:space="preserve">
    <value>Legend item path line style.</value>
  </data>
  <data name="DescriptionAttributePath_TextColor" xml:space="preserve">
    <value>The text color of the path.</value>
  </data>
  <data name="DescriptionAttributeField_UniqueIdentifier" xml:space="preserve">
    <value>Determines if this field is to be treated as a unique identifier during data binding.</value>
  </data>
  <data name="AccessibilityDistanceScalePanelName" xml:space="preserve">
    <value>Distance scale panel</value>
  </data>
  <data name="DescriptionAttributeFrame_PageColor" xml:space="preserve">
    <value>Frame page color.</value>
  </data>
  <data name="DescriptionAttributeLinearPinLabel_DistanceFromScale" xml:space="preserve">
    <value>A value by which the labels will be offset from their normal position.</value>
  </data>
  <data name="DescriptionAttributeGroup_TextColor" xml:space="preserve">
    <value>Gets or sets the text color for the group.</value>
  </data>
  <data name="DescriptionAttributeMapControl_BackGradientType" xml:space="preserve">
    <value>The gradient type of the control's background.</value>
  </data>
  <data name="DescriptionAttributeGroup_CentralPointOffset" xml:space="preserve">
    <value>Gets or sets the offset of the group's central point.</value>
  </data>
  <data name="DescriptionAttributeMapControl_DimWhenNotFocused" xml:space="preserve">
    <value>Specifies whether the control content should be dimmed when the control loses the focus.</value>
  </data>
  <data name="DescriptionAttributeSymbolRule_DataGrouping" xml:space="preserve">
    <value>Determines the data grouping method to use when generating the data intervals.</value>
  </data>
  <data name="DescriptionAttributePath_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and how far down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributePath_ToolTip" xml:space="preserve">
    <value>The tooltip text to be displayed when the cursor is over the path.</value>
  </data>
  <data name="DescriptionAttributeLinearSpecialPosition_LabelStyle" xml:space="preserve">
    <value>The label attributes of this pin.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_MarkerHatchStyle" xml:space="preserve">
    <value>Gets or sets the hatch style of the marker.</value>
  </data>
  <data name="DescriptionAttributeLegendItem_SeparatorColor" xml:space="preserve">
    <value>Legend item visual separator color.</value>
  </data>
  <data name="DescriptionAttributeColorSwatchPanel_LabelColor" xml:space="preserve">
    <value>Determines the text color for the color swatch labels.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Alignment" xml:space="preserve">
    <value>Legend cell content alignment.</value>
  </data>
  <data name="AccessibilityGroupName" xml:space="preserve">
    <value>Group {0}</value>
  </data>
  <data name="DescriptionAttributePinMajorTickMark_Length" xml:space="preserve">
    <value>The length of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Font" xml:space="preserve">
    <value>Legend cell text font. Set CellType to Text to use this property.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Name" xml:space="preserve">
    <value>Specifies the name of this legend item cell.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Href" xml:space="preserve">
    <value>URL target of the legend cell.</value>
  </data>
  <data name="DescriptionAttributeLegendCell_Text" xml:space="preserve">
    <value>Legend cell text. Set CellType to Text to use this property.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackGradientType" xml:space="preserve">
    <value>Frame background gradient type.</value>
  </data>
  <data name="DescriptionAttributeShape_Selected" xml:space="preserve">
    <value>Determines if the shape visually appears selected.</value>
  </data>
  <data name="AccessibilityColorSwatchTitleNameRS" xml:space="preserve">
    <value>Color scale title</value>
  </data>
  <data name="DescriptionAttributeCustomWidth_FromValue" xml:space="preserve">
    <value>Gets or sets the start value for this width. Leave empty to determine the value automatically.</value>
  </data>
  <data name="DescriptionAttributeLinearLabelStyle_IntervalOffset" xml:space="preserve">
    <value>Interval offset of the labels. </value>
  </data>
  <data name="DescriptionAttributeFrame_BackColor" xml:space="preserve">
    <value>Frame background color.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_FillSecondaryColor" xml:space="preserve">
    <value>The end color of the pointer's fill gradient.</value>
  </data>
  <data name="DescriptionAttributeFrame_BackImage" xml:space="preserve">
    <value>Frame background image.</value>
  </data>
</root>