//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.ReportingServices.Rendering.ExcelRenderer.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelRenderRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelRenderRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.ReportingServices.Rendering.ExcelRenderer.ExcelRenderRes", typeof(ExcelRenderRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension : Argument is not valid..
        /// </summary>
        internal static string ArgumentInvalid {
            get {
                return ResourceManager.GetString("ArgumentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension : Argument is null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document map.
        /// </summary>
        internal static string DocumentMap {
            get {
                return ResourceManager.GetString("DocumentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 2003.
        /// </summary>
        internal static string ExcelLocalizedName {
            get {
                return ResourceManager.GetString("ExcelLocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string ExcelOoxmlLocalizedName {
            get {
                return ResourceManager.GetString("ExcelOoxmlLocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension : Index at {0} is not valid..
        /// </summary>
        internal static string InvalidIndexException {
            get {
                return ResourceManager.GetString("InvalidIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension: Number of columns exceeds the maximum possible in a worksheet of this version. Columns requested: {0}. Maximum columns: {1}..
        /// </summary>
        internal static string MaxColExceededInSheet {
            get {
                return ResourceManager.GetString("MaxColExceededInSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension: Number of rows exceeds the maximum possible in a worksheet of this version. Rows requested: {0}. Maximum rows: {1}..
        /// </summary>
        internal static string MaxRowExceededInSheet {
            get {
                return ResourceManager.GetString("MaxRowExceededInSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelRenderingExtension: Value of cell at row {0}, column {1} exceeds the maximum length for a string of 32767 characters..
        /// </summary>
        internal static string MaxStringLengthExceeded {
            get {
                return ResourceManager.GetString("MaxStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension : Maximum value of data type ({0}) exceeded..
        /// </summary>
        internal static string MaxValueExceeded {
            get {
                return ResourceManager.GetString("MaxValueExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string SheetNameCounterSuffix {
            get {
                return ResourceManager.GetString("SheetNameCounterSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension: Unknown image format {0}..
        /// </summary>
        internal static string UnknownImageFormat {
            get {
                return ResourceManager.GetString("UnknownImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Rendering Extension : Value {2} is out of range. Expected range is {0} - {1}..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
