//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Reporting.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Reporting.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string AsyncProgressText {
            get {
                return ResourceManager.GetString("AsyncProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the report is rendered asynchronously from the rest of the web page..
        /// </summary>
        internal static string AsyncRenderingDesc {
            get {
                return ResourceManager.GetString("AsyncRenderingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user navigates back to the parent report of a drillthrough report..
        /// </summary>
        internal static string BackEventDesc {
            get {
                return ResourceManager.GetString("BackEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user navigates to a bookmark in the report..
        /// </summary>
        internal static string BookmarkEventDesc {
            get {
                return ResourceManager.GetString("BookmarkEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLinkText {
            get {
                return ResourceManager.GetString("CancelLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during client rendering..
        /// </summary>
        internal static string ClientRenderingErrors {
            get {
                return ResourceManager.GetString("ClientRenderingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines which mime types are exported as attachments..
        /// </summary>
        internal static string ContentDispositionDesc {
            get {
                return ResourceManager.GetString("ContentDispositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceInfo &apos;{0}&apos; is for internal use.
        /// </summary>
        internal static string DeviceInfoInternal {
            get {
                return ResourceManager.GetString("DeviceInfoInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user-visible name of the report..
        /// </summary>
        internal static string DisplayNameDesc {
            get {
                return ResourceManager.GetString("DisplayNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether the document map is visible or collapsed..
        /// </summary>
        internal static string DocMapCollapsedDesc {
            get {
                return ResourceManager.GetString("DocMapCollapsedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user navigates to a document map entry in the report..
        /// </summary>
        internal static string DocMapEventDesc {
            get {
                return ResourceManager.GetString("DocMapEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the width of the document map..
        /// </summary>
        internal static string DocMapWidthDesc {
            get {
                return ResourceManager.GetString("DocMapWidthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the document map width will grow proportionally with the size of the ReportViewer control..
        /// </summary>
        internal static string DocMapWidthFixedDesc {
            get {
                return ResourceManager.GetString("DocMapWidthFixedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user performs a drillthrough to a new report..
        /// </summary>
        internal static string DrillthroughEventDesc {
            get {
                return ResourceManager.GetString("DrillthroughEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether a report that has external images can be rendered (for example, images referenced via a URL.).
        /// </summary>
        internal static string EnableExternalImagesDesc {
            get {
                return ResourceManager.GetString("EnableExternalImagesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether a report that contains hyperlink actions can be rendered..
        /// </summary>
        internal static string EnableHyperlinksDesc {
            get {
                return ResourceManager.GetString("EnableHyperlinksDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether telemetry for anonymous usage of the control is enabled..
        /// </summary>
        internal static string EnableTelemetryDesc {
            get {
                return ResourceManager.GetString("EnableTelemetryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when errors are encountered while rendering a report..
        /// </summary>
        internal static string ErrorEventDesc {
            get {
                return ResourceManager.GetString("ErrorEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ?.
        /// </summary>
        internal static string EstimateTotalPages {
            get {
                return ResourceManager.GetString("EstimateTotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user exports the report..
        /// </summary>
        internal static string ExportEventDesc {
            get {
                return ResourceManager.GetString("ExportEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &apos;{0}&apos; contains external images. The EnableExternalImages property has not been set for this report..
        /// </summary>
        internal static string ExternalImagesError {
            get {
                return ResourceManager.GetString("ExternalImagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Document Map.
        /// </summary>
        internal static string HideDocMapTooltip {
            get {
                return ResourceManager.GetString("HideDocMapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Parameters.
        /// </summary>
        internal static string HideParametersTooltip {
            get {
                return ResourceManager.GetString("HideParametersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight background color..
        /// </summary>
        internal static string HighlightBackgroundColorDesc {
            get {
                return ResourceManager.GetString("HighlightBackgroundColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of a report history snapshot for the specified report..
        /// </summary>
        internal static string HistoryIdDesc {
            get {
                return ResourceManager.GetString("HistoryIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user clicks a hyperlink in the report..
        /// </summary>
        internal static string HyperlinkEventDesc {
            get {
                return ResourceManager.GetString("HyperlinkEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &apos;{0}&apos; contains hyperlinks. The EnableHyperlinks property has not been set for this report.
        /// </summary>
        internal static string HyperlinkSecurityError {
            get {
                return ResourceManager.GetString("HyperlinkSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target window of the hyperlinks in the report..
        /// </summary>
        internal static string HyperlinkTargetDesc {
            get {
                return ResourceManager.GetString("HyperlinkTargetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether synchronous or asynchronous postbacks are used for report interactivity..
        /// </summary>
        internal static string InteractivityPostBackModeDesc {
            get {
                return ResourceManager.GetString("InteractivityPostBackModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true, the report viewer will keep the report session alive as long as the report viewer is running..
        /// </summary>
        internal static string KeepSessionAliveDesc {
            get {
                return ResourceManager.GetString("KeepSessionAliveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeepSessionAlive cannot be turned on because a report session already exists..
        /// </summary>
        internal static string KeepSessionAliveException {
            get {
                return ResourceManager.GetString("KeepSessionAliveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local report processing requires FullTrust Code Access Security permissions, which is unavailable to the calling code.  Grant the application FullTrust permissions or use ServerReport to execute the report remotely..
        /// </summary>
        internal static string LocalModeMissingFullTrustErrors {
            get {
                return ResourceManager.GetString("LocalModeMissingFullTrustErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during local report processing..
        /// </summary>
        internal static string LocalProcessingErrors {
            get {
                return ResourceManager.GetString("LocalProcessingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local processing properties..
        /// </summary>
        internal static string LocalReportDesc {
            get {
                return ResourceManager.GetString("LocalReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system path to the report definition file..
        /// </summary>
        internal static string LocalReportPathDesc {
            get {
                return ResourceManager.GetString("LocalReportPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the application identifier (AppID) to use for Bing Maps Web Services..
        /// </summary>
        internal static string MapTileServerConfigurationAppIDDesc {
            get {
                return ResourceManager.GetString("MapTileServerConfigurationAppIDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines configuration settings for Microsoft Bing Maps Web Services that provides a tile background for map report items..
        /// </summary>
        internal static string MapTileServerConfigurationDesc {
            get {
                return ResourceManager.GetString("MapTileServerConfigurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the maximum number of connections to Bing Maps Web Services..
        /// </summary>
        internal static string MapTileServerConfigurationMaxConnectionsDesc {
            get {
                return ResourceManager.GetString("MapTileServerConfigurationMaxConnectionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the timeout in seconds to wait for a response from Bing Maps Web Services..
        /// </summary>
        internal static string MapTileServerConfigurationTimeoutDesc {
            get {
                return ResourceManager.GetString("MapTileServerConfigurationTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source instance has not been supplied for the data source &apos;{0}&apos;..
        /// </summary>
        internal static string MissingDataSource {
            get {
                return ResourceManager.GetString("MissingDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more data sources is missing credentials.
        /// </summary>
        internal static string MissingDataSourceCredentials {
            get {
                return ResourceManager.GetString("MissingDataSourceCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is missing a value.
        /// </summary>
        internal static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReportServerUrl property is not set to a report server URL..
        /// </summary>
        internal static string MissingReportServerUrl {
            get {
                return ResourceManager.GetString("MissingReportServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source of the report definition has not been specified.
        /// </summary>
        internal static string MissingReportSource {
            get {
                return ResourceManager.GetString("MissingReportSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-CLSCompliant exception..
        /// </summary>
        internal static string NonClsCompliantException {
            get {
                return ResourceManager.GetString("NonClsCompliantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation can only be performed from a drillthrough report.
        /// </summary>
        internal static string NotInDrillthrough {
            get {
                return ResourceManager.GetString("NotInDrillthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether the actual number of pages are calculated when rendering the report..
        /// </summary>
        internal static string PageCountModeDesc {
            get {
                return ResourceManager.GetString("PageCountModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user changes the displayed page of the report..
        /// </summary>
        internal static string PageNavigationEventDesc {
            get {
                return ResourceManager.GetString("PageNavigationEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when user changes the margins or bounds in the page settings dialog..
        /// </summary>
        internal static string PageSettingsChangedEventDesc {
            get {
                return ResourceManager.GetString("PageSettingsChangedEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; does not exist on this report.
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; was specified multiple times.
        /// </summary>
        internal static string ParameterSpecifiedMultipleTimes {
            get {
                return ResourceManager.GetString("ParameterSpecifiedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load policy file: {0}.
        /// </summary>
        internal static string PolicyFileLoadFailed {
            get {
                return ResourceManager.GetString("PolicyFileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color used for the primary buttons in dialogs ie. &apos;ok&apos;..
        /// </summary>
        internal static string PrimaryButtonBackgroundColor {
            get {
                return ResourceManager.GetString("PrimaryButtonBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color used for the primary buttons in dialogs..
        /// </summary>
        internal static string PrimaryButtonForegroundColor {
            get {
                return ResourceManager.GetString("PrimaryButtonForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color used for the primary buttons in dialogs when hovering..
        /// </summary>
        internal static string PrimaryButtonHoverBackgroundColor {
            get {
                return ResourceManager.GetString("PrimaryButtonHoverBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color used for the primary buttons in dialogs when hovering..
        /// </summary>
        internal static string PrimaryButtonHoverForegroundColor {
            get {
                return ResourceManager.GetString("PrimaryButtonHoverForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user prints the report..
        /// </summary>
        internal static string PrintEventDesc {
            get {
                return ResourceManager.GetString("PrintEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs after &apos;OK&apos; is pressed in the print dialog..
        /// </summary>
        internal static string PrintingBegingEventDesc {
            get {
                return ResourceManager.GetString("PrintingBegingEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether report processing occurs locally or on a report server..
        /// </summary>
        internal static string ProcessingModeDesc {
            get {
                return ResourceManager.GetString("ProcessingModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether the prompt area is visible or collapsed..
        /// </summary>
        internal static string PromptAreaCollapsedDesc {
            get {
                return ResourceManager.GetString("PromptAreaCollapsedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user refreshes the report..
        /// </summary>
        internal static string RefreshEventDesc {
            get {
                return ResourceManager.GetString("RefreshEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before rendering of the report is begins..
        /// </summary>
        internal static string RenderBeginEventDesc {
            get {
                return ResourceManager.GetString("RenderBeginEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the rendering of the report in completed..
        /// </summary>
        internal static string RenderCompleteEventDesc {
            get {
                return ResourceManager.GetString("RenderCompleteEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source instance associated with each report data source..
        /// </summary>
        internal static string ReportDataSourcesDesc {
            get {
                return ResourceManager.GetString("ReportDataSourcesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of embedded resource containing the report definition. If ReportPath is set this property is ignored..
        /// </summary>
        internal static string ReportEmbeddedResourceDesc {
            get {
                return ResourceManager.GetString("ReportEmbeddedResourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameters or credentials have not been specified.
        /// </summary>
        internal static string ReportNotReady {
            get {
                return ResourceManager.GetString("ReportNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is not ready to render: Unknown reason..
        /// </summary>
        internal static string ReportNotReadyException {
            get {
                return ResourceManager.GetString("ReportNotReadyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the report server. .
        /// </summary>
        internal static string ReportServerUrlDesc {
            get {
                return ResourceManager.GetString("ReportServerUrlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a report.
        /// </summary>
        internal static string ReportViewerDescription {
            get {
                return ResourceManager.GetString("ReportViewerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user searches for text in the report..
        /// </summary>
        internal static string SearchEventDesc {
            get {
                return ResourceManager.GetString("SearchEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color used for the secondary buttons in dialogs..
        /// </summary>
        internal static string SecondaryButtonBackgroundColor {
            get {
                return ResourceManager.GetString("SecondaryButtonBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color used for the secondary buttons in dialogs..
        /// </summary>
        internal static string SecondaryButtonForegroundColor {
            get {
                return ResourceManager.GetString("SecondaryButtonForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color used for the secondary buttons in dialogs when hovering..
        /// </summary>
        internal static string SecondaryButtonHoverBackgroundColor {
            get {
                return ResourceManager.GetString("SecondaryButtonHoverBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color used for the secondary buttons in dialogs when hovering..
        /// </summary>
        internal static string SecondaryButtonHoverForegroundColor {
            get {
                return ResourceManager.GetString("SecondaryButtonHoverForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote processing properties..
        /// </summary>
        internal static string ServerReportDesc {
            get {
                return ResourceManager.GetString("ServerReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to report on the Report Server..
        /// </summary>
        internal static string ServerReportPathDesc {
            get {
                return ResourceManager.GetString("ServerReportPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of milliseconds to wait for a connection before terminating the attempt.  Specify -1 for no time out..
        /// </summary>
        internal static string ServerTimeoutDesc {
            get {
                return ResourceManager.GetString("ServerTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the back button on the tool bar..
        /// </summary>
        internal static string ShowBackButtonDesc {
            get {
                return ResourceManager.GetString("ShowBackButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the report context menu..
        /// </summary>
        internal static string ShowContextMenuDesc {
            get {
                return ResourceManager.GetString("ShowContextMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether credential prompts should be displayed during remote processing..
        /// </summary>
        internal static string ShowCredentialPromptsDesc {
            get {
                return ResourceManager.GetString("ShowCredentialPromptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true and an error occurs with a subreport, a detailed error message will be embedded into the report..
        /// </summary>
        internal static string ShowDetailedSubreportMessagesDesc {
            get {
                return ResourceManager.GetString("ShowDetailedSubreportMessagesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Document Map.
        /// </summary>
        internal static string ShowDocMapTooltip {
            get {
                return ResourceManager.GetString("ShowDocMapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the document map button on the tool bar..
        /// </summary>
        internal static string ShowDocumentMapButtonDesc {
            get {
                return ResourceManager.GetString("ShowDocumentMapButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the export button on the tool bar..
        /// </summary>
        internal static string ShowExportButtonDesc {
            get {
                return ResourceManager.GetString("ShowExportButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the find controls on the tool bar..
        /// </summary>
        internal static string ShowFindButtonDesc {
            get {
                return ResourceManager.GetString("ShowFindButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the page navigation controls on the tool bar..
        /// </summary>
        internal static string ShowPageNavigationDesc {
            get {
                return ResourceManager.GetString("ShowPageNavigationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether parameter prompts should be displayed during remote processing..
        /// </summary>
        internal static string ShowParameterPromptsDesc {
            get {
                return ResourceManager.GetString("ShowParameterPromptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Parameters.
        /// </summary>
        internal static string ShowParametersTooltip {
            get {
                return ResourceManager.GetString("ShowParametersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the print, print layout, and page setup buttons on the tool bar..
        /// </summary>
        internal static string ShowPrintButtonDesc {
            get {
                return ResourceManager.GetString("ShowPrintButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether a progress animation is visible while waiting for the report..
        /// </summary>
        internal static string ShowProgressDesc {
            get {
                return ResourceManager.GetString("ShowProgressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the prompt area splitter button above the tool bar..
        /// </summary>
        internal static string ShowPromptAreaButtonDesc {
            get {
                return ResourceManager.GetString("ShowPromptAreaButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the refresh button on the tool bar..
        /// </summary>
        internal static string ShowRefreshButtonDesc {
            get {
                return ResourceManager.GetString("ShowRefreshButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the report content is rendered..
        /// </summary>
        internal static string ShowReportBodyDesc {
            get {
                return ResourceManager.GetString("ShowReportBodyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the stop button on the tool bar..
        /// </summary>
        internal static string ShowStopButtonDesc {
            get {
                return ResourceManager.GetString("ShowStopButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the tool bar..
        /// </summary>
        internal static string ShowToolBarDesc {
            get {
                return ResourceManager.GetString("ShowToolBarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether the cancel link is displayed on the busy status indicator..
        /// </summary>
        internal static string ShowWaitControlCancelLinkDesc {
            get {
                return ResourceManager.GetString("ShowWaitControlCancelLinkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the visibility of the zoom button on the tool bar..
        /// </summary>
        internal static string ShowZoomButtonDesc {
            get {
                return ResourceManager.GetString("ShowZoomButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the report area has a fixed size or is the size of the report content..
        /// </summary>
        internal static string SizeToContentDesc {
            get {
                return ResourceManager.GetString("SizeToContentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user performs a sort on the report..
        /// </summary>
        internal static string SortEventDesc {
            get {
                return ResourceManager.GetString("SortEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the display state of the report viewer changes..
        /// </summary>
        internal static string StateChangedEventDesc {
            get {
                return ResourceManager.GetString("StateChangedEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user submits data source credentials via the built-in prompt area..
        /// </summary>
        internal static string SubmittingDataSourceCredentialsEventDesc {
            get {
                return ResourceManager.GetString("SubmittingDataSourceCredentialsEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user submits parameter values from the built-in prompt area..
        /// </summary>
        internal static string SubmittingParameterValuesEventDesc {
            get {
                return ResourceManager.GetString("SubmittingParameterValuesEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a subreport is being processed..
        /// </summary>
        internal static string SubreportProcessingEventDesc {
            get {
                return ResourceManager.GetString("SubreportProcessingEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user toggles an item in the report..
        /// </summary>
        internal static string ToggleEventDesc {
            get {
                return ResourceManager.GetString("ToggleEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Bar.
        /// </summary>
        internal static string ToolBarCategoryDesc {
            get {
                return ResourceManager.GetString("ToolBarCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color used for icon borders, and to separate regions of the Report Viewer Control..
        /// </summary>
        internal static string ToolbarDividerColorDesc {
            get {
                return ResourceManager.GetString("ToolbarDividerColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of icons and text within the toolbar..
        /// </summary>
        internal static string ToolbarForegroundColor {
            get {
                return ResourceManager.GetString("ToolbarForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of disabled content in the toolbar area..
        /// </summary>
        internal static string ToolbarForegroundDisabledColorDesc {
            get {
                return ResourceManager.GetString("ToolbarForegroundDisabledColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color of toolbar icons when hovered or selected..
        /// </summary>
        internal static string ToolbarHoverBackColorDesc {
            get {
                return ResourceManager.GetString("ToolbarHoverBackColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of icons and text when a toolbar icons is being hovered over..
        /// </summary>
        internal static string ToolbarHoverForegroundColorDesc {
            get {
                return ResourceManager.GetString("ToolbarHoverForegroundColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote report processing requires Microsoft SQL Server 2008 Reporting Services or later..
        /// </summary>
        internal static string UnsupportedReportServerError {
            get {
                return ResourceManager.GetString("UnsupportedReportServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user clicks the view report button..
        /// </summary>
        internal static string ViewReportEventDesc {
            get {
                return ResourceManager.GetString("ViewReportEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay in milliseconds before the busy status indicator is displayed to the user..
        /// </summary>
        internal static string WaitControlDisplayAfterDesc {
            get {
                return ResourceManager.GetString("WaitControlDisplayAfterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user changes the zoom setting for the report..
        /// </summary>
        internal static string ZoomEventDesc {
            get {
                return ResourceManager.GetString("ZoomEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the type of zoom applied to the report..
        /// </summary>
        internal static string ZoomModeDesc {
            get {
                return ResourceManager.GetString("ZoomModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the percentage of zoom applied to the report when ZoomMode is set to Percent..
        /// </summary>
        internal static string ZoomPercentDesc {
            get {
                return ResourceManager.GetString("ZoomPercentDesc", resourceCulture);
            }
        }
    }
}
