//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Reporting.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcessingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Reporting.ProcessingStrings", typeof(ProcessingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report execution in the current AppDomain requires Code Access Security policy, which is off by default in .NET 4.0 and later.  Enable legacy CAS policy or execute the report in the sandbox AppDomain..
        /// </summary>
        internal static string CasPolicyUnavailableForCurrentAppDomain {
            get {
                return ResourceManager.GetString("CasPolicyUnavailableForCurrentAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set Processing Extension.
        /// </summary>
        internal static string DataSetExtensionName {
            get {
                return ResourceManager.GetString("DataSetExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Report.
        /// </summary>
        internal static string MainReport {
            get {
                return ResourceManager.GetString("MainReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are {0} to {1}..
        /// </summary>
        internal static string MapTileServerConfiguration_MaxConnectionsOutOfRange {
            get {
                return ResourceManager.GetString("MapTileServerConfiguration_MaxConnectionsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are {0} to {1}..
        /// </summary>
        internal static string MapTileServerConfiguration_TimeoutOutOfRange {
            get {
                return ResourceManager.GetString("MapTileServerConfiguration_TimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source instance has not been supplied for the data source &quot;{0}&quot;..
        /// </summary>
        internal static string MissingDataReader {
            get {
                return ResourceManager.GetString("MissingDataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report definition for report &apos;{0}&apos; has not been specified.
        /// </summary>
        internal static string MissingDefinition {
            get {
                return ResourceManager.GetString("MissingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition of the report &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string pvInvalidDefinition {
            get {
                return ResourceManager.GetString("pvInvalidDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RdlCompile: Could not open file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string RdlCompile_CouldNotOpenFile {
            get {
                return ResourceManager.GetString("RdlCompile_CouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RdlCompile: Could not write state file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string RdlCompile_CouldNotWriteStateFile {
            get {
                return ResourceManager.GetString("RdlCompile_CouldNotWriteStateFile", resourceCulture);
            }
        }
    }
}
