//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.ReportingServices.OnDemandReportRendering.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RenderErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RenderErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.ReportingServices.OnDemandReportRendering.RenderErrors", typeof(RenderErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML tag of a control cannot be null or the empty string..
        /// </summary>
        internal static string rrControlInvalidTag {
            get {
                return ResourceManager.GetString("rrControlInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing tag for the element &apos;{0}&apos; was expected. The device information is invalid..
        /// </summary>
        internal static string rrExpectedEndElement {
            get {
                return ResourceManager.GetString("rrExpectedEndElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top level element in the device information XML structure has to be &apos;{0}&apos;..
        /// </summary>
        internal static string rrExpectedTopLevelElement {
            get {
                return ResourceManager.GetString("rrExpectedTopLevelElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action label is only optional when using a single action. Adding multiple actions requires labels for each action..
        /// </summary>
        internal static string rrInvalidActionLabel {
            get {
                return ResourceManager.GetString("rrInvalidActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of an HTML attribute cannot be null or the empty string..
        /// </summary>
        internal static string rrInvalidAttribute {
            get {
                return ResourceManager.GetString("rrInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border style &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrInvalidBorderStyle {
            get {
                return ResourceManager.GetString("rrInvalidBorderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrInvalidColor {
            get {
                return ResourceManager.GetString("rrInvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null control cannot be added to a list..
        /// </summary>
        internal static string rrInvalidControl {
            get {
                return ResourceManager.GetString("rrInvalidControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred trying to parse the device information XML structure. Details: {0}.
        /// </summary>
        internal static string rrInvalidDeviceInfo {
            get {
                return ResourceManager.GetString("rrInvalidDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The measurement unit of &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrInvalidMeasurementUnit {
            get {
                return ResourceManager.GetString("rrInvalidMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image mime type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrInvalidMimeType {
            get {
                return ResourceManager.GetString("rrInvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on ActiveXControls and Script in your Internet Explorer browser..
        /// </summary>
        internal static string rrInvalidOWCRequest {
            get {
                return ResourceManager.GetString("rrInvalidOWCRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number has to be an integer between 1 and {0}..
        /// </summary>
        internal static string rrInvalidPageNumber {
            get {
                return ResourceManager.GetString("rrInvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string rrInvalidParamValue {
            get {
                return ResourceManager.GetString("rrInvalidParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of an inline CSS style property cannot be null or the empty string..
        /// </summary>
        internal static string rrInvalidProperty {
            get {
                return ResourceManager.GetString("rrInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrInvalidSize {
            get {
                return ResourceManager.GetString("rrInvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style argument has to be of type &apos;{0}&apos;..
        /// </summary>
        internal static string rrInvalidStyleArgumentType {
            get {
                return ResourceManager.GetString("rrInvalidStyleArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a CSS style cannot be null or the empty string..
        /// </summary>
        internal static string rrInvalidStyleName {
            get {
                return ResourceManager.GetString("rrInvalidStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified unique name contains invalid characters. Only a-z, A-Z and 0-9 are allowed..
        /// </summary>
        internal static string rrInvalidUniqueName {
            get {
                return ResourceManager.GetString("rrInvalidUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement unit unsupported..
        /// </summary>
        internal static string rrMeasurementUnitError {
            get {
                return ResourceManager.GetString("rrMeasurementUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The negative size &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string rrNegativeSize {
            get {
                return ResourceManager.GetString("rrNegativeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string rrOutOfRange {
            get {
                return ResourceManager.GetString("rrOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a namespace cannot be null or the empty string..
        /// </summary>
        internal static string rrPageNamespaceInvalid {
            get {
                return ResourceManager.GetString("rrPageNamespaceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opening tag for a parameter was expected. The device information is invalid..
        /// </summary>
        internal static string rrParameterExpected {
            get {
                return ResourceManager.GetString("rrParameterExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Rendering:  Invalid Argument:  Device Info is null..
        /// </summary>
        internal static string rrRenderDeviceNull {
            get {
                return ResourceManager.GetString("rrRenderDeviceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report viewer cannot be displayed if the renderer parameters have not been specified..
        /// </summary>
        internal static string rrRendererParamsNull {
            get {
                return ResourceManager.GetString("rrRendererParamsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during rendering of the report..
        /// </summary>
        internal static string rrRenderingError {
            get {
                return ResourceManager.GetString("rrRenderingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Rendering:  Invalid Argument:  Report Name is null or empty..
        /// </summary>
        internal static string rrRenderReportNameNull {
            get {
                return ResourceManager.GetString("rrRenderReportNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Rendering:  Invalid Argument:  Report is null..
        /// </summary>
        internal static string rrRenderReportNull {
            get {
                return ResourceManager.GetString("rrRenderReportNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Renderer: Invalid Argument: Render Result is null..
        /// </summary>
        internal static string rrRenderResultNull {
            get {
                return ResourceManager.GetString("rrRenderResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rendering section instance..
        /// </summary>
        internal static string rrRenderSectionInstanceError {
            get {
                return ResourceManager.GetString("rrRenderSectionInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Rendering:  Invalid Argument:  Result Stream is null..
        /// </summary>
        internal static string rrRenderStreamNull {
            get {
                return ResourceManager.GetString("rrRenderStreamNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rendering the styles..
        /// </summary>
        internal static string rrRenderStyleError {
            get {
                return ResourceManager.GetString("rrRenderStyleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style missing style name..
        /// </summary>
        internal static string rrRenderStyleName {
            get {
                return ResourceManager.GetString("rrRenderStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t convert TextBox value to string..
        /// </summary>
        internal static string rrRenderTextBox {
            get {
                return ResourceManager.GetString("rrRenderTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Report Item Type in Renderer..
        /// </summary>
        internal static string rrRenderUnknownReportItem {
            get {
                return ResourceManager.GetString("rrRenderUnknownReportItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report viewer cannot be displayed if the report name has not been specified..
        /// </summary>
        internal static string rrReportNameNull {
            get {
                return ResourceManager.GetString("rrReportNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report viewer cannot be displayed if the report parameters have not been specified..
        /// </summary>
        internal static string rrReportParamsNull {
            get {
                return ResourceManager.GetString("rrReportParamsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred in Report Rendering..
        /// </summary>
        internal static string rrUnexpectedError {
            get {
                return ResourceManager.GetString("rrUnexpectedError", resourceCulture);
            }
        }
    }
}
