namespace AspNetCore.Reporting.Gauge.WebForms
{
	internal enum BackFrameShape
	{
		Circular,
		Rectangular,
		RoundedRectangular,
		AutoShape,
		CustomCircular1 = 1001,
		CustomCircular2,
		CustomCircular3,
		CustomCircular4,
		CustomCircular5,
		CustomCircular6,
		CustomCircular7,
		CustomCircular8,
		CustomCircular9,
		CustomCircular10,
		CustomCircular11,
		CustomCircular12,
		CustomCircular13,
		CustomCircular14,
		CustomCircular15,
		CustomSemiCircularN1 = 2001,
		CustomSemiCircularN2,
		CustomSemiCircularN3,
		CustomSemiCircularN4,
		CustomSemiCircularS1 = 2101,
		CustomSemiCircularS2,
		CustomSemiCircularS3,
		CustomSemiCircularS4,
		CustomSemiCircularE1 = 2201,
		CustomSemiCircularE2,
		CustomSemiCircularE3,
		CustomSemiCircularE4,
		CustomSemiCircularW1 = 2301,
		CustomSemiCircularW2,
		CustomSemiCircularW3,
		CustomSemiCircularW4,
		CustomQuarterCircularNE1 = 3001,
		CustomQuarterCircularNE2,
		CustomQuarterCircularNE3,
		CustomQuarterCircularNE4,
		CustomQuarterCircularNW1 = 3101,
		CustomQuarterCircularNW2,
		CustomQuarterCircularNW3,
		CustomQuarterCircularNW4,
		CustomQuarterCircularSE1 = 3201,
		CustomQuarterCircularSE2,
		CustomQuarterCircularSE3,
		CustomQuarterCircularSE4,
		CustomQuarterCircularSW1 = 3301,
		CustomQuarterCircularSW2,
		CustomQuarterCircularSW3,
		CustomQuarterCircularSW4
	}
}
