<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="DescriptionAttributeNumericRange_DecimalColor" xml:space="preserve">
    <value>The color of the decimal digits when the indicator's value is in range.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapImageTransColor" xml:space="preserve">
    <value>The transparent color of the pointer cap image.</value>
  </data>
  <data name="DescriptionAttributeKnob_ValueSource" xml:space="preserve">
    <value>Specifies the name of an input value or a calculated value.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerRangeTimeout" xml:space="preserve">
    <value>Occurs when a pointer stays in a range longer than the period set by the Range.InRangeTimeout property.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BackShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the back shadow will be.</value>
  </data>
  <data name="LabelFormatPrecisionMsg" xml:space="preserve">
    <value>Precision can be empty or in range from 0 to 99</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BorderStyle" xml:space="preserve">
    <value>The line style of the frame's border.</value>
  </data>
  <data name="DescriptionAttributeFillGradientType6" xml:space="preserve">
    <value>The primary fill gradient type of the pointer.</value>
  </data>
  <data name="DescriptionAttributeFillGradientType5" xml:space="preserve">
    <value>The fill gradient type of the range.</value>
  </data>
  <data name="DescriptionAttributeFillGradientType3" xml:space="preserve">
    <value>The fill gradient type of the scale's bar.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BorderWidth" xml:space="preserve">
    <value>The line width of the frame's border.</value>
  </data>
  <data name="ExceptionEmptyNameFailed" xml:space="preserve">
    <value>The name of this {0} element cannot be empty.</value>
  </data>
  <data name="DescriptionAttributePeriod" xml:space="preserve">
    <value>Period value. Represents period for calculations in units of duration type.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_ZOrder" xml:space="preserve">
    <value>Determines the Z order of the gauge label in the gauge container.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BorderColor" xml:space="preserve">
    <value>The color of the frame's border.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_ValueLimitOverflow" xml:space="preserve">
    <value>Occurs when the limit of some value is reached.</value>
  </data>
  <data name="DescriptionAttributeState_BorderStyle" xml:space="preserve">
    <value>The line style of the indicator's border when this state is activated.</value>
  </data>
  <data name="DescriptionAttributeState_BorderWidth" xml:space="preserve">
    <value>The width of the indicator's border when this state is activated. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeCustomLabels" xml:space="preserve">
    <value>Represents the scale's collection of custom labels.</value>
  </data>
  <data name="ExceptionColumnNotFound" xml:space="preserve">
    <value>A column with the name "{0}" was not found.</value>
  </data>
  <data name="DescriptionAttributeState_BorderColor" xml:space="preserve">
    <value>The color of the indicator's border when this state is activated.</value>
  </data>
  <data name="TraceFrameRenderingComplete" xml:space="preserve">
    <value>Frame rendering complete.</value>
  </data>
  <data name="DescriptionAttributeFontAngle3" xml:space="preserve">
    <value>An additional fixed amount in degrees by which labels will be rotated.</value>
  </data>
  <data name="ExceptionSerializerInvalidClassName" xml:space="preserve">
    <value>Invalid format of the serializable content string. Class name not set.</value>
  </data>
  <data name="DescriptionAttributeImage5" xml:space="preserve">
    <value>The image to be used as a custom tick mark.</value>
  </data>
  <data name="DescriptionAttributeImage7" xml:space="preserve">
    <value>The image to be used as a pointer.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Maximum" xml:space="preserve">
    <value>A number that represents the maximum (end) value of the indicator range.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BackGradientType" xml:space="preserve">
    <value>The gradient type of the back.</value>
  </data>
  <data name="DescriptionAttributeKnob_RotateGradient" xml:space="preserve">
    <value>Determines if the gradient of the knob should rotate or remain static.</value>
  </data>
  <data name="DescriptionAttributeInRangeTimeout" xml:space="preserve">
    <value>Determines the time a pointer needs to stay in the range before triggering the PointerRangeTimeout event.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BorderStyle" xml:space="preserve">
    <value>The line style of the gauge label border.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BorderWidth" xml:space="preserve">
    <value>The line width of the gauge label's border.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_MajorTickMark" xml:space="preserve">
    <value>The major tick mark attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeCircularRange_StartWidth" xml:space="preserve">
    <value>The start width of the range. Measured as a percent of the radius of the scale that owns the range.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BorderColor" xml:space="preserve">
    <value>The color of the gauge label border.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_SelectionBorderColor" xml:space="preserve">
    <value>Determines the border color of the selection.</value>
  </data>
  <data name="DescriptionAttributeImageTransColor6" xml:space="preserve">
    <value>The transparent color of the state image.</value>
  </data>
  <data name="DescriptionAttributeImageTransColor5" xml:space="preserve">
    <value>The transparent color of the pointer image.</value>
  </data>
  <data name="DescriptionAttributeImageTransColor4" xml:space="preserve">
    <value>The transparent color of the tick mark image.</value>
  </data>
  <data name="ExceptionOutOfRangeMinOpen" xml:space="preserve">
    <value>The argument must be greater than {0}.</value>
  </data>
  <data name="CategoryGaugeBehavior" xml:space="preserve">
    <value>Gauge Behavior</value>
  </data>
  <data name="ExceptionListOutOfRange" xml:space="preserve">
    <value>List index is out of range</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BackHatchStyle" xml:space="preserve">
    <value>The pattern style of the gauge label's background.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_LedDimColor" xml:space="preserve">
    <value>The color of the digit's background.</value>
  </data>
  <data name="DescriptionAttributeTopImageHueColor" xml:space="preserve">
    <value>The hue color to be applied to the top image.</value>
  </data>
  <data name="DescriptionAttributeLength" xml:space="preserve">
    <value>The length of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeLogarithmic" xml:space="preserve">
    <value>Determines if the scale is logarithmic.</value>
  </data>
  <data name="DescriptionAttributeLogarithmicBase" xml:space="preserve">
    <value>Determines the base for logarithmic scales.</value>
  </data>
  <data name="AccessibilityGaugeControlName" xml:space="preserve">
    <value>Gauge</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_BackFrame" xml:space="preserve">
    <value>The frame attributes of the gauge container.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_Radius" xml:space="preserve">
    <value>Determines the radius of the scale. The coordinates are in percent of the Gauge's width or height, whichever is smaller</value>
  </data>
  <data name="ExceptionOutOfrange" xml:space="preserve">
    <value>The argument is out of range ({0},{1}).</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Location" xml:space="preserve">
    <value>The location of the gauge label inside the gauge container. The coordinates are measured as a percentage of the container's width and height.</value>
  </data>
  <data name="DescriptionAttributeMapArea_MapArea" xml:space="preserve">
    <value>Represent a custom map area element, that has a user-defined shape and dimensions.</value>
  </data>
  <data name="DescriptionAttributeEnable" xml:space="preserve">
    <value>Determines whether the position is enabled.</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_IgnoreUnknownXmlAttributes" xml:space="preserve">
    <value>Indicates that unknown XML attributes and elements will be ignored without throwing an exception.</value>
  </data>
  <data name="DescriptionAttributeState_EndValue" xml:space="preserve">
    <value>The start and end values determine when the state is activated.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapReflection" xml:space="preserve">
    <value>Determines if the pointer cap has a reflection effect.</value>
  </data>
  <data name="DescriptionAttributeTextColor" xml:space="preserve">
    <value>The text color of the position.</value>
  </data>
  <data name="CategoryTypeSpecific" xml:space="preserve">
    <value>Type Specific</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_TemplateMode" xml:space="preserve">
    <value>Determines if the serializer works in template creation mode.</value>
  </data>
  <data name="DescriptionAttributeInputValue_HistoryDepthType" xml:space="preserve">
    <value>History depth type in DurationType. Represents type of history depth units.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueIntegral_IntegralIntervalType" xml:space="preserve">
    <value>Gets or sets the integral interval period type.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Angle" xml:space="preserve">
    <value>Determines the angle (in degrees) by which this image is rotated.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Image" xml:space="preserve">
    <value>The image to be displayed for the gauge image's default state.</value>
  </data>
  <data name="DescriptionAttributeHref10" xml:space="preserve">
    <value>The Href of the object.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_Callback" xml:space="preserve">
    <value>Fires during a user callback.</value>
  </data>
  <data name="ExceptionPlaybackCount" xml:space="preserve">
    <value>The length of the history is less than {0} records.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_GaugeContainer" xml:space="preserve">
    <value>Gauge for ASP.NET provides the ability to implement a variety of rich interactive gauges and dashboards.</value>
  </data>
  <data name="CategoryGaugeContainer" xml:space="preserve">
    <value>Gauge Container</value>
  </data>
  <data name="DescriptionAttributeValueSource" xml:space="preserve">
    <value>Specifies the name of an input or calculated value.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_RenderType" xml:space="preserve">
    <value>Determines if the gauge should be rendered as an image tag, input tag, binary data stream or image map.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerFillGradientType" xml:space="preserve">
    <value>The fill gradient type of the knob cap.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerPositionChange" xml:space="preserve">
    <value>Occurs when a pointer's value is changed interactively. The new value can be validated.</value>
  </data>
  <data name="DescriptionAttributeKnob_SnappingEnabled" xml:space="preserve">
    <value>Determines if snapping of the knob's value to a given interval is enabled.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_FillColor" xml:space="preserve">
    <value>The fill color of the indicator's border when the indicator is in its default state.</value>
  </data>
  <data name="DescriptionAttributeImageHueColor4" xml:space="preserve">
    <value>The hue color to be applied to the state image.</value>
  </data>
  <data name="DescriptionAttributeImageHueColor6" xml:space="preserve">
    <value>The hue color to be applied to the tick mark image.</value>
  </data>
  <data name="CategoryPointer" xml:space="preserve">
    <value>Pointer</value>
  </data>
  <data name="DescriptionAttributeSnappingEnabled4" xml:space="preserve">
    <value>Determines if snapping of the pointer's value to a given interval is enabled.</value>
  </data>
  <data name="DescriptionAttributeMapAreaAttributes4" xml:space="preserve">
    <value>Other attributes of the map area.</value>
  </data>
  <data name="DescriptionAttributeCursor" xml:space="preserve">
    <value>The cursor to be displayed when the mouse is over this pointer.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Shape" xml:space="preserve">
    <value>Shape of the custom map area. Effects the coordinates that must be set so that the shape is drawn correctly.</value>
  </data>
  <data name="DescriptionAttributeTypeName" xml:space="preserve">
    <value>Calculated value type.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapFillGradientType" xml:space="preserve">
    <value>The fill gradient type of the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeTopImageTransColor" xml:space="preserve">
    <value>The transparent color of the top image.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Coordinates" xml:space="preserve">
    <value>Coordinates of the map area. The Shape property determines how many coordinates are required to correctly draw the shape.</value>
  </data>
  <data name="ExceptionInvalidParent" xml:space="preserve">
    <value>Cannot locate "{0}".</value>
  </data>
  <data name="DescriptionAttributeCommon" xml:space="preserve">
    <value>Indicates that map area is custom. </value>
  </data>
  <data name="DescriptionAttributeStateIndicator_ImageTransparency" xml:space="preserve">
    <value>Determines the transparency of the image in percents. This property is only used if the Image property is set.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_MajorTickMark" xml:space="preserve">
    <value>The major tick marks attributes of this scale.</value>
  </data>
  <data name="ExceptionWebPixelSizeWidth" xml:space="preserve">
    <value>The width must be set in pixels.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_IsPercentBased" xml:space="preserve">
    <value>Determines if the state's start and end values are in percentages of indicator minimum and maximum.</value>
  </data>
  <data name="DescriptionAttributeState_StartValue" xml:space="preserve">
    <value>The start and end values determine when the state is activated.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_RefreshRate" xml:space="preserve">
    <value>The refresh rate of the entire gauge container, in redraws per second.</value>
  </data>
  <data name="CategoryPointerCap" xml:space="preserve">
    <value>Pointer Cap</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapStyle" xml:space="preserve">
    <value>The style of the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapWidth" xml:space="preserve">
    <value>Determines the width of the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapImage" xml:space="preserve">
    <value>The image to be used for the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapOnTop" xml:space="preserve">
    <value>Determines if the cap is on top of the pointer or below it.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_FontAngle" xml:space="preserve">
    <value>An additional fixed amount in degrees by which the label will be rotated.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapFillColor" xml:space="preserve">
    <value>The fill color of the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapImageOrigin" xml:space="preserve">
    <value>The point on the image that represents the pointer origin (in pixels).</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_Click" xml:space="preserve">
    <value>Fires when the user clicks on the control.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_AntiAliasing" xml:space="preserve">
    <value>The smoothing (antialiasing) mode.</value>
  </data>
  <data name="ExceptionDatabindState" xml:space="preserve">
    <value>Cannot perform data binding when input value state is in playback, data binding, or suspended mode.</value>
  </data>
  <data name="DescriptionAttributeZOrder4" xml:space="preserve">
    <value>Determines the Z order of this gauge in the gauge container.</value>
  </data>
  <data name="ExceptionGdiNonInitialized" xml:space="preserve">
    <value>Internal error. GDI engine is not initialized.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_DynamicWidth" xml:space="preserve">
    <value>The width to which the gauge panel should grow/shrink.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerRangeLeave" xml:space="preserve">
    <value>Occurs when a pointer leaves a range.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerRotateGradient" xml:space="preserve">
    <value>Determines if the gradient of the marker should rotate or remain static.</value>
  </data>
  <data name="DescriptionAttributeKnob_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the knob.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerRangeEnter" xml:space="preserve">
    <value>Occurs when a pointer enters a range.</value>
  </data>
  <data name="DescriptionAttributeState_FillHatchStyle" xml:space="preserve">
    <value>The pattern style of the state.</value>
  </data>
  <data name="ExceptionWebPixelSize" xml:space="preserve">
    <value>The height must be set in pixels.</value>
  </data>
  <data name="ExceptionSvgMaximumGradients" xml:space="preserve">
    <value>SVG Graphics object - The maximum number for gradients is:{0}</value>
  </data>
  <data name="DescriptionAttributeInputValue_CalculatedValues" xml:space="preserve">
    <value>Calculated values collection</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_GaugeContainer" xml:space="preserve">
    <value>Gauge for Windows Forms provides the ability to implement a variety of rich interactive gauges and dashboards.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_TextColor" xml:space="preserve">
    <value>The text color of the custom label.</value>
  </data>
  <data name="DescriptionAttributeGaugeLocation_X" xml:space="preserve">
    <value>The X value of the location. </value>
  </data>
  <data name="ExceptionHotRegionInitialize" xml:space="preserve">
    <value>The element "{0}" is not initialized.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Digits" xml:space="preserve">
    <value>The total number of digits that will be displayed.</value>
  </data>
  <data name="ExceptionLocateIProviderFailed" xml:space="preserve">
    <value>Cannot locate input value with name "{0}"</value>
  </data>
  <data name="ExceptionHistoryCannotNull" xml:space="preserve">
    <value>The sourceHistory parameter cannot be null</value>
  </data>
  <data name="DescriptionAttributeBackFrame_Shape" xml:space="preserve">
    <value>The overall frame shape, which can be circular or rectangular.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_Style" xml:space="preserve">
    <value>The pre-defined style that determines the overall appearance of the frame.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Visible" xml:space="preserve">
    <value>Determines the visibility of the gauge image.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_MapEnabled" xml:space="preserve">
    <value>Determines if client-side image maps are enabled.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_Image" xml:space="preserve">
    <value>The image to be used as a frame.</value>
  </data>
  <data name="DescriptionAttributeGradientDensity" xml:space="preserve">
    <value>Determines the density of the gradient effect. The value is between 0 and 100 percent.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapReflection" xml:space="preserve">
    <value>Determines if the knob cap has a reflection effect.</value>
  </data>
  <data name="DescriptionAttributeInputValue_ValueFieldMember" xml:space="preserve">
    <value>The name of field of the data source that provides the value content of the history items</value>
  </data>
  <data name="DescriptionAttributeMapAreaID" xml:space="preserve">
    <value>The unique ID of this map area</value>
  </data>
  <data name="ExceptionInvalidKeywordFormat" xml:space="preserve">
    <value>Invalid keyword format. "{0}"</value>
  </data>
  <data name="ExceptionInvalidImageMissingFormat" xml:space="preserve">
    <value>Image URL do not contain the #SEQ formatter.</value>
  </data>
  <data name="DescriptionAttributeName" xml:space="preserve">
    <value>The name of the value.</value>
  </data>
  <data name="DescriptionAttributeDate" xml:space="preserve">
    <value>Current date stamp of value.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_MapAreas" xml:space="preserve">
    <value>Map area collection, which stores custom map area objects.</value>
  </data>
  <data name="ExceptionPlaybackDataEmpty" xml:space="preserve">
    <value>There is no data for playback. The history is empty.</value>
  </data>
  <data name="ExceptionSvgInvalidOutput" xml:space="preserve">
    <value>SVG Graphics Object - SVG Output Writer is null</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_ResetWhenLoading" xml:space="preserve">
    <value>Determines if object properties are reset to their default values prior to loading.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_ResizeMode" xml:space="preserve">
    <value>Determines if the font will be automatically resized so that the text will always fit. This property is used only if the indicator style is text.</value>
  </data>
  <data name="DescriptionAttributeKnob_FillColor" xml:space="preserve">
    <value>The fill color of the knob.</value>
  </data>
  <data name="DescriptionAttributeMapAreaType" xml:space="preserve">
    <value>The target type of the map area</value>
  </data>
  <data name="ExceptionSvgInvalidGradient" xml:space="preserve">
    <value>SVG Graphics object - Gradient type is not defined.</value>
  </data>
  <data name="DescriptionAttributeReversed" xml:space="preserve">
    <value>Determines if the direction of the scale is reversed.</value>
  </data>
  <data name="DescriptionAttributeLinearRange_StartWidth" xml:space="preserve">
    <value>The start width of the range. Measured as a percentage of the size of the gauge (height for horizontal gauges, width for vertical gauges).</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the indicator.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueRateOfChange_RateOfChangePeriodType" xml:space="preserve">
    <value>Gets or sets the rate of change period type.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerStyle" xml:space="preserve">
    <value>Determines the marker style if this knob is of type marker.</value>
  </data>
  <data name="CategoryOutOfRangeAppearance" xml:space="preserve">
    <value>Default Appearance</value>
  </data>
  <data name="DescriptionAttributeKnob_ImageHueColor" xml:space="preserve">
    <value>The hue color to be applied to the knob image.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerWidth" xml:space="preserve">
    <value>Determines the width of the knob marker if this knob is of type knob. Measured in percents of the knob width.</value>
  </data>
  <data name="DescriptionAttributePointerBase_Width" xml:space="preserve">
    <value>The width of the pointer, measured as a percentage.</value>
  </data>
  <data name="CategoryLabelsAndTickMarks" xml:space="preserve">
    <value>Labels and Tick Marks</value>
  </data>
  <data name="DescriptionAttributeState_TriggerDelayType" xml:space="preserve">
    <value>The type of the TriggerDelay value.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_ZOrder" xml:space="preserve">
    <value>Determines the Z order of the numeric indicator in the gauge container.</value>
  </data>
  <data name="DescriptionAttributeKnob_FillGradientType" xml:space="preserve">
    <value>The primary fill gradient type of the knob.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Style" xml:space="preserve">
    <value>Determines the style of the numeric indicator.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Value" xml:space="preserve">
    <value>The current value of the indicator.</value>
  </data>
  <data name="DescriptionAttributeRefreshRateType" xml:space="preserve">
    <value>Gets or sets the rate of refresh type.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_RenderAsControl" xml:space="preserve">
    <value>Determines if the GaugeContainer should be rendered as a WinForms control.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the cap shadow would appear. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_TextAntiAliasingQuality" xml:space="preserve">
    <value>The quality of all text antialiasing.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_LinearGauges" xml:space="preserve">
    <value>A collection containing all linear gauges of the control.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_ValueChanged" xml:space="preserve">
    <value>Occurs after a value has changed.</value>
  </data>
  <data name="DescriptionAttributeTextColor5" xml:space="preserve">
    <value>The text color of the scale labels.</value>
  </data>
  <data name="DescriptionAttributePointers" xml:space="preserve">
    <value>A collection containing all pointers of this gauge.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_FillHatchStyle" xml:space="preserve">
    <value>The primary fill pattern style of the indicator when it is in its default state.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_Font" xml:space="preserve">
    <value>Specifies the font of this custom label.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_Name" xml:space="preserve">
    <value>The name of this custom label.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerPosition" xml:space="preserve">
    <value>Determines how far from the knob center the marker would be positioned.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BackGradientType" xml:space="preserve">
    <value>The gradient type of the gauge label's background.</value>
  </data>
  <data name="DescriptionAttributeImageResolution" xml:space="preserve">
    <value>Image resolution to be used with the gauge control.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_DecimalColor" xml:space="preserve">
    <value>The color of the decimal digits.</value>
  </data>
  <data name="DescriptionAttributeMinorTickMarkInt" xml:space="preserve">
    <value>The minor tick marks attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BackColor" xml:space="preserve">
    <value>The color of the background.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_AutoLayout" xml:space="preserve">
    <value>Determines if the location and size of all radial and linear gauges is to be calculated automatically for best fit.</value>
  </data>
  <data name="DescriptionAttributeBorderWidth10" xml:space="preserve">
    <value>The line width of the scale bar's border.</value>
  </data>
  <data name="ExceptionSvgInvalidWriter" xml:space="preserve">
    <value>SVG Graphics Object - Invalid Text Writer.</value>
  </data>
  <data name="DescriptionAttributeMultiValueSeparator" xml:space="preserve">
    <value>Separator to be used with the multiple value parameters</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Location" xml:space="preserve">
    <value>The location of the gauge inside the gauge container. The coordinates are measured as a percentage of the container's width/height.</value>
  </data>
  <data name="DescriptionAttributeNamedImage_NamedImage" xml:space="preserve">
    <value>Image with a unique name, saved as a resource.</value>
  </data>
  <data name="DescriptionAttributeInputValue_DateFieldMember" xml:space="preserve">
    <value>The name of the data source field that provides the date content of the history items.</value>
  </data>
  <data name="DescriptionAttributeImageTransparency5" xml:space="preserve">
    <value>The transparency level of the image</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_ShowSign" xml:space="preserve">
    <value>Determines which sign (plus or minus) to show.</value>
  </data>
  <data name="TraceImageFrameRenderingComplete" xml:space="preserve">
    <value>Image based frame rendering complete.</value>
  </data>
  <data name="DescriptionAttributeVisible3" xml:space="preserve">
    <value>Determines the visibility of the gauge.</value>
  </data>
  <data name="DescriptionAttributeVisible7" xml:space="preserve">
    <value>Determines the visibility of the pointer.</value>
  </data>
  <data name="DescriptionAttributeVisible6" xml:space="preserve">
    <value>Determines the visibility of the labels.</value>
  </data>
  <data name="DescriptionAttributeVisible9" xml:space="preserve">
    <value>Determines the visibility of the range.</value>
  </data>
  <data name="DescriptionAttributeWidth" xml:space="preserve">
    <value>The width of the pointer.</value>
  </data>
  <data name="DescriptionAttributeLinearRange_EndWidth" xml:space="preserve">
    <value>The width of the range at the end in percentage of the size of the gauge (height for horizontal gauges, width for vertical gauges).</value>
  </data>
  <data name="ExceptionXamlGeometryNotSupported" xml:space="preserve">
    <value>The stream geometry command {0} is not supported.</value>
  </data>
  <data name="ExceptionImageLoaderInvalidLocation" xml:space="preserve">
    <value>Can't load image from this location: {0}</value>
  </data>
  <data name="DescriptionAttributeSize5" xml:space="preserve">
    <value>The size of the gauge inside the gauge container. The coordinates are measured as a percentage of the container's width and height.</value>
  </data>
  <data name="DescriptionAttributeState" xml:space="preserve">
    <value>Gets the state (Interactive,Playback, etc) of this input value.</value>
  </data>
  <data name="AccessibilityKnobName" xml:space="preserve">
    <value>Knob {0}</value>
  </data>
  <data name="DescriptionAttributeText5" xml:space="preserve">
    <value>The text to be displayed.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_RefreshRate" xml:space="preserve">
    <value>Determines how often the indicator is refreshed per second.</value>
  </data>
  <data name="DescriptionAttributeName9" xml:space="preserve">
    <value>The name of the pointer.</value>
  </data>
  <data name="DescriptionAttributeName3" xml:space="preserve">
    <value>The name of the gauge.</value>
  </data>
  <data name="DescriptionAttributeFont4" xml:space="preserve">
    <value>Determines the font of the position.</value>
  </data>
  <data name="DescriptionAttributeFont3" xml:space="preserve">
    <value>Specifies the font of the labels.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_NumericIndicators" xml:space="preserve">
    <value>A collection containing all numeric indicators of the control.</value>
  </data>
  <data name="DescriptionAttributeHref7" xml:space="preserve">
    <value>The Href of the scale.</value>
  </data>
  <data name="DescriptionAttributeHref3" xml:space="preserve">
    <value>The Href of the gauge.</value>
  </data>
  <data name="DescriptionAttributeHref8" xml:space="preserve">
    <value>The Href of the range.</value>
  </data>
  <data name="TraceStartingRenderingDynamicElements" xml:space="preserve">
    <value>Start rendering of dynamic elements.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Parent" xml:space="preserve">
    <value>Determines the parent element, which affects the indicator's coordinate system..</value>
  </data>
  <data name="DescriptionAttributeImageOrigin_NotSet" xml:space="preserve">
    <value>Determines if the image origin is not set.</value>
  </data>
  <data name="DescriptionAttributeDampeningSweepTime" xml:space="preserve">
    <value>The time it takes in seconds to make a full sweep (travel from the minimum to the maximum).</value>
  </data>
  <data name="DescriptionAttributeKnob_Interactive" xml:space="preserve">
    <value>Determines whether the user can rotate the knob with the mouse by clicking and dragging.</value>
  </data>
  <data name="ExceptionCircularReference" xml:space="preserve">
    <value>Circular reference detected.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the numeric indicator.</value>
  </data>
  <data name="ExceptionSerializerUnsupportedAttribute" xml:space="preserve">
    <value>Binary deserialization does not support 'IgnoreUnknownAttributes' property.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_TopImage" xml:space="preserve">
    <value>The image to be displayed on top of the gauge container.</value>
  </data>
  <data name="DescriptionAttributeMapAreaCollection_MapAreaCollection" xml:space="preserve">
    <value>Map areas collection.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Ranges" xml:space="preserve">
    <value>Represents the indicator's collection of numeric ranges.</value>
  </data>
  <data name="AccessibilityLinearGaugeName" xml:space="preserve">
    <value>Linear gauge {0}</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameColor" xml:space="preserve">
    <value>The color of the frame, but not the color of its back.</value>
  </data>
  <data name="DescriptionAttributeShadowOffset4" xml:space="preserve">
    <value>Determines how far to the right and down the shadow will appear. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeShadowOffset3" xml:space="preserve">
    <value>Determines how far to the right and down the shadow will be drawn. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the gauge label.</value>
  </data>
  <data name="DescriptionAttributeBaseValueName" xml:space="preserve">
    <value>Base value name. This is the name of input or calculated value to be linked to.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameStyle" xml:space="preserve">
    <value>The pre-defined style that determines the overall appearance of the frame.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameShape" xml:space="preserve">
    <value>The overall frame shape, which can be circular or rectangular.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerFillGradientEndColor" xml:space="preserve">
    <value>The end color of the knob marker's fill gradient.</value>
  </data>
  <data name="DescriptionAttributeCapImageHueColor" xml:space="preserve">
    <value>The hue color to be applied to the cap image.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameWidth" xml:space="preserve">
    <value>The width of the frame. Measured as a percentage of width/height.</value>
  </data>
  <data name="ExceptionSerializerInvalidPropertyName" xml:space="preserve">
    <value>Invalid format of the serializable content string. Property name not set.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_SelectionMarkerColor" xml:space="preserve">
    <value>Determines the fill color of the markers of a selected element.</value>
  </data>
  <data name="ExceptionUiTypeEditorEnum" xml:space="preserve">
    <value>UI type editor may be set for the enumerations only</value>
  </data>
  <data name="ExceptionInvalidServiceContainer" xml:space="preserve">
    <value>Valid Service Container object must be provided</value>
  </data>
  <data name="DescriptionAttributeFormatString3" xml:space="preserve">
    <value>The format string that is to be used for all labels.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_MinorTickMark" xml:space="preserve">
    <value>The minor tick mark attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeCircularRange_EndWidth" xml:space="preserve">
    <value>The end width of the range. Measured as a percent of the radius of the scale that owns the range.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Selected" xml:space="preserve">
    <value>Determines if the indicator visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeKnob_FillHatchStyle" xml:space="preserve">
    <value>The primary fill pattern style of the knob.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Location" xml:space="preserve">
    <value>The location of the indicator inside the gauge container. The coordinates are measured as a percentage of the container's width/height.</value>
  </data>
  <data name="ExceptionMapDurationArgument" xml:space="preserve">
    <value>MapToDurationType: invalid argument.</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_Format" xml:space="preserve">
    <value>Format used to serialize the gauge data.</value>
  </data>
  <data name="DescriptionAttributeMinimum3" xml:space="preserve">
    <value>The start value of the scale.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_FormatString" xml:space="preserve">
    <value>The format string of the numeric indicator.</value>
  </data>
  <data name="DescriptionAttributeSelected7" xml:space="preserve">
    <value>Determines if the gauge visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeSelected4" xml:space="preserve">
    <value>Determines if the range visually appears selected.</value>
  </data>
  <data name="ExceptionLocationFormat" xml:space="preserve">
    <value>Incorrect string format. The X, Y of the location must be specified e.g. "0,0"</value>
  </data>
  <data name="DescriptionAttributeKnob_CapVisible" xml:space="preserve">
    <value>Determines if the cap in the center of the knob is visible.</value>
  </data>
  <data name="DescriptionAttributeFillColor8" xml:space="preserve">
    <value>The fill color of the range.</value>
  </data>
  <data name="DescriptionAttributeFillColor5" xml:space="preserve">
    <value>The fill color of the scale's bar.</value>
  </data>
  <data name="DescriptionAttributeFillColor4" xml:space="preserve">
    <value>The fill color of the tick mark.</value>
  </data>
  <data name="DescriptionAttributeFillColor3" xml:space="preserve">
    <value>The fill color of the pointer.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_SnappingEnabled" xml:space="preserve">
    <value>Determines if snapping of the indicator's value to a given interval is enabled.</value>
  </data>
  <data name="CollectionEditorMoveDown" xml:space="preserve">
    <value>Move the selected item down.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BackGradientEndColor" xml:space="preserve">
    <value>The end color of the frame's back gradient.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerFillHatchStyle" xml:space="preserve">
    <value>The fill pattern style of the knob marker.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_TopImage" xml:space="preserve">
    <value>The image to be used on top of the gauge container.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_LinearGauges" xml:space="preserve">
    <value>A collection containing all linear gauges in the control.</value>
  </data>
  <data name="DescriptionAttributeKnob_Name" xml:space="preserve">
    <value>The name of the knob.</value>
  </data>
  <data name="DescriptionAttributeInteractive3" xml:space="preserve">
    <value>Determines whether the user can move the pointer with the mouse by clicking and dragging.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_NamedImages" xml:space="preserve">
    <value>Named images collection. Named images are saved as resources.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Transparency" xml:space="preserve">
    <value>Determines the transparency of the image. Measured as a percentage.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_DampeningEnabled" xml:space="preserve">
    <value>Determines if the value movement will be dampened.</value>
  </data>
  <data name="ExceptionNegativeValue" xml:space="preserve">
    <value>Value cannot be negative.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_ShadowIntensity" xml:space="preserve">
    <value>The intensity of all shadows, measured as a percentage.</value>
  </data>
  <data name="DescriptionAttributeMarkerStyle4" xml:space="preserve">
    <value>Determines the marker style if this pointer is of type marker.</value>
  </data>
  <data name="GaugeDesignException" xml:space="preserve">
    <value>Gauge Exception:  </value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_TextShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the text shadow will be.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Printing" xml:space="preserve">
    <value>Gauge printing object.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_SeparatorWidth" xml:space="preserve">
    <value>The line width of the separator, Measured in % of the indicator.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_LoadingDataText" xml:space="preserve">
    <value>The message to be displayed when the Windows Forms control is loading its data.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_SeparatorColor" xml:space="preserve">
    <value>The color of the lines that separate the digits.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_TagAttributes" xml:space="preserve">
    <value>Additional attributes that are to be placed inside the rendered tag.</value>
  </data>
  <data name="DescriptionAttributeBackFrame" xml:space="preserve">
    <value>The frame attributes of the gauge or gauge container.</value>
  </data>
  <data name="DescriptionAttributeCompanyName" xml:space="preserve">
    <value>Microsoft Corporation</value>
  </data>
  <data name="DescriptionAttributeBorderStyle3" xml:space="preserve">
    <value>The line style of the border.</value>
  </data>
  <data name="DescriptionAttributeBorderStyle8" xml:space="preserve">
    <value>The line style of the range border.</value>
  </data>
  <data name="DescriptionAttributeBorderStyle9" xml:space="preserve">
    <value>The line style of the scale bar's border.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Width" xml:space="preserve">
    <value>The width of the scale bar.</value>
  </data>
  <data name="ExceptionInvalidImageFormat" xml:space="preserve">
    <value>Invalid image URL format. #SEQ formatter must be followed by (300,3), where 300 is a max sequence number and 3 is an image file time to live.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapFillHatchStyle" xml:space="preserve">
    <value>The fill pattern style of the pointer cap.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Parent" xml:space="preserve">
    <value>Determines the parent element, which affects the indicator's coordinate system.</value>
  </data>
  <data name="DescriptionAttributeInRangeBarPointerColor" xml:space="preserve">
    <value>The fill color of a bar pointer that occurs within the range.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerScaleLeave" xml:space="preserve">
    <value>Occurs when a pointer's value falls outside of the scale.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PointerScaleEnter" xml:space="preserve">
    <value>Occurs when a pointer's value falls within the scale.</value>
  </data>
  <data name="DescriptionAttributeReportParameters" xml:space="preserve">
    <value>A collection of name / value pairs used for report drilldown</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapVisible" xml:space="preserve">
    <value>Determines if the cap in the center of the pointer is visible.</value>
  </data>
  <data name="TraceStartingPaint" xml:space="preserve">
    <value>Starting Paint.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_States" xml:space="preserve">
    <value>Represents the indicator's collection of states.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_ImageUrl" xml:space="preserve">
    <value>The URL where the gauge image is saved, when an image or input tag is used for rendering.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_RealTimeData" xml:space="preserve">
    <value>Fires during a real-time data request.</value>
  </data>
  <data name="GaugeDesignStack" xml:space="preserve">
    <value>Stack Trace: 
</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Href" xml:space="preserve">
    <value>The Href of the numeric indicator.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Name" xml:space="preserve">
    <value>The name of the numeric indicator.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Font" xml:space="preserve">
    <value>Specifies the font of the digits.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_ZOrder" xml:space="preserve">
    <value>Determines the Z order of the indicator in the gauge container.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Size" xml:space="preserve">
    <value>The size of the gauge inside the gauge container. The coordinates are measured as a percentage of the container's width/height.</value>
  </data>
  <data name="DescriptionAttributeBorderWidth5" xml:space="preserve">
    <value>The line width of the range border.</value>
  </data>
  <data name="DescriptionAttributeBorderWidth9" xml:space="preserve">
    <value>The line width of the border.</value>
  </data>
  <data name="DescriptionAttributeImageSizing" xml:space="preserve">
    <value>The appearance of the gauge if it does not conform to the specified size.</value>
  </data>
  <data name="ExceptionPropertyNegative" xml:space="preserve">
    <value>The {0} property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeStartValue" xml:space="preserve">
    <value>The start value of the range.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_ClipImage" xml:space="preserve">
    <value>Determines if the image is to be clipped to the frame outline. This property is used only when the Image property is set.</value>
  </data>
  <data name="TraceFinishedRenderingDynamicElements" xml:space="preserve">
    <value>Rendering of dynamic elements complete.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_ViewStateContent" xml:space="preserve">
    <value>The view state to be persisted on the server.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_Type" xml:space="preserve">
    <value>Determines if the pointer type is marker or bar.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapFillHatchStyle" xml:space="preserve">
    <value>The fill pattern style of the knob cap.</value>
  </data>
  <data name="ExceptionImagemapInvalidPolygon" xml:space="preserve">
    <value>Invalid number of coordinates for the polygon map area shape. "x1,y1,x2,y2...xn,yn" Each x,y pair contains the coordinates of one vertex of the polygon.</value>
  </data>
  <data name="ExceptionInvalidPlacementType" xml:space="preserve">
    <value>Internal error. Invalid placement type specified.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_OffString" xml:space="preserve">
    <value>The string to be displayed if the Value is Double.NaN.</value>
  </data>
  <data name="DescriptionAttributeLabelStyle" xml:space="preserve">
    <value>The label attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_BorderStyle" xml:space="preserve">
    <value>The line style of the indicator border.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_BorderWidth" xml:space="preserve">
    <value>The line width of the indicator's border when the indicator is in its default state. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_TextColor" xml:space="preserve">
    <value>The text color of the gauge label.</value>
  </data>
  <data name="ExceptionInvalidObjectType" xml:space="preserve">
    <value>The collection {0} cannot accept this object. {1} object type required.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_StartAngle" xml:space="preserve">
    <value>The start angle of the scale in degrees (0 to 360).</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_BorderColor" xml:space="preserve">
    <value>The color of the indicator border.</value>
  </data>
  <data name="AccessibilityCircularPointerName" xml:space="preserve">
    <value>Circular pointer {0}</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Visible" xml:space="preserve">
    <value>Determines the visibility of the indicator.</value>
  </data>
  <data name="DescriptionAttributeDataSource" xml:space="preserve">
    <value>Gets or sets the source containing a list of values used to populate history data. DateFieldMember and ValueFieldMember properties must be also set.</value>
  </data>
  <data name="ExceptionDecimalsNegative" xml:space="preserve">
    <value>The decimals property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_StartMargin" xml:space="preserve">
    <value>Determines the distance between the start of the linear gauge and the start of the scale in percent.</value>
  </data>
  <data name="DescriptionAttributePointerBase_MarkerLength" xml:space="preserve">
    <value>Determines the length of the marker if the pointer is of type marker.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_NeedleStyle" xml:space="preserve">
    <value>Determines the needle style if the type is set to needle.</value>
  </data>
  <data name="DescriptionAttributeGaugeCore_BuildNumber" xml:space="preserve">
    <value>Control build number.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the indicator's map area.</value>
  </data>
  <data name="TraceStartRenderingImageFrame" xml:space="preserve">
    <value>Start rendering image based frame.</value>
  </data>
  <data name="SerializerCollectionDefaultError" xml:space="preserve">
    <value>Serializer can not create new collection item for object</value>
  </data>
  <data name="DescriptionAttributeGaugeCore_ControlType" xml:space="preserve">
    <value>Control build type.</value>
  </data>
  <data name="DescriptionAttributeInputValue_Value" xml:space="preserve">
    <value>Gets and sets the value.</value>
  </data>
  <data name="DescriptionAttributeParentObject3" xml:space="preserve">
    <value>Gets object reference to the parent object. If there is not valid parent element the result is null.</value>
  </data>
  <data name="DescriptionAttributeMultiplier" xml:space="preserve">
    <value>Amount by which the scale's values are multiplied before being displayed.</value>
  </data>
  <data name="ExceptionListUniqueName" xml:space="preserve">
    <value>{0} cannot contain duplicate elements by name.  </value>
  </data>
  <data name="DescriptionAttributePlacement" xml:space="preserve">
    <value>Determines if the pointer should touch the scale bar on the inside or the outside.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BorderColor" xml:space="preserve">
    <value>The color of the numeric indicator's border.</value>
  </data>
  <data name="DescriptionAttributeCollection" xml:space="preserve">
    <value>The named element's parent collection.</value>
  </data>
  <data name="DescriptionAttributeCircularLabelStyle_RotateLabels" xml:space="preserve">
    <value>Determines if labels are rotated along with their scale.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BorderWidth" xml:space="preserve">
    <value>The line width of the numeric indicator's border.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BorderStyle" xml:space="preserve">
    <value>The line style of the numeric indicator's border.</value>
  </data>
  <data name="CollectionEditorMoveUp" xml:space="preserve">
    <value>Move the selected item up.</value>
  </data>
  <data name="DescriptionAttributeFontAngle" xml:space="preserve">
    <value>An additional fixed amount in degrees by which the position label will be rotated.</value>
  </data>
  <data name="DescriptionAttributeSnappingInterval" xml:space="preserve">
    <value>The interval to use when snapping is enabled. If 0 it will snap to the smallest tick mark interval.</value>
  </data>
  <data name="DescriptionAttributeFontUnit3" xml:space="preserve">
    <value>Determines if the font size is measured as a percentage of the parent, or in units specified by the Font.Unit property.</value>
  </data>
  <data name="DescriptionAttributeParentElement" xml:space="preserve">
    <value>Reference to parent element of the parent collection</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_SerializableContent" xml:space="preserve">
    <value>Comma separated list of serializable (Save/Load/Reset) properties.</value>
  </data>
  <data name="DescriptionAttributeMinimumPin" xml:space="preserve">
    <value>Attributes for the minimum pin of the scale.</value>
  </data>
  <data name="DescriptionAttributeCircularGauge_Knobs" xml:space="preserve">
    <value>A collection containing all knobs of this gauge.</value>
  </data>
  <data name="DescriptionAttributeBorderWidth" xml:space="preserve">
    <value>The border width of the tick mark.</value>
  </data>
  <data name="CategoryBehavior" xml:space="preserve">
    <value>Behavior</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_BorderStyle" xml:space="preserve">
    <value>The line style of the gauge container's border.</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_NonSerializableContent" xml:space="preserve">
    <value>Comma separated list of non-serializable (Save/Load/Reset) properties.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_BorderWidth" xml:space="preserve">
    <value>The line width of the gauge container's border.</value>
  </data>
  <data name="DescriptionAttributeFontUnit" xml:space="preserve">
    <value>Determines if the font size is measured as a percentage of the parent or in units specified in the Font.Unit property.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_BorderColor" xml:space="preserve">
    <value>The color of the gauge container's border.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBackGradientType" xml:space="preserve">
    <value>The thermometer back gradient type.</value>
  </data>
  <data name="DescriptionAttributeTickMarksOnTop" xml:space="preserve">
    <value>Determines if the tick marks should drawn over pointers.</value>
  </data>
  <data name="AccessibilityNumericIndicatorName" xml:space="preserve">
    <value>Numeric indicator {0}</value>
  </data>
  <data name="DefaultMeazureStringSimbol" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="DescriptionAttributeBorderColor6" xml:space="preserve">
    <value>The color of the scale bar's border.</value>
  </data>
  <data name="DescriptionAttributeBorderColor4" xml:space="preserve">
    <value>The color of the range border.</value>
  </data>
  <data name="DescriptionAttributeBorderColor5" xml:space="preserve">
    <value>The color of the border.</value>
  </data>
  <data name="DescriptionAttributeBorderColor3" xml:space="preserve">
    <value>The border color of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_OutOfRangeString" xml:space="preserve">
    <value>The string to be displayed if the value is out of range.</value>
  </data>
  <data name="ExceptionSerializerInvalidObjectType" xml:space="preserve">
    <value>Serializer do not support objects of type "{0}".</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Size" xml:space="preserve">
    <value>The size of the gauge image inside the gauge container. The coordinates are in percents.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Name" xml:space="preserve">
    <value>The name of the gauge image.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Href" xml:space="preserve">
    <value>The Href of the gauge image.</value>
  </data>
  <data name="TraceFinishedRenderingStaticElements" xml:space="preserve">
    <value>Rendering of static elements complete.</value>
  </data>
  <data name="ExceptionInvalidImageUrlTag" xml:space="preserve">
    <value>Image URL can not be empty when rendering chart as image tag.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_SnappingInterval" xml:space="preserve">
    <value>The interval to use when snapping is turned on. If 0 there will be no snapping.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_NamedImages" xml:space="preserve">
    <value>A collection containing all named images in the control.</value>
  </data>
  <data name="ExceptionDuplicateObjectFailed" xml:space="preserve">
    <value>Invalid attempt to insert an object that already exists in collection "{0}"</value>
  </data>
  <data name="ExceptionSerializerUnknownProperty" xml:space="preserve">
    <value>Can't deserialize property. Unknown property name "{0}" in object "{1}"</value>
  </data>
  <data name="ExceptionElementNotFound" xml:space="preserve">
    <value>{0} with the name "{1}" cannot be found in the {2} collection.</value>
  </data>
  <data name="ExceptionDecimalsDigitsDrror" xml:space="preserve">
    <value>The decimals must be less than the digits.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_FillGradientType" xml:space="preserve">
    <value>The primary fill gradient type of the indicator when it is in its default state.</value>
  </data>
  <data name="DescriptionAttributeGauge_AspectRatio" xml:space="preserve">
    <value>Determines the aspect ratio of the gauge in terms of width over height. If this value is set to 2, it means that the guage should be twice as wide as it is tall.</value>
  </data>
  <data name="ExceptionSerializerInvalidConstructor" xml:space="preserve">
    <value>Can't deserialize property. Can't find default public constructor for type "{0}".</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_MapAreaAttributes" xml:space="preserve">
    <value>Other attributes of the image's map area.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueRateOfChange_RateOfChangePeriod" xml:space="preserve">
    <value>Gets or sets rate of change period.</value>
  </data>
  <data name="DescriptionAttributeParent5" xml:space="preserve">
    <value>Determines the parent element. This is used for the coordinate system.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Custom" xml:space="preserve">
    <value>Indicates that the map area is custom.</value>
  </data>
  <data name="DescriptionAttributeKnob_ImageOrigin" xml:space="preserve">
    <value>The point on the image that represents the knob center (in pixels).</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Parent" xml:space="preserve">
    <value>The name of the parent element, which affects its coordinate system.</value>
  </data>
  <data name="DescriptionAttributeFillGradientEndColor5" xml:space="preserve">
    <value>The end color of the fill gradient.</value>
  </data>
  <data name="DescriptionAttributeFillGradientEndColor3" xml:space="preserve">
    <value>The end color of the scale bar fill gradient.</value>
  </data>
  <data name="CategoryAppearance" xml:space="preserve">
    <value>Appearance</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_Type" xml:space="preserve">
    <value>Determines if the pointer type is needle, marker or bar.</value>
  </data>
  <data name="DescriptionAttributeDistanceFromScale3" xml:space="preserve">
    <value>The distance from the tip of the pointer to the scale. Measured as a percent.</value>
  </data>
  <data name="DescriptionAttributeDistanceFromScale6" xml:space="preserve">
    <value>A value by which the labels will be offset from their normal position.</value>
  </data>
  <data name="DescriptionAttributeDistanceFromScale4" xml:space="preserve">
    <value>Determines the offset of the tick mark from its normal position.</value>
  </data>
  <data name="DescriptionAttributeDistanceFromScale5" xml:space="preserve">
    <value>Determines how far away the labels will be from the scale. Measured as a percentage of the width or height of the associated scale's parent object</value>
  </data>
  <data name="DescriptionAttributeDistanceFromScale8" xml:space="preserve">
    <value>The distance from the range to the scale. Measured as a percent of the radius of the scale that owns the range.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapImageTransColor" xml:space="preserve">
    <value>The transparent color of the knob cap image.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_Placement" xml:space="preserve">
    <value>Determines the placement of the label, relative to its scale.</value>
  </data>
  <data name="ExceptionIntervalNegative" xml:space="preserve">
    <value>The interval value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeEnableGradient" xml:space="preserve">
    <value>Determines whether or not a gradient effect is used for the tick mark.</value>
  </data>
  <data name="DescriptionAttributeNamedImage_Image" xml:space="preserve">
    <value>Image object to be used as a named image.</value>
  </data>
  <data name="DescriptionAttributeImageHueColor" xml:space="preserve">
    <value>The hue color to be applied to the pointer image.</value>
  </data>
  <data name="AccessibilityLabelName" xml:space="preserve">
    <value>Gauge label {0}</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_ToolTip" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the gauge image.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapRotateGradient" xml:space="preserve">
    <value>Determines if the gradient of the cap should rotate or remain static.</value>
  </data>
  <data name="DescriptionAttributeIntervalOffset4" xml:space="preserve">
    <value>Determines the amount by which the scale's tick marks and labels will be offset. </value>
  </data>
  <data name="DescriptionAttributeIntervalOffset3" xml:space="preserve">
    <value>Interval offset of the labels. </value>
  </data>
  <data name="DescriptionAttributeInterval3" xml:space="preserve">
    <value>Determines how often the tick marks will be drawn.</value>
  </data>
  <data name="DescriptionAttributeInterval4" xml:space="preserve">
    <value>Determines how often the scale's tick marks and labels will be displayed.</value>
  </data>
  <data name="DescriptionAttributeCircularLabelStyle_AllowUpsideDown" xml:space="preserve">
    <value>Determines if labels can be rotated by more than 90 degrees.</value>
  </data>
  <data name="ExceptionUiMissingContext" xml:space="preserve">
    <value>Context instance is not a Gauge object.</value>
  </data>
  <data name="ExceptionSerializerInvalidFlag" xml:space="preserve">
    <value>Serializer - Unsupported serialization content flag.</value>
  </data>
  <data name="DescriptionAttributeFillGradientEndColor" xml:space="preserve">
    <value>The end color of the pointer's fill gradient.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBulbOffset" xml:space="preserve">
    <value>Determines the offset of the thermometer bulb from the zero position.</value>
  </data>
  <data name="DescriptionAttributeLinearScale_Position" xml:space="preserve">
    <value>Determines the position of the scale.</value>
  </data>
  <data name="DescriptionAttributeInterval" xml:space="preserve">
    <value>Determines how often the labels will show.</value>
  </data>
  <data name="ExceptionBadDatasourceFields" xml:space="preserve">
    <value>The data source does not support the IEnumerable interface OR some of the provided field names are empty.</value>
  </data>
  <data name="DescriptionAttributeCircularPointer_CapFillGradientEndColor" xml:space="preserve">
    <value>The end color of the pointer cap fill gradient.</value>
  </data>
  <data name="ExceptionInvalidIndexer" xml:space="preserve">
    <value>Invalid indexer argument type. Valid types are int OR string</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BackHatchStyle" xml:space="preserve">
    <value>The pattern style of the background.</value>
  </data>
  <data name="ImageUIOpenFileFilter" xml:space="preserve">
    <value>All Image Files|*.jpg;*.jpeg;*.jpe;*.jif;*.bmp;*.png;*.gif;*.ico;*.emf;*.wmf|Bitmap Files (*.bmp)|*.bmp|GIF Files (*.gif)|*.gif|JPEG Files (*.jpg; *.jpeg; *.jpe; *.jif )|*.jpg;*.jpeg;*.jpe;*.jfif|Meta Files (*.emf; *.wmf)|*.emf,*.wmf|PNG Files (*.png)|*.png|All Files (*.*)|*.*</value>
  </data>
  <data name="ExceptionXamlBrushNotSupported" xml:space="preserve">
    <value>The brush {0} is not supported.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Values" xml:space="preserve">
    <value>A collection containing all input values in the control.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameGradientEndColor" xml:space="preserve">
    <value>The end color of the frame gradient.</value>
  </data>
  <data name="DescriptionAttributeShowEndLabels" xml:space="preserve">
    <value>Determines if the end labels of the scale are visible.</value>
  </data>
  <data name="CollectionEditorClone" xml:space="preserve">
    <value>Clone the selected item.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapFillGradientType" xml:space="preserve">
    <value>The fill gradient type of the knob cap.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_Visible" xml:space="preserve">
    <value>Determines the visibility of the label.</value>
  </data>
  <data name="DescriptionAttributeInRangeLabelColor" xml:space="preserve">
    <value>The color of the labels that occur within the range.</value>
  </data>
  <data name="AccessibilityLinearPointerName" xml:space="preserve">
    <value>Linear pointer {0}</value>
  </data>
  <data name="DescriptionAttributeEndValue3" xml:space="preserve">
    <value>The end value of the range.</value>
  </data>
  <data name="GaugeDesignSite" xml:space="preserve">
    <value>Site: {0} 

</value>
  </data>
  <data name="DescriptionAttributeGaugeSize_Width" xml:space="preserve">
    <value>The Width value of the size.</value>
  </data>
  <data name="DescriptionAttributeSelected10" xml:space="preserve">
    <value>Determines if the scale visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeKnob_Selected" xml:space="preserve">
    <value>Determines if the knob visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_DistanceFromScale" xml:space="preserve">
    <value>The amount by which the label will be offset from its normal position.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_CircularGauges" xml:space="preserve">
    <value>A collection containing all radial gauges of the control.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BackGradientEndColor" xml:space="preserve">
    <value>The end color of the fill gradient. Used for gradients and hatching.</value>
  </data>
  <data name="DescriptionAttributeNumericRange_DigitColor" xml:space="preserve">
    <value>The color of the digits when the indicator's value is in range.</value>
  </data>
  <data name="ExceptionPeriodTimespanArgument" xml:space="preserve">
    <value>PeriodToTimeSpan : argument PeriodType cannot be NotSet.</value>
  </data>
  <data name="DescriptionAttributeGaugeSize_Height" xml:space="preserve">
    <value>The Height value of the size.</value>
  </data>
  <data name="DescriptionAttributeInputValue_HistoryDepth" xml:space="preserve">
    <value>Gets or sets the history depth.</value>
  </data>
  <data name="AccessibilityCircularRangeName" xml:space="preserve">
    <value>Circular range {0}</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_DataSource" xml:space="preserve">
    <value>Gets or sets the data source containing a list of values used to populate history data. The DateFieldMember and ValueFieldMember properties must be also set.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameGradientType" xml:space="preserve">
    <value>The gradient type of the frame.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_AutoLayout" xml:space="preserve">
    <value>Determines if the location and size of all radial and linear gauges is to be calculated automatically for the best fit.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Name" xml:space="preserve">
    <value>Map area name.</value>
  </data>
  <data name="DescriptionAttributeMapArea_Href" xml:space="preserve">
    <value>URL target of the map area.</value>
  </data>
  <data name="DescriptionAttributeLocation6" xml:space="preserve">
    <value>Determines the location of the position (in degrees or percent), relative to the zero.</value>
  </data>
  <data name="DescriptionAttributeLocation5" xml:space="preserve">
    <value>The location of the gauge inside the gauge container. The coordinates are measured as a percentage of the container's width and height.</value>
  </data>
  <data name="DescriptionAttributeValueLimit" xml:space="preserve">
    <value>Value limit, which controls when the ValueLimitOverflow event is raised.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_TickMarkStyle" xml:space="preserve">
    <value>The tick mark attributes for this custom label.</value>
  </data>
  <data name="ExceptionImagemapInvalidRectangle" xml:space="preserve">
    <value>Invalid number of coordinates for the rectangle map area shape. Four coordinates must be provided: x,y coordinates of the upper-left corner followed by x,y coordinates for the bottom-right corner.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_RealTimeDataInterval" xml:space="preserve">
    <value>Determines how often (in seconds) the Windows Forms control will poll the Web server in order to retrieve real time data.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_ZOrder" xml:space="preserve">
    <value>Determines the Z order of the gauge image in the gauge container.</value>
  </data>
  <data name="LabelFormatPrecisionMsgCaption" xml:space="preserve">
    <value>Error</value>
  </data>
  <data name="DescriptionAttributeParentObject" xml:space="preserve">
    <value>Gets an object reference to the parent object. If there is no valid parent element the result is null.</value>
  </data>
  <data name="ExceptionOutOfRangeMinClose" xml:space="preserve">
    <value>The argument cannot be less than {0}.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BackColor" xml:space="preserve">
    <value>The color of the frame's background.</value>
  </data>
  <data name="ExceptionDuplicateNameFailed" xml:space="preserve">
    <value>This element cannot duplicate its name with another element in the same collection.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueLinear_Multiplier" xml:space="preserve">
    <value>The multiplier (m) in linear formula f(x) = x*m + a.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_RightToLeft" xml:space="preserve">
    <value>Indicates whether the control should draw right-to-left for RTL languages.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_AllowUpsideDown" xml:space="preserve">
    <value>Determines if the label can be rotated by more than 90 degrees.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_BackHatchStyle" xml:space="preserve">
    <value>The pattern style of the back.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_DynamicHeight" xml:space="preserve">
    <value>The height to which the gauge panel should grow/shrink.</value>
  </data>
  <data name="ExceptionSerializerMissingSerivice" xml:space="preserve">
    <value>The gauge serializer does not provide service of type: {0}</value>
  </data>
  <data name="DescriptionAttributeTopImage4" xml:space="preserve">
    <value>The image to be used on top of the gauge.</value>
  </data>
  <data name="DescriptionAttributeState_TriggerDelay" xml:space="preserve">
    <value>Determines how long the indicator value needs to be in range before this state is activated.</value>
  </data>
  <data name="DescriptionAttributeKnob_ScaleName" xml:space="preserve">
    <value>The name of the scale to which this knob belongs.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBackHatchStyle" xml:space="preserve">
    <value>The pattern style of the thermometer's back.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_NumericIndicators" xml:space="preserve">
    <value>A collection containing all numeric indicators in the control.</value>
  </data>
  <data name="DescriptionAttributeState_Text" xml:space="preserve">
    <value>The text to be displayed when this state is activated.</value>
  </data>
  <data name="DescriptionAttributeState_Font" xml:space="preserve">
    <value>Specifies the font of the state.</value>
  </data>
  <data name="DescriptionAttributeState_Name" xml:space="preserve">
    <value>The name of the state.</value>
  </data>
  <data name="CategoryPosition" xml:space="preserve">
    <value>Position</value>
  </data>
  <data name="DescriptionAttributeRangeBase_DistanceFromScale" xml:space="preserve">
    <value>The distance from the range to the scale in percentage of the size of the gauge (height for horizontal gauges, width for vertical gauges).</value>
  </data>
  <data name="ExceptionSizeFormat" xml:space="preserve">
    <value>Incorrect string format. The Width, Height of the size must be specified e.g. "100,100"</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_StateIndicators" xml:space="preserve">
    <value>A collection containing all indicators in the control.</value>
  </data>
  <data name="DescriptionAttributeSelected" xml:space="preserve">
    <value>Determines if the pointer visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeInRangeTimeoutType" xml:space="preserve">
    <value>The type of the InRangeTimeout property.</value>
  </data>
  <data name="NotImplemented" xml:space="preserve">
    <value>{0} is not implemented yet</value>
  </data>
  <data name="ExceptionGenerateNameFailed" xml:space="preserve">
    <value>Internal exception : Generating unique name failed.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBackGradientEndColor" xml:space="preserve">
    <value>The end color of the thermometer's back gradient.</value>
  </data>
  <data name="DescriptionAttributeRangeBase_Placement" xml:space="preserve">
    <value>Determines where the range should be placed relative to the scale bar.</value>
  </data>
  <data name="TraceStartingRenderingStaticElements" xml:space="preserve">
    <value>Start rendering of static elements.</value>
  </data>
  <data name="DescriptionAttributeInputValue_DataMember" xml:space="preserve">
    <value>Gets or sets the specific data member in a multimember data source to bind to the history.</value>
  </data>
  <data name="ExceptionMapPeriodTypeArgument" xml:space="preserve">
    <value>MapToPeriodType: argument DurationType cannot be Infinity or Count.</value>
  </data>
  <data name="ExceptionIntervalOffsetNegative" xml:space="preserve">
    <value>The interval offset value cannot be less than zero.</value>
  </data>
  <data name="ExceptionTraceManagerUnsupportedType" xml:space="preserve">
    <value>Trace Manager does not provide service of type: {0}</value>
  </data>
  <data name="DescriptionAttributeKnob_Cursor" xml:space="preserve">
    <value>The cursor to be displayed when the mouse is over this knob.</value>
  </data>
  <data name="ExceptionMustInRange" xml:space="preserve">
    <value>The argument must be in range ({0},{1}).</value>
  </data>
  <data name="DescriptionAttributeY" xml:space="preserve">
    <value>The Y value of the location.</value>
  </data>
  <data name="DescriptionAttributeMarkerLength4" xml:space="preserve">
    <value>Determines the length of the marker if this pointer is of type marker.</value>
  </data>
  <data name="LabelFormatDescriptionF" xml:space="preserve">
    <value>The number is converted to the most compact decimal form, using fixed or scientific notation. The precision specifier determines the number of significant digits in the resulting string.</value>
  </data>
  <data name="LabelFormatDescriptionG" xml:space="preserve">
    <value>The number is converted to a string of the form "-ddd.ddd…" where each 'd' indicates a digit (0-9). The string starts with a minus sign if the number is negative. The precision specifier indicates the desired number of decimal places.</value>
  </data>
  <data name="LabelFormatDescriptionE" xml:space="preserve">
    <value>The number is converted to a string of the form "-d.ddd…E+ddd" or "-d.ddd…e+ddd", where each 'd' indicates a digit (0-9). The string starts with a minus sign if the number is negative. One digit always precedes the decimal point. The precision specifier indicates the desired number of digits after the decimal point.</value>
  </data>
  <data name="LabelFormatDescriptionC" xml:space="preserve">
    <value>The number is converted to a string that represents a currency amount. The conversion is controlled by the system currency format information. The precision specifier indicates the desired number of decimal places.</value>
  </data>
  <data name="LabelFormatDescriptionN" xml:space="preserve">
    <value>The number is converted to a string of the form "-d,ddd,ddd.ddd…", where each 'd' indicates a digit (0-9). The string starts with a minus sign if the number is negative. Thousand separators are inserted between each group of three digits to the left of the decimal point. The precision specifier indicates the desired number of decimal places.</value>
  </data>
  <data name="LabelFormatDescriptionP" xml:space="preserve">
    <value>The number is converted to a string that represents a percent. The precision specifier indicates the desired number of decimal places.</value>
  </data>
  <data name="DescriptionAttributeCircularPinLabel_AllowUpsideDown" xml:space="preserve">
    <value>Determines is labels can be rotated by more than 90 degrees.</value>
  </data>
  <data name="ExceptionXamlInvalidCanvasSize" xml:space="preserve">
    <value>The root canvas must have its Width and Height defined.</value>
  </data>
  <data name="DescriptionAttributeImageOrigin_X" xml:space="preserve">
    <value>The X value of the image origin.</value>
  </data>
  <data name="CategoryValues" xml:space="preserve">
    <value>Values</value>
  </data>
  <data name="TraceStartRenderingFrame" xml:space="preserve">
    <value>Start rendering frame.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapFillColor" xml:space="preserve">
    <value>The fill color of the knob cap.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_CircularGauges" xml:space="preserve">
    <value>A collection containing all radial gauges in the control.</value>
  </data>
  <data name="ExceptionInvalidIndexer2" xml:space="preserve">
    <value>Invalid indexer argument.</value>
  </data>
  <data name="DescriptionAttributeResizeMode" xml:space="preserve">
    <value>Determines if the font will be automatically resized so that the text will always fit.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_BackColor" xml:space="preserve">
    <value>The background color of the gauge label.</value>
  </data>
  <data name="TraceStartRendering" xml:space="preserve">
    <value>Start rendering {0}.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_TransparentColor" xml:space="preserve">
    <value>Specifies the color which will become transparent. Used only when the image type is PNG.</value>
  </data>
  <data name="ExceptionSerializerHashProperty" xml:space="preserve">
    <value>Binary serialization error. Properties "{0}" and "{1}" have the same hash code.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Selected" xml:space="preserve">
    <value>Determines if the gauge image visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_Location" xml:space="preserve">
    <value>The location of the gauge image inside the gauge container. The coordinates are measured as a percentage of the container's width and height.</value>
  </data>
  <data name="DescriptionAttributePrintingManager_PrintDocument" xml:space="preserve">
    <value>A reusable object that sends output to a printer. Can be used for custom print routines.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_Value" xml:space="preserve">
    <value>The position along the scale where the custom label will be displayed.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Multiplier" xml:space="preserve">
    <value>Amount by which the indicator's value is multiplied before being displayed.</value>
  </data>
  <data name="ExceptionInvalidImageDualFormat" xml:space="preserve">
    <value>Image URL can not contain both #UID and #SEQ formatters.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_AntiAliasing" xml:space="preserve">
    <value>The smoothing (antialiasing) mode, applied to all gauge container elements.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_FontUnit" xml:space="preserve">
    <value>Determines if the font size is measured as a percentage of the parent or in units specified by the Font.Unit property.</value>
  </data>
  <data name="DescriptionAttributeState_FillGradientType" xml:space="preserve">
    <value>The primary fill gradient type of the indicator when this state is activated.</value>
  </data>
  <data name="DescriptionAttributeState_FillColor" xml:space="preserve">
    <value>Gets or sets the fill color of the indicator when this state is activated.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueIntegral_IntegralBase" xml:space="preserve">
    <value>Gets or sets integral base value.</value>
  </data>
  <data name="ExceptionUiTypeEditorEnumInt32" xml:space="preserve">
    <value>UI type editor may be set for the enumerations with Int32 underlying type only.</value>
  </data>
  <data name="CategoryStates" xml:space="preserve">
    <value>States</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerLength" xml:space="preserve">
    <value>Determines the length of the knob marker if this knob is of type knob. Measured in percents of the knob width.</value>
  </data>
  <data name="DescriptionAttributePlacement6" xml:space="preserve">
    <value>Determines the position of the tick marks relative to the scale.</value>
  </data>
  <data name="DescriptionAttributePlacement7" xml:space="preserve">
    <value>Determines where the range should be placed relative to the scale.</value>
  </data>
  <data name="DescriptionAttributePlacement5" xml:space="preserve">
    <value>Determines the position of the labels relative to the scale.</value>
  </data>
  <data name="DescriptionAttributePlacement3" xml:space="preserve">
    <value>Determines the placement of the position's label, relative to the scale.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_IndicatorStyle" xml:space="preserve">
    <value>Determines if the style of the indicator.</value>
  </data>
  <data name="DescriptionAttributeRanges3" xml:space="preserve">
    <value>A collection containing all ranges of this gauge.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_SweepAngle" xml:space="preserve">
    <value>The sweep angle of the scale in degrees (0 to 360).</value>
  </data>
  <data name="DescriptionAttributeState_Image" xml:space="preserve">
    <value>The image to be used for this state.</value>
  </data>
  <data name="DescriptionAttributeLength3" xml:space="preserve">
    <value>The length of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeGaugeImage_ResizeMode" xml:space="preserve">
    <value>Determines whether or not the image will be stretched to fit the specified size.</value>
  </data>
  <data name="AccessibilityCircularGaugeName" xml:space="preserve">
    <value>Circular gauge {0}</value>
  </data>
  <data name="ExceptionSvgInvalidSize" xml:space="preserve">
    <value>SVG Graphics Object - Invalid SVG Picture Size.</value>
  </data>
  <data name="DescriptionAttributePeriodType" xml:space="preserve">
    <value>Period type in DurationType. Represents type of period units.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_TextAlignment" xml:space="preserve">
    <value>Specifies how the text is aligned within the gauge label.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Width" xml:space="preserve">
    <value>Width of the gauge container, measured in UnitType.Pixel.</value>
  </data>
  <data name="DescriptionAttributePointerBase_MarkerStyle" xml:space="preserve">
    <value>Determines the marker style if the pointer is of type marker.</value>
  </data>
  <data name="DefaultFontFamily" xml:space="preserve">
    <value>Microsoft Sans Serif</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueLinear_Adder" xml:space="preserve">
    <value>The addend (a) in linear formula f(x) = x*m + a.</value>
  </data>
  <data name="ExceptionSerializerInvalidBinary" xml:space="preserve">
    <value>Deserialization error. Invalid binary format.   </value>
  </data>
  <data name="DescriptionAttributeLinearScale_MinorTickMark" xml:space="preserve">
    <value>The minor tick marks attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BackGradientType" xml:space="preserve">
    <value>The gradient type of the background.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_WinControlUrl" xml:space="preserve">
    <value>Absolute or relative URL of the Windows Forms control (WinGauge2005.dll).</value>
  </data>
  <data name="DescriptionAttributeBackFrame_FrameHatchStyle" xml:space="preserve">
    <value>The pattern style of the frame.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_ScaleFactor" xml:space="preserve">
    <value>Determines the mumber by which the indicator is scaled.</value>
  </data>
  <data name="ExceptionSerializerInvalidContentFormat" xml:space="preserve">
    <value>Invalid format of the serializable content string.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_Labels" xml:space="preserve">
    <value>A collection containing gauge labels in the control.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapFillGradientEndColor" xml:space="preserve">
    <value>The end color of the cap fill gradient.</value>
  </data>
  <data name="ExceptionImagemapInvalidObject" xml:space="preserve">
    <value>Object to be inserted or added is not a MapArea object.</value>
  </data>
  <data name="ExceptionDigitsNegative" xml:space="preserve">
    <value>The digits property value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeClipContent" xml:space="preserve">
    <value>Determines if the content of the gauge is clipped to the gauge bounds or its frame.</value>
  </data>
  <data name="CategoryValue" xml:space="preserve">
    <value>Value</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PostPaint" xml:space="preserve">
    <value>Called just after a gauge element's background is painted.</value>
  </data>
  <data name="CategoryRange" xml:space="preserve">
    <value>Range</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Visible" xml:space="preserve">
    <value>Determines the visibility of the gauge label.</value>
  </data>
  <data name="DescriptionAttributeBarStart" xml:space="preserve">
    <value>Determines where a bar pointer will start if the pointer is of type bar.</value>
  </data>
  <data name="DescriptionAttributeBarStyle" xml:space="preserve">
    <value>Determines the bar style if the pointer is of type bar.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_GlassEffect" xml:space="preserve">
    <value>Determines the glass effect of the frame.</value>
  </data>
  <data name="ExceptionDigitsDecimals" xml:space="preserve">
    <value>The digits must be greater than the decimals.</value>
  </data>
  <data name="TracePaintComplete" xml:space="preserve">
    <value>Paint complete.</value>
  </data>
  <data name="CategoryImage" xml:space="preserve">
    <value>Image</value>
  </data>
  <data name="DescriptionAttributeMapArea_ToolTip" xml:space="preserve">
    <value>Tooltip of the map area.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_StateIndicators" xml:space="preserve">
    <value>A collection containing all indicators of the control.</value>
  </data>
  <data name="ExceptionInvalidValue" xml:space="preserve">
    <value>Invalid property value.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_ShowLeadingZeros" xml:space="preserve">
    <value>Determines whether or not leading zeros are displayed.</value>
  </data>
  <data name="ExceptionValueDbNull" xml:space="preserve">
    <value>Cannot get value because it is DBNull.</value>
  </data>
  <data name="TraceRenderingComplete" xml:space="preserve">
    <value>Rendering of {0} complete.</value>
  </data>
  <data name="CategoryKnobCap" xml:space="preserve">
    <value>Knob Cap</value>
  </data>
  <data name="DescriptionAttributeLinearScale_EndMargin" xml:space="preserve">
    <value>Determines the distance between the end of the linear gauge and the end of the scale in percent.</value>
  </data>
  <data name="DescriptionAttributeBackFrame_ImageHueColor" xml:space="preserve">
    <value>The hue color to be applied to the image.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PrePaint" xml:space="preserve">
    <value>Called just before a gauge element's background is painted.</value>
  </data>
  <data name="ExceptionLocateCProviderFailed" xml:space="preserve">
    <value>Cannot locate calculated value with name "{0}"</value>
  </data>
  <data name="DescriptionAttributeNamedElement_Tag" xml:space="preserve">
    <value>Gets or sets an object that contains data to associate with the item.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_EnableViewState" xml:space="preserve">
    <value>Gets or sets a value indicating whether the control persists its view state.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerStyle" xml:space="preserve">
    <value>Determines the style of the thermometer.</value>
  </data>
  <data name="ExceptionImagemapInvalidCircle" xml:space="preserve">
    <value>Invalid number of coordinates for the circle map area shape. Three coordinates must be provided: the center of the circle (x,y), followed by the radius.</value>
  </data>
  <data name="ExceptionDurationNegative" xml:space="preserve">
    <value>The duration value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_LoadingControlImage" xml:space="preserve">
    <value>The image to be displayed when the Windows Forms control is loading its data.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_LoadingDataImage" xml:space="preserve">
    <value>The image to be displayed when the Windows Forms control is loading its data.</value>
  </data>
  <data name="DescriptionAttributeCustomLabel_RotateLabel" xml:space="preserve">
    <value>Determines if the label will be rotated along with its scale.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Text" xml:space="preserve">
    <value>The text of the indicator when it is in its default state.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Size" xml:space="preserve">
    <value>The size of the indicator inside the gauge container. The coordinates are measured as a percentage of the container's width/height.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Font" xml:space="preserve">
    <value>Specifies the font of the default state.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Name" xml:space="preserve">
    <value>The name of the indicator.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Href" xml:space="preserve">
    <value>The Href of the indicator.</value>
  </data>
  <data name="SvgHeaderComment" xml:space="preserve">
    <value>Microsoft Gauge SVG Converter</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_FillGradientEndColor" xml:space="preserve">
    <value>The end color of the indicator when it is in its default state.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBulbSize" xml:space="preserve">
    <value>Determines the size of the thermometer bulb.</value>
  </data>
  <data name="DescriptionAttributeCircularGauge_PivotPoint" xml:space="preserve">
    <value>The point around which the needle rotates. The coordinates are in percent.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_CurrentState" xml:space="preserve">
    <value>Read-only property that represents the name of the current state.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Labels" xml:space="preserve">
    <value>A collection containing labels of the control.</value>
  </data>
  <data name="DescriptionAttributeMaximum3" xml:space="preserve">
    <value>The end value of the scale.</value>
  </data>
  <data name="DescriptionAttributeShadowOffset" xml:space="preserve">
    <value>Determines how far to the right and down the shadow would appear. Measured in pixels.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Selected" xml:space="preserve">
    <value>Determines if the gauge label visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeKnob_Visible" xml:space="preserve">
    <value>Determines if the knob is visible.</value>
  </data>
  <data name="ExceptionPeriodNegative" xml:space="preserve">
    <value>The period value cannot be less than zero.</value>
  </data>
  <data name="DescriptionAttributeToolTip8" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the gauge.</value>
  </data>
  <data name="DescriptionAttributeToolTip9" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the range.</value>
  </data>
  <data name="DescriptionAttributeToolTip3" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the scale.</value>
  </data>
  <data name="DescriptionAttributeToolTip5" xml:space="preserve">
    <value>The tool tip to be displayed when the cursor is over the pointer.</value>
  </data>
  <data name="DescriptionAttributeKnob_DampeningEnabled" xml:space="preserve">
    <value>Determines if the knob movement is dampened.</value>
  </data>
  <data name="DescriptionAttributeRSTooltip" xml:space="preserve">
    <value>Provides a tooltip to be displayed on the rendered image.</value>
  </data>
  <data name="CategoryDesign" xml:space="preserve">
    <value>Design</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_DigitColor" xml:space="preserve">
    <value>The color of the digits.</value>
  </data>
  <data name="DescriptionAttributeImageOrigin3" xml:space="preserve">
    <value>The point on the image that represents the pointer origin (in pixels).</value>
  </data>
  <data name="DescriptionAttributeDampeningEnabled3" xml:space="preserve">
    <value>Determines if the pointer movement is dampened.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Images" xml:space="preserve">
    <value>A collection containing gauge images in the control.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Maximum" xml:space="preserve">
    <value>The end value of the numeric indicator. The Minimum and Maximum properties determine the indicator's range.</value>
  </data>
  <data name="AccessibilityLinearScaleName" xml:space="preserve">
    <value>Linear scale {0}</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_ShowDecimalPoint" xml:space="preserve">
    <value>Determines whether or not the decimal point is displayed.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapWidth" xml:space="preserve">
    <value>The width of the knob cap, measured as a percentage of the knob width.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapImage" xml:space="preserve">
    <value>The image to be used for the knob cap.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Compression" xml:space="preserve">
    <value>Jpeg image compression value (0-100 percent).</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_Content" xml:space="preserve">
    <value>Defines the serializable content for the Load, Save and Reset methods.</value>
  </data>
  <data name="DescriptionAttributeKnob_CapImageOrigin" xml:space="preserve">
    <value>The point on the image that represents the knob origin (in pixels).</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_Height" xml:space="preserve">
    <value>Height of the gauge container, measured in UnitType.Pixel.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Value" xml:space="preserve">
    <value>The value of the indicator.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Parent" xml:space="preserve">
    <value>Determines the parent element of the label, which effects its coordinate system.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Style" xml:space="preserve">
    <value>Determines if the style of the indicator.</value>
  </data>
  <data name="ExceptionBadDatasource" xml:space="preserve">
    <value>The data source does not support the IEnumerable interface.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_Images" xml:space="preserve">
    <value>A collection containing gauge images of the control.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_ImageType" xml:space="preserve">
    <value>Determines the type of image to be rendered. Can be Png, Jpg, Bmp, Flash, etc. When the RenderType property is set to RenderType.RealTimeStreaming this property also determines if the real time streaming will be image based or Flash based.</value>
  </data>
  <data name="ExceptionHotRegionSupport" xml:space="preserve">
    <value>The element "{0}" does not support its own coordinate system.</value>
  </data>
  <data name="DescriptionAttributeRefreshRate3" xml:space="preserve">
    <value>The maximum amount of time that can elapse before the calculated value is refreshed.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Angle" xml:space="preserve">
    <value>Determines the angle (in degrees) by which the indicator is rotated.</value>
  </data>
  <data name="DescriptionAttributeIntervalOffset" xml:space="preserve">
    <value>A value by which the tick marks and labels will be offset. </value>
  </data>
  <data name="DescriptionAttributeValue6" xml:space="preserve">
    <value>The value to which this pointer currently points. </value>
  </data>
  <data name="DescriptionAttributeValue8" xml:space="preserve">
    <value>Gets the current value.</value>
  </data>
  <data name="DescriptionAttributeCircularPinLabel_RotateLabel" xml:space="preserve">
    <value>Determines if the position's label is rotated along with the scale.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Image" xml:space="preserve">
    <value>The image to be used when the indicator is in its default state.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_TextAntiAliasingQuality" xml:space="preserve">
    <value>The quality of text antialiasing.</value>
  </data>
  <data name="DescriptionAttributeKnob_MarkerFillColor" xml:space="preserve">
    <value>The fill color of the knob marker.</value>
  </data>
  <data name="ExceptionSerializerInvalidWriter" xml:space="preserve">
    <value>Invalid type of writer object. Can be Stream, TextWriter, XmlWriter or String (file name)</value>
  </data>
  <data name="DescriptionAttributeVisible10" xml:space="preserve">
    <value>Determines the visibility of the scale.</value>
  </data>
  <data name="DescriptionAttributeVisible12" xml:space="preserve">
    <value>Determines whether or not to show the tick marks.</value>
  </data>
  <data name="DescriptionAttributeWidth9" xml:space="preserve">
    <value>The width of the scale bar, measured in percentage of the size of the gauge (height for horizontal gauges, width for vertical gauges).</value>
  </data>
  <data name="DescriptionAttributeWidth7" xml:space="preserve">
    <value>The width of the tick marks.</value>
  </data>
  <data name="DescriptionAttributeLinearGauge_Orientation" xml:space="preserve">
    <value>Determines if the linear gauge is horizontal or vertical.</value>
  </data>
  <data name="DescriptionAttributeCalculatedValueIntegral_IntegralInterval" xml:space="preserve">
    <value>Gets or sets the integral interval.</value>
  </data>
  <data name="ExceptionImageLoaderInvalidUrl" xml:space="preserve">
    <value>Can't load image from this URL:  {0}</value>
  </data>
  <data name="DescriptionAttributeGaugeSerializer_GaugeSerializer" xml:space="preserve">
    <value>Gauge serializer class.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Angle" xml:space="preserve">
    <value>Determines the angle (in degrees) by which this label is rotated.</value>
  </data>
  <data name="DescriptionAttributeKnob_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the knob image.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Visible" xml:space="preserve">
    <value>Determines the visibility of the numeric indicator.</value>
  </data>
  <data name="ExceptionImageLoaderMissingSerivice" xml:space="preserve">
    <value>Image loader do not provide service of type: {0}</value>
  </data>
  <data name="ExceptionMinMax" xml:space="preserve">
    <value>The minimum of the scale must be less than the maximum.</value>
  </data>
  <data name="ExceptionMinLog" xml:space="preserve">
    <value>The Minimum property cannot be less OR equal than 0 on logarithmic scales.</value>
  </data>
  <data name="ExceptionMaxMin" xml:space="preserve">
    <value>The maximum of the scale must be greater than the minimum.</value>
  </data>
  <data name="ExceptionMargin" xml:space="preserve">
    <value>The start margin must be less than the end margin.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_DataSetName" xml:space="preserve">
    <value>The name of the DataSet associated with the gauge.</value>
  </data>
  <data name="ExceptionXamlShapeNotSupported" xml:space="preserve">
    <value>The shape {0} is not supported.</value>
  </data>
  <data name="ExceptioncalCulatedValueProvider" xml:space="preserve">
    <value>CalculatedValue.BaseValueName: Cannot locate value provider with name "{0} "</value>
  </data>
  <data name="DescriptionAttributeInRangeTickMarkColor" xml:space="preserve">
    <value>The color of the scale tick marks that occur within the range.</value>
  </data>
  <data name="NoImageString" xml:space="preserve">
    <value>No
image</value>
  </data>
  <data name="DescriptionAttributeGaugeContainerEvent_PlaybackStateChanged" xml:space="preserve">
    <value>Occurs after playback starts, stops, pauses and resumes.  It also occurs when playback complete.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Selected" xml:space="preserve">
    <value>Determines if the numeric indicator visually appears selected.</value>
  </data>
  <data name="DescriptionAttributeKnob_KnobStyle" xml:space="preserve">
    <value>Determines the marker style if this knob is of type marker.</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer2_Values" xml:space="preserve">
    <value>A collection containing all input values of the control.</value>
  </data>
  <data name="DescriptionAttributeCircularScale_GaugePivotPoint" xml:space="preserve">
    <value>The point around which the needle rotates. The coordinates are in percent of the Gauge's width or height, whichever is smaller.</value>
  </data>
  <data name="ExceptionSerializerIdLoading" xml:space="preserve">
    <value>Can't find property with specified ID while loading data.</value>
  </data>
  <data name="ExceptionSvgWrapStrings" xml:space="preserve">
    <value>SVG Rendering - Wrap String Error.</value>
  </data>
  <data name="ExceptionSerializerInvalidReader" xml:space="preserve">
    <value>Invalid type of reader object. Can be Stream, TextReader, XmlReader or String (file name)</value>
  </data>
  <data name="DescriptionAttributeGaugeContainer_ShadowIntensity" xml:space="preserve">
    <value>The intensity all shadows, measured as a percentage.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Decimals" xml:space="preserve">
    <value>The total number of decimals that will be shown.</value>
  </data>
  <data name="CategoryData" xml:space="preserve">
    <value>Data</value>
  </data>
  <data name="CategoryMisc" xml:space="preserve">
    <value>Misc</value>
  </data>
  <data name="ExceptionInvalidMarkerType" xml:space="preserve">
    <value>Internal error. Invalid marker type specified.</value>
  </data>
  <data name="DescriptionAttributeStateIndicator_Minimum" xml:space="preserve">
    <value>A number that represents the minimum (start) value of the indicator range.</value>
  </data>
  <data name="DescriptionAttributeShape3" xml:space="preserve">
    <value>Determines the shape of the tick mark.</value>
  </data>
  <data name="AccessibilityCircularScaleName" xml:space="preserve">
    <value>Circular scale {0}</value>
  </data>
  <data name="CategoryLayout" xml:space="preserve">
    <value>Layout</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_Minimum" xml:space="preserve">
    <value>The start value of the numeric indicator. The Minimum and Maximum properties determine the indicator's range.</value>
  </data>
  <data name="DescriptionAttributeLinearPointer_ThermometerBackColor" xml:space="preserve">
    <value>The thermometer's back color.</value>
  </data>
  <data name="DescriptionAttributeLabelStyle3" xml:space="preserve">
    <value>The label attributes of this pin.</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_IndicatorStyle" xml:space="preserve">
    <value>Determines the style of the numeric indicator.</value>
  </data>
  <data name="DescriptionAttributeScales" xml:space="preserve">
    <value>A collection containing all scales of this gauge.</value>
  </data>
  <data name="DescriptionAttributeMajorTickMarkInt" xml:space="preserve">
    <value>The major tick marks attributes of this scale.</value>
  </data>
  <data name="DescriptionAttributeScaleName3" xml:space="preserve">
    <value>The name of the scale to which the range belongs.</value>
  </data>
  <data name="DescriptionAttributeScaleName4" xml:space="preserve">
    <value>The name of the scale to which this pointer belongs.</value>
  </data>
  <data name="AccessibilityLinearRangeName" xml:space="preserve">
    <value>Linear range {0}</value>
  </data>
  <data name="CategoryStyleSpecific" xml:space="preserve">
    <value>Style Specific</value>
  </data>
  <data name="CategoryMarker" xml:space="preserve">
    <value>Marker</value>
  </data>
  <data name="DescriptionAttributeNumericIndicator_BackGradientEndColor" xml:space="preserve">
    <value>The end color of the background gradient.</value>
  </data>
  <data name="AccessibilityGaugeImageName" xml:space="preserve">
    <value>Gauge image {0}</value>
  </data>
  <data name="DescriptionAttributeKnob_FillGradientEndColor" xml:space="preserve">
    <value>The end color of the knob's fill gradient.</value>
  </data>
  <data name="ExceptionParentNotRenderable" xml:space="preserve">
    <value>The "{0}" does not support its own coordinate system.</value>
  </data>
  <data name="LabelFormatInvalidCustomFormat" xml:space="preserve">
    <value>Invalid custom format string</value>
  </data>
  <data name="DescriptionAttributeBackFrame_ImageTransColor" xml:space="preserve">
    <value>The transparent color of the frame's image.</value>
  </data>
  <data name="DescriptionAttributeKnob_Image" xml:space="preserve">
    <value>The image to be used as a knob.</value>
  </data>
  <data name="AccessibilityStateIndicatorName" xml:space="preserve">
    <value>Indicator {0}</value>
  </data>
  <data name="DescriptionAttributeKnob_Style" xml:space="preserve">
    <value>Determines the marker style if this knob is of type marker.</value>
  </data>
  <data name="DescriptionAttributeKnob_Width" xml:space="preserve">
    <value>The width of the knob in percents of the associated scale diameter.</value>
  </data>
  <data name="DescriptionAttributeMaximumPin" xml:space="preserve">
    <value>Attributes for the maximum pin of the scale.</value>
  </data>
  <data name="DescriptionAttributeKnob_Value" xml:space="preserve">
    <value>The value to which this knob currently points.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Text" xml:space="preserve">
    <value>The text to be displayed for the gauge label.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Size" xml:space="preserve">
    <value>The size of the gauge label inside the gauge container. The coordinates are in percents.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Font" xml:space="preserve">
    <value>Specifies the font of the gauge label.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Name" xml:space="preserve">
    <value>The name of the gauge label.</value>
  </data>
  <data name="DescriptionAttributeGaugeLabel_Href" xml:space="preserve">
    <value>The Href of the gauge label.</value>
  </data>
  <data name="DescriptionAttributeFillHatchStyle3" xml:space="preserve">
    <value>The primary fill pattern style of the pointer.</value>
  </data>
  <data name="DescriptionAttributeFillHatchStyle5" xml:space="preserve">
    <value>The fill pattern style of the scale's bar.</value>
  </data>
  <data name="DescriptionAttributeFillHatchStyle7" xml:space="preserve">
    <value>The fill pattern style of the range.</value>
  </data>
  <data name="DescriptionAttributeName11" xml:space="preserve">
    <value>The name of the scale.</value>
  </data>
  <data name="DescriptionAttributeName10" xml:space="preserve">
    <value>Gets and sets the name of the NamedElement</value>
  </data>
  <data name="DescriptionAttributeName13" xml:space="preserve">
    <value>The name of the range.</value>
  </data>
</root>