namespace AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel
{
	internal enum CharSet : byte
	{
		ANSI_CHARSET,
		DEFAULT_CHARSET,
		SYMBOL_CHARSET,
		MAC_CHARSET = 77,
		SHIFTJIS_CHARSET = 0x80,
		HANGEUL_CHARSET,
		HANGUL_CHARSET = 129,
		JOHAB_CHARSET,
		GB2312_CHARSET = 134,
		CHINESEBIG5_CHARSET = 136,
		GREEK_CHARSET = 161,
		TURKISH_CHARSET,
		VIETNAMESE_CHARSET,
		HEBREW_CHARSET = 177,
		ARABIC_CHARSET,
		BALTIC_CHARSET = 186,
		RUSSIAN_CHARSET = 204,
		THAI_CHARSET = 222,
		EASTEUROPE_CHARSET = 238,
		OEM_CHARSET = 0xFF
	}
}
